[KOGITO-1548] - Upgrade Kogito Images to JDK 11
apache/incubator-kie-kogito-images pull request #116
Opened 2020-03-26 14:52 UTC by spolti

Signed-off-by: spolti <fspolti@redhat.com>

2020-03-26 14:52 UTC, spolti commented
waiting a updated jobs-service artifact to update the image, the current artifact is not compatible with java 11.;

2020-03-26 16:02 UTC, ricardozanini requested changes
LGTM! I'm just curious about the jobs-service jar file.

2020-03-26 16:02 UTC, ricardozanini commented on modules/kogito-jobs-service/module.yaml
>      url: https://repository.jboss.org/org/kie/kogito/jobs-service/8.0.0-SNAPSHOT/jobs-service-8.0.0-20200323.063633-114-runner.jar
Since the MD5 changed, won't the file name should be changed as well?

2020-03-26 16:02 UTC, ricardozanini commented on tests/features/kogito-quarkus-ubi8-s2i.feature
> +  @wip
leftovers?

2020-03-26 16:54 UTC, sutaakar approved these changes

2020-03-26 23:11 UTC, spolti commented on modules/kogito-jobs-service/module.yaml
>      url: https://repository.jboss.org/org/kie/kogito/jobs-service/8.0.0-SNAPSHOT/jobs-service-8.0.0-20200323.063633-114-runner.jar
not really, cekit will look the the md5 in local or remote cache before download the file listed on the url tag.
as I build the job-servive jar locally and pushed to the cekit cache the file under url will not be used.

2020-03-26 23:37 UTC, spolti commented on tests/features/kogito-quarkus-ubi8-s2i.feature
> +  @wip
Yes :)

2020-03-27 04:00 UTC, cristianonicolai approved these changes
looks good, just need to figure why artifacts are not showing up on Neuxs

2020-03-27 09:07 UTC, radtriste approved these changes

2020-03-27 12:38 UTC, ricardozanini commented on modules/kogito-jobs-service/module.yaml
>      url: https://repository.jboss.org/org/kie/kogito/jobs-service/8.0.0-SNAPSHOT/jobs-service-8.0.0-20200323.063633-114-runner.jar
Ok, then I assume we will change this one once we have a valid SNAPSHOT.

2020-03-27 12:38 UTC, ricardozanini approved these changes

2020-03-27 13:29 UTC, radtriste commented on tests/features/kogito-quarkus-ubi8-s2i.feature
> +  @wip
be careful on the leftovers still there :)

2020-03-27 13:42 UTC, spolti commented
jobs-service update with the latest snapshot;
0.9.0-rc2 available on quay.

2020-03-27 13:44 UTC, radtriste approved these changes
one leftover. otherwise looks good

2020-03-27 13:44 UTC, radtriste commented on tests/features/kogito-quarkus-ubi8-s2i.feature
> +  @wip
still one `@wip` there

2020-03-27 13:51 UTC, sutaakar approved these changes

2020-03-27 13:52 UTC, spolti commented
@radtriste thanks, remove the wips :)

2020-03-27 13:59 UTC, ricardozanini approved these changes

2020-03-27 14:12 UTC, merged