[master][KOGITO-1636] - Native binary is not recognized in binary bui…
apache/incubator-kie-kogito-images pull request #128
Opened 2020-04-07 22:57 UTC by spolti

…ld when target folder is uploaded
See: https://issues.redhat.com/browse/KOGITO-1636

Bats tests on this PR: https://github.com/kiegroup/kogito-images/pull/120/

Signed-off-by: spolti <fspolti@redhat.com>

2020-04-07 23:28 UTC, spolti commented
tag 0.10.0-rc1 available.

2020-04-08 07:29 UTC, sutaakar approved these changes

2020-04-08 07:29 UTC, radtriste commented
@spolti with which artifacts did you build the 0.10.0-rc1 ?
I cannot see anything in git history about that rc1 ...

asking because jobs-service 0.10.0-rc1 is still failing because of oidc...

2020-04-08 07:45 UTC, radtriste commented on modules/kogito-s2i-core/added/s2i-core
>          fi
should we fail if none of them happen ? (no jar or no native runner)

2020-04-08 08:03 UTC, sutaakar commented on modules/kogito-s2i-core/added/s2i-core
>          fi
Well, not necessarily.
There are 3 different possibilities expected:
- non native Quarkus binary (*runner.jar) - covered here
- native Quarkus binary (*runner) - covered here
- Springboot (or any other, plain *.jar file) - no need to cover here as it doesn't have native option

IMHO this part of code decides whether uploaded content is related to native build or not, relevant just for Quarkus.

2020-04-08 08:20 UTC, radtriste commented on modules/kogito-s2i-core/added/s2i-core
>          fi
oki. forgot about Spring boot.

2020-04-08 08:20 UTC, radtriste approved these changes

2020-04-08 08:28 UTC, sutaakar requested changes
~I tested this change with 0.10.0-rc1 image.
The build passed, however when result image was started it crash with
`Error: Unable to access jarfile /home/kogito/bin/*runner.jar`~

I forgot to set native build flag in CR.
The result image runs correctly.

2020-04-08 09:33 UTC, sutaakar approved these changes

2020-04-08 12:42 UTC, spolti commented
@radtriste I didn't update any snapshot version of jobs-service, data-index or mgmt-console, I can do a separete PR for it and update only these three images, does it sounds good?

2020-04-08 12:47 UTC, radtriste commented
yeah would be great to have intermediate 0.10.0-rcX images with latest snapshot as long as we don't have the pipeline ;)

2020-04-08 15:24 UTC, ricardozanini approved these changes

2020-04-08 15:37 UTC, merged