[KOGITO-1490] - Improve Kogito images README file
apache/incubator-kie-kogito-images pull request #134
Opened 2020-04-09 15:46 UTC by spolti

See: https://issues.redhat.com/browse/KOGITO-1490

Signed-off-by: spolti <fspolti@redhat.com>

2020-04-09 15:49 UTC, spolti commented
Once the PR is reviewed and approved I'll cherry pick it for 0.9.x

2020-04-09 17:18 UTC, sterobin reviewed
@spolti I just focused on the Management Console bit, and some high-level comments and questions. Thanks.

2020-04-09 17:18 UTC, sterobin commented on README.md
> +API.
A few quick points:

* "Kogito processes" lower case
* "Data Index Service" upper case
* Process instance management add-on - You're linking to the runtimes wiki, which we are retiring. Instead, link to this section in the new Kogito docs: https://docs.jboss.org/kogito/release/latest/html_single/#con_bpmn-process-instance-management_kogito-developing-process-services  For any other cross-refs that you use throughout to the runtimes wiki, change to point instead to the Kogito docs page. That page contains 100% of the wiki content now, plus a lot more. But minus the "Developer workflow" intro sections that are now mostly obsolete anyway.
* "REST API" upper case

2020-04-09 17:18 UTC, sterobin commented on README.md
> +might not work properly.
"deploy the Data Index Service capabilities to Kogito services on ..."

2020-04-09 17:18 UTC, sterobin commented on README.md
> +```
So is this the official way we want people to use and start the Console, with docker? I think that's a quick-start method only, for like examples, and last I heard we're moving away from docker and to Podman instead. This came up in Kogito docs. Do you know the more standardized steps to use the Console without relying on Docker? Such as, get a Data Index Service running, then ... what exactly?

2020-04-09 19:22 UTC, ricardozanini approved these changes

2020-04-10 13:52 UTC, radtriste requested changes
please use `podman` instead `docker`

2020-04-10 13:52 UTC, radtriste commented on kogito-management-console-overrides.yaml
> +  - name: "KOGITO_DATAINDEX_HTTP_URL"
Please change this to MANAGEMENT_CONSOLE (or MGMT_CONSOLE ?)

(and also url & description)

2020-04-10 13:52 UTC, radtriste commented on README.md
> +smoothly on any Kubernetes player. There are few sets images which are divided in three different groups which are
`Kubernetes player` => `Kubernetes cluster`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +smoothly on any Kubernetes player. There are few sets images which are divided in three different groups which are
`There are few sets` => ` There are a few sets of images`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +the components, builder and runtime images.
`the components, the builder images and the runtime images.`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +* [Kogito Images](#kogito-container-images) - ok
please remove the `ok` in toc and regenerate it correctly

2020-04-10 13:52 UTC, radtriste commented on README.md
> +To interact with Kogito images you would need to install the needed dependencies so the images can be built and tested.
`with the Kogito images, you would need [...] so that the images`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +            * python packages: docker, docker-squash, odcs-client. All of those can be handled with pip, including CeKit.
`All of those can be handled with pip, including Cekit` => set in new bullet point

2020-04-10 13:52 UTC, radtriste commented on README.md
> +    * GraalVM 19.3.1 Java 11 or higher, useful to test Kogito apps on native mode before create a Container image with it.
`useful to test Kogito apps[...]` => set in new bullet point to be in sync with previous bullet point

2020-04-10 13:52 UTC, radtriste commented on README.md
> +Today, the Kogito images are divided, basically in 2 vectors when we talk about images that would be used to assemble or run
`Today, the Kogito images are divided basically in 2 vectors, when we talk about images that would be used to assemble or run Kogito applications: Runtime image and Builder image. Those are described bellow.`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +### Builder Images
`Kogito Builder images`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +The Builder image is responsible for building the project with Apache Maven and generate the binary that will be used to run the
```
The Kogito Builder Images are responsible for building the project with Apache Maven and generate the binary that will be used by the Runtime images to run the Kogito application.

The current available Kogito Builder images are:

* [quay.io/kiegroup/kogito-quarkus-ubi8-s2i](kogito-quarkus-s2i-overrides.yaml)
* [quay.io/kiegroup/kogito-springboot-ubi8-s2i](kogito-springboot-s2i-overrides.yaml)

The Kogito Quarkus Builder Image allows you to create native image using GraalVM which allows you to have
lightweight and fast applications ready to run on Cloud.
```

2020-04-10 13:52 UTC, radtriste commented on README.md
> +**modules/install** section.
`in the **modules.install** section.`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +This image contains a help message to better understand how to use this image:
This image contains a helper option [...]

2020-04-10 13:52 UTC, radtriste commented on README.md
> +By default, a native build willl be performed, to disable it and perform a normal java build just set the NATIVE build variable to false.
By default, a native build will be performed. To disable it and perform a normal java build just set the NATIVE build environment variable to false.

2020-04-10 13:52 UTC, radtriste commented on README.md
> +Like the example showed in the next topic.
See the next topic for an example.

2020-04-10 13:52 UTC, radtriste commented on README.md
> +On this example, let's use a simple application available on [Kogito Examples](https://github.com/kiegroup/kogito-examples) repository.
`In this example, let's use a simple application available in the [Kogito Examples](https://github.com/kiegroup/kogito-examples) repository.`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +Let's use the *rules-quarkus-helloworld*.
Let's use here the *rules-quarkus-helloworld* example, with native compilation disabled.

2020-04-10 13:52 UTC, radtriste commented on README.md
> +$ docker run -it -p 8080:8080 drools-example:latest
you build `rules-example` but you test `drools-example`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +#### Kogito Spring Boot Builder Image
same here, either use `Kogito Spring Boot Builder Image` or use `Spring Boot Builder Image` in the whole chapter but do not mix.

2020-04-10 13:52 UTC, radtriste commented on README.md
> + * GraalVM 19.3.1 with openjdk 11.0.6
openjdk => OpenJDK

2020-04-10 13:52 UTC, radtriste commented on README.md
> + * OpenJDK 11.0.6
do we need to repeat the `OpenJDK` here ?

2020-04-10 13:52 UTC, radtriste commented on README.md
> +**modules/install** section.
`in the **modules.install** section.`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +The Quarkus Builder Image is equipped with the following components:
The Kogito Quarkus Builder Image

2020-04-10 13:52 UTC, radtriste commented on README.md
> +##### Quarkus Builder Image usage
Kogito Quarkus Builder Image usage

2020-04-10 13:52 UTC, radtriste commented on README.md
> +##### Quarkus - Building a Simple Application
Kogito Quarkus Builder Image example

2020-04-10 13:52 UTC, radtriste commented on README.md
> +The Springboot Builder Image is equipped with the following components:
The Kogito Spring Boot Builder Image

2020-04-10 13:52 UTC, radtriste commented on README.md
> +This image contains a help message to better understand how to use this image:
This image contains a helper option [...]

2020-04-10 13:52 UTC, radtriste commented on README.md
> +##### Spring Boot Builder Image usage
Kogito Spring Boot Builder Image usage

2020-04-10 13:52 UTC, radtriste commented on README.md
> +##### Spring Boot - Building a Simple Application
Kogito Spring Boot Builder Image example

2020-04-10 13:52 UTC, radtriste commented on README.md
> +On this example, let's use a simple application available on [Kogito Examples](https://github.com/kiegroup/kogito-examples) repository.
`In this example, let's use a simple application available in the [Kogito Examples](https://github.com/kiegroup/kogito-examples) repository.`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +With the image built, let's test it:
After the image is built, let's test it:

2020-04-10 13:52 UTC, radtriste commented on README.md
> +With the image built, let's test it:
After the image is built, let's test it:

2020-04-10 13:52 UTC, radtriste commented on README.md
> +On a different shell try the following commands:
In a different shell, try the following commands:

2020-04-10 13:52 UTC, radtriste commented on README.md
> +On a different shell try the following commands:
In a different shell, try the following command:

2020-04-10 13:52 UTC, radtriste commented on README.md
> +### Improving Build Time
should be `####` here or ?

2020-04-10 13:52 UTC, radtriste commented on README.md
> +Time needed to build the application is rather long, mainly due to maven downloading dependencies for the which usually
The time needed to build the application is rather long. This is mainly due to maven downloading all dependencies, which takes several minutes.

2020-04-10 13:52 UTC, radtriste commented on README.md
> +That can be improved by using incremental builds on the source-to-image.
If you are planning to build many times the same application, you can use the incremental builds which will improve drastically the build time.

2020-04-10 13:52 UTC, radtriste commented on README.md
> +Let's start 2 builds with incremental enabled and compare the time spent to build each one:
Let's start 2 builds with the incremental option enabled and compare the time spent to build each one:

2020-04-10 13:52 UTC, radtriste commented on README.md
> +Let's run it again:
And now, let's run it again.

2020-04-10 13:52 UTC, radtriste commented on README.md
> +On the second try you can see the artifacts getting unpacked and reused from the previous build,
In the second try, you can see the artifacts getting unpacked and reused from the previous build.
Now, pay also attention to the time spent to build it. There is a big difference.
In fact, an incremental build reuses the previously built image and it takes advantage of already downloaded artifacts. 
This can significantly improve the build time.

2020-04-10 13:52 UTC, radtriste commented on README.md
`##### Using incremental builds`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +
`##### Using a Maven mirror`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +Another option is to use a Maven Mirror, this can be used together with incremental builds to speed up the build even more.
Another option is to use a Maven Mirror. This can be used together with incremental builds to speed up the build even more.

2020-04-10 13:52 UTC, radtriste commented on README.md
> +To turn it possible we just need to set the **MAVEN_MIRROR_URL88 environment variable when starting a new build, see the example below:
`To turn the Maven Mirror option on, you just need to set the **MAVEN_MIRROR_URL** build environment variable when starting a new build. See the example below:`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +    --env --env MAVEN_MIRROR_URL=http://nexus.apps.local.cloud/nexus/content/groups/public
remove double `--env`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +# First try
`# Third incremental build, with Maven mirror option`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +# First try
`# First incremental build`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +# Second try
`# Second incremental build`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +It is really impressive, if the maven mirror already have all the dependencies there, the build time can be even faster
```
Here you can see that the build time has again been reduced.
If the maven mirror already have all the dependencies there, the build time can be even faster.
```

2020-04-10 13:52 UTC, radtriste commented on README.md
> +### Runtime Images
Kogito Runtime Images

2020-04-10 13:52 UTC, radtriste commented on README.md
> +The Runtime image is responsible for just running the fat jar taken from the Builder image or by doing a binary build
```
The Kogito Runtime Images have 2 behaviors:
* Run the artifacts built by the Kogito Builder Images
* Run your pre-built local artifacts, via what we call a _Binary Build_
For non-native built applications, they have a JRE installed to allow to execute Java applications.

With this approach, we can have smaller and more compact images that do not include any of the build tools or artifacts (like the local maven repository for example).
```

2020-04-10 13:52 UTC, radtriste commented on README.md
> +Today we have the following Runtime Images:
Today we have the following Kogito Runtime Images:

2020-04-10 13:52 UTC, radtriste commented on README.md
> +Binary builds allows you to quick copy the built artifacts into the target *Runtime Image* saving the time needed to build
`A Binary Build allows you to quickly copy the built locally artifacts into the target *Kogito Runtime Image*, saving the time needed to build the final image using the method with Kogito Builder Images.`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +[KJAR](https://developers.redhat.com/blog/2018/03/14/what-is-a-kjar/) stands for Knowledge jar which is a custom JAR file that contains Business Process or Rules and all needed
`kjar` or `KJAR` ?

2020-04-10 13:52 UTC, radtriste commented on README.md
> +[KJAR](https://developers.redhat.com/blog/2018/03/14/what-is-a-kjar/) stands for Knowledge jar which is a custom JAR file that contains Business Process or Rules and all needed
`stands for Knowledge jar which is a custom JAR file that contains a Business Process or Rules and all the needed dependencies and/or files to execute it on the target runtime, either Quarkus or Spring Boot.`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +If you don't have a already existing project, the best way to create a new one is to use Kogito Maven Archetypes
If you don't have already an existing project, the best way to create a new one is to use the Kogito Maven Archetypes to generate a project structure. 
The available archetypes are:

2020-04-10 13:52 UTC, radtriste commented on README.md
> +- [Kogito Quarkus archetype](https://github.com/kiegroup/kogito-runtimes/tree/master/archetypes/kogito-quarkus-archetype)
`archetype` or `Archetype` ?

2020-04-10 13:52 UTC, radtriste commented on README.md
> +Note that, when building Quarkus based application that's **not** a *UberJAR* we also need to copy the **target/lib**
`Note that, when building a Quarkus based application that is **not** a *UberJAR*, we also need to copy the **lib**  folder.`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +
This source structure assumes `that` there is

2020-04-10 13:52 UTC, radtriste commented on README.md
> +This source structure assumes there is no maven project but only business assets stored either directly in the top folder
but only business assets`,` stored either directly

2020-04-10 13:52 UTC, radtriste commented on README.md
>  Business assets are:
Types of Business assets can be:

2020-04-10 13:52 UTC, radtriste commented on README.md
> +- Business Process definition - bpmn2 or just bpmn
```
- Business Process definition - bpmn2 or just bpmn files
- Business Rule definition - drl files
- Business Decision definition - dmn files
```

2020-04-10 13:52 UTC, radtriste commented on README.md
> +Upon build these assets will be copied to generated maven project and built with maven to produce the runnable binary.
Upon build, these assets will be copied to a generated maven project and built with Maven to produce a runnable binary.

2020-04-10 13:52 UTC, radtriste commented on README.md
> +This is a lightweight and compact application container image and contains basically only the JRE.
and `it` contains basically only the JRE.

2020-04-10 13:52 UTC, radtriste commented on README.md
> +This Runtime image is considered a runtime image as it only contains the needed
This Kogito Runtime Image contains only the needed files to execute a pre built Kogito application.

2020-04-10 13:52 UTC, radtriste commented on README.md
> +##### Image usage
`##### Kogito Quarkus JVM Runtime Image usage`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +This image can be used without the image builder, this image has the ability to copy
This is redundant with Binary builds explained earlier

2020-04-10 13:52 UTC, radtriste commented on README.md
> +This image contains a help message to better understand how to use this image:
a helper option

2020-04-10 13:52 UTC, radtriste commented on README.md
> +For this example lets use the [process-quarkus-example](https://github.com/kiegroup/kogito-examples/tree/stable/process-quarkus-example)
`For this example lets use the [process-quarkus-example](https://github.com/kiegroup/kogito-examples/tree/stable/process-quarkus-example).`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +# inspect and running the generated uberjar, for instructions on how to use this example se its README file.
`inspect and run`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +# inspect and running the generated uberjar, for instructions on how to use this example se its README file.
`see its README file.`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +# performing a source to image build
`performing a source to image build to copy the artifacts to the runtime image`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +Once you have checked the example on your local machine follow the steps below:
Once you have checked the example on your local machine follow the steps below.

2020-04-10 13:52 UTC, radtriste commented on README.md
> +Example with UberJAR
`**Example with UberJAR**`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +Example with non uberjar
`**Example with non UberJAR**`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +$ s2i build target/ quay.io/kiegroup/kogito-quarkus-jvm-ubi8:latest process-quarkus-example
we should copy here only the jar ... otherwise, there is not much difference with the non-uberjar example

2020-04-10 13:52 UTC, radtriste commented on README.md
> +Note that this time there is a lib on the **target directory**, the s2i build will take care of copy it to the correct place, just
`take care of copying it`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +Example with UberJAR
add before: `##### Kogito Quarkus JVM Runtime Image examples`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +This Runtime image is considered a runtime image as it only contains the needed
same here: `This Kogito Runtime Image contains only the needed files to execute a pre built Kogito application.`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +This image can be used without the image builder, this image has the ability to copy
This is redundant with Binary builds explained earlier

2020-04-10 13:52 UTC, radtriste commented on README.md
> +##### Image usage
`##### Kogito Quarkus Native Runtime Image usage`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +This image contains a help message to better understand how to use this image:
a helper option

2020-04-10 13:52 UTC, radtriste commented on README.md
> +For this example let's use the same than the previous one, but this time, let's perform a native build
For this example let's use the same than the previous one (process-quarkus-example). But this time, let's perform a native build:

2020-04-10 13:52 UTC, radtriste commented on README.md
> +Note that a binary was generated on the **target directory**, let's use this binary to perform the source-to-image build:
A binary has been generated into the **target directory**.
Let's use this binary to perform the source-to-image build:

2020-04-10 13:52 UTC, radtriste commented on README.md
> +This image can be used without the image builder, this image has the ability to copy
again redundant with Binary builds explained

2020-04-10 13:52 UTC, radtriste commented on README.md
> +##### Image usage
`#### Kogito Spring Boot Runtime Image usage`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +
`##### Kogito Quarkus Native Runtime Image example`

2020-04-10 13:52 UTC, radtriste commented on README.md
`#### Kogito Spring Boot Runtime Image example`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +This image contains a help message to better understand how to use this image:
a helper option

2020-04-10 13:52 UTC, radtriste commented on README.md
> +Note that a binary was generated on the **target directory**, let's use this binary to perform the source-to-image build:
```
A uberjar file has been generated into the **target directory**.
Let's use this uberjar to perform the build:
```

2020-04-10 13:52 UTC, radtriste commented on README.md
> +The Components images can be considered lightweight images that will complement the Kogito core engine by providing
The Kogito Component Images can be considered as lightweight images that will complement the Kogito core engine by providing extra capabilities, like managing the processes on a web UI or providing persistence layer to the Kogito applications.

2020-04-10 13:52 UTC, radtriste commented on README.md
> +Today we have 3 components images:
Today we have 3 Kogito Component Images:

2020-04-10 13:52 UTC, radtriste commented on README.md
> +This service aims for capturing and indexing data produced by one more Kogito runtime services.
The Data Index Service aims

2020-04-10 13:52 UTC, radtriste commented on README.md
> +It depends on a Running Infinispan Server.
The Data Index Service depends on a running Infinispan Server.

2020-04-10 13:52 UTC, radtriste commented on README.md
> +The [Kogito Operator](https://github.com/kiegroup/kogito-cloud-operator) can be used to to deploy data index capabilities to Kogito Services
`The [Kogito Operator](https://github.com/kiegroup/kogito-cloud-operator) can be used to deploy the Kogito Data Index Service to your Kogito infrastructure on a Kubernetes cluster and provide its capabilities to your Kogito applications`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +TODO: add the envs inherited from another modules
TODO ?

2020-04-10 13:52 UTC, radtriste commented on README.md
> +Kogito Job Service is a dedicated lightweight service responsible for scheduling jobs that aim to be fired at a given time.
The Kogito Jobs Service [...]

2020-04-10 13:52 UTC, radtriste commented on README.md
> +The service does not execute the job itself, it triggers a callback that could be an HTTP request on a given endpoint
It does not execute the job itself but it triggers a callback that could be an HTTP request on a given endpoint specified on the job request, or any other callback that could be supported by the service.

2020-04-10 13:52 UTC, radtriste commented on README.md
> +For more information please access this (link)[https://github.com/kiegroup/kogito-runtimes/wiki/Job-Service]
`please visit this link`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +The [Kogito Operator](https://github.com/kiegroup/kogito-cloud-operator) can be used to to deploy data index capabilities to Kogito Services
`The [Kogito Operator](https://github.com/kiegroup/kogito-cloud-operator) can be used to deploy the Kogito Jobs Service to your Kogito infrastructure on a Kubernetes cluster and provide its capabilities to your Kogito applications`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +The [Kogito Operator](https://github.com/kiegroup/kogito-cloud-operator) can be used to to deploy data index capabilities to Kogito Services
`The [Kogito Operator](https://github.com/kiegroup/kogito-cloud-operator) can be used to deploy the Kogito Management Console to your Kogito infrastructure on a Kubernetes cluster and provide its capabilities to your Kogito applications`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +The Management Console allows you to have a intuitive way to manage your Kogito Processes in execution.
The Kogito Management Console

2020-04-10 13:52 UTC, radtriste commented on README.md
> +It depends on a Kogito Data Index service which the Console will connect so it can be able to manage it.
It depends on the Kogito Data Index Service on which the Console will connect to so it can be able to manage it.

2020-04-10 13:52 UTC, radtriste commented on README.md
> +If the Data Index url is not provided or not available on the default one (http://localhost:8180) the Management Console
To work correctly, the Kogito Management Console needs the Kogito Data Index Service url. If not provided, it will try to connect to the default one (http://localhost:8180).

2020-04-10 13:52 UTC, radtriste commented on README.md
> +## Contributing with Kogito Images
Contributing to Kogito Images repository

2020-04-10 13:52 UTC, radtriste commented on README.md
> +To build the images for local testing there is a [Makefile](./Makefile) which will do all the hard work for you, with this
```
To build the images for local testing there is a [Makefile](./Makefile) which will do all the hard work for you
With this Makefile you can:
```

2020-04-10 13:52 UTC, radtriste commented on README.md
> +   - This command will build and test all images
Remove this line

2020-04-10 13:52 UTC, radtriste commented on README.md
> +- Build all images with only one command
Build and test all images with only one command

2020-04-10 13:52 UTC, radtriste commented on README.md
> +   - This command will build (TODO build and test together) the desired image
merge the 2 lines

2020-04-10 13:52 UTC, radtriste commented on README.md
> +    - this command will build and push the images to the target repository, default quay.io/kiegroup
Merge the 2 lines

2020-04-10 13:52 UTC, radtriste commented on README.md
> +        - 0.X-latest
X.Y(-latest has been removed)

2020-04-10 13:52 UTC, radtriste commented on README.md
> +        - 0.X.X
X.Y.z

2020-04-10 13:52 UTC, radtriste commented on README.md
> +    - this command will build and push RC images to quay.
merge the 2 lines

2020-04-10 13:52 UTC, radtriste commented on README.md
> +####Image Modules
`#### Image Modules`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +CeKit can use modules to better separate things and reuse these modules on different images.
`to better separate concerns`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +On the Kogito Images we have several CeKit modules that are used during builds. To better understanding
`To better understand the CeKit Modules, please visit [...]`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +- [kogito-data-index](modules/kogito-data-index): Installs and Configure the data-index jar inside the image.
Could we put each documentation line in each module as a first comment (in module.yaml for example).
That would allow to keep up-to-date documentation.
And here we just say to check each `module.yaml` file to understand what it is.
wdyt ?

2020-04-10 13:52 UTC, radtriste commented on README.md
> +Below you can find all images, and to see which modules each image install, please refer to the **modules** section:
For each image, we use a specific `*-overrides.yaml` file which will specific the modules needed.
Please see each file for the installed modules.

2020-04-10 13:52 UTC, radtriste commented on README.md
> +There is two kind of tests that we could run locally and also it is ran by CI, **behave** and **bats** tests.
`that we could run locally and also it is ran by CI` => not needed IMO

2020-04-10 13:52 UTC, radtriste commented on README.md
> +
`#### Behave tests`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +
`#### Bats tests`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +
move that part after bats tests and add 2 subchapters:

`##### Running behave tests`
`##### Writing behave tests`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +CeKit also allow you to run a specific test, suppose you are working on a new feature and add tests to cover your changes.
```
CeKit also allows you to run a specific test.
See [Writing Behave Tests](#writing-behave-tests).
```

2020-04-10 13:52 UTC, radtriste commented on README.md
> +### Writing Bats tests
Put this with bats tests chapter, before behave tests

2020-04-10 13:52 UTC, radtriste commented on README.md
> +## Using Kogito Images to Deploy Apps on OpenShift
This part should be before `Contributing to` part

2020-04-10 13:52 UTC, radtriste commented on README.md
> +Once the images are built and imported into registry (quay.io or internal OpenShift registry)
Once the images are built and imported into a registry (quay.io or any other registry), new applications can be built and deployed within a few steps.

2020-04-10 13:52 UTC, radtriste commented on README.md
> +As first step we need to make the Kogito Images available as Image Stream on the OpenShift. If you have `cluster-admin`
As a first step, we need to make the Kogito Images available as Image Streams in OpenShift.

2020-04-10 13:52 UTC, radtriste commented on README.md
> +rights you can deploy it on the **openshift** namespace, otherwise, deploy it on the namespace you have permission.
deploy it into the namespace where you have permissions.

2020-04-10 13:52 UTC, radtriste commented on README.md
> +$ oc new-build --name=drools-helloworld-builder --image-stream=kogito-quarkus-ubi8-s2i:0.9.0 \
`rules-quarkus-helloworld-builder`

2020-04-10 13:52 UTC, radtriste commented on README.md
> +Once the build is finished, we can now create a new build to copy the generated artifact from the source to image build
Once the build is finished, you can now create

2020-04-10 13:52 UTC, radtriste commented on README.md
> +to the runtime image, to do this execute the following command:
to the Kogito Runtime Image. To do this, execute the following command:

2020-04-10 13:52 UTC, radtriste commented on README.md
> +$ oc new-build --name=drools-helloworld-service --source-image=drools-helloworld-builder \
drools-helloworld-service => rules-quarkus-helloworld-service
drools-helloworld-builder => rules-quarkus-helloworld-builder

2020-04-10 13:52 UTC, radtriste commented on README.md
> +Once the build gets finished, we need to create an application and use our service image created with the latested command.
Once the build gets finished, you need to create an application and use the service image created with the latest command.

2020-04-10 13:52 UTC, radtriste commented on README.md
> +$ oc new-app drools-helloworld-service:latest
drools-helloworld-service => rules-quarkus-helloworld-service

2020-04-10 13:52 UTC, radtriste commented on README.md
> +As described in the command output, to be able to access the application, we need to expose it to the external world,
[...] we need to expose it to the external world. For that, just execute the command listed [...]

2020-04-10 13:52 UTC, radtriste commented on README.md
> +drools-helloworld-service   drools-helloworld-service-rules-quarkus-helloworld.apps.spolti.cloud             drools-helloworld-service   8080-tcp                 None
update the log with rules-quarkus-helloworld

2020-04-10 13:52 UTC, radtriste commented on README.md
> +     http://drools-helloworld-service-rules-quarkus-helloworld.apps.spolti.cloud/hello
same here, update the log

2020-04-10 13:52 UTC, radtriste commented on README.md
> +To be able to build the image a docker should be installed and available on OpenShift before it can be used.
To be able to build the image, docker should be installed [...]

2020-04-10 15:35 UTC, spolti commented on README.md
> +* [Kogito Images](#kogito-container-images) - ok
oops, left over hehe

2020-04-10 15:45 UTC, spolti commented on README.md
> + * OpenJDK 11.0.6
there is also the common JDK on the builder image.
maybe to make clear that there is the GraalVM with java 11 and openjdk, 

Or just use java 11 on graavl vm?

2020-04-10 15:56 UTC, spolti commented on README.md
> +$ docker run -it -p 8080:8080 drools-example:latest
did this before the kogito examples renaming, left over hehe

2020-04-10 16:04 UTC, spolti commented on README.md
> +### Improving Build Time
correct.

2020-04-10 16:09 UTC, spolti commented on kogito-management-console-overrides.yaml
> +  - name: "KOGITO_DATAINDEX_HTTP_URL"
this is the current env name support on the management console image.
why change to management console?

2020-04-10 18:38 UTC, spolti commented on README.md
> +[KJAR](https://developers.redhat.com/blog/2018/03/14/what-is-a-kjar/) stands for Knowledge jar which is a custom JAR file that contains Business Process or Rules and all needed
I think KJAR is correct, will update other occurences to upper case.

2020-04-10 18:42 UTC, spolti commented on README.md
> +- [Kogito Quarkus archetype](https://github.com/kiegroup/kogito-runtimes/tree/master/archetypes/kogito-quarkus-archetype)
Ar... is better

2020-04-10 18:42 UTC, spolti commented on README.md
> +Note that, when building Quarkus based application that's **not** a *UberJAR* we also need to copy the **target/lib**
maybe keep targe is better to specify where the lib directory can be found?

2020-04-10 18:52 UTC, spolti commented on README.md
> +$ s2i build target/ quay.io/kiegroup/kogito-quarkus-jvm-ubi8:latest process-quarkus-example
there's no need, the runtime image will remove everything that's not needed.
but yeah, we might should move the uberjar to another directory and copy the jar from there.

2020-04-10 19:08 UTC, spolti commented on README.md
> +$ s2i build target/ quay.io/kiegroup/kogito-quarkus-jvm-ubi8:latest process-quarkus-example
looks like s2i command allows you to specify a single file to build.

2020-04-10 19:21 UTC, spolti commented on README.md
> +TODO: add the envs inherited from another modules
letfover.

2020-04-10 19:30 UTC, spolti commented on README.md
> +API.
Thanks, I updated the wiki link, but for jobs services it still pointing to the wiki as I didn't find it on the docs you mentioned.

2020-04-10 19:32 UTC, spolti commented on README.md
> +might not work properly.
Is the suggeted change above enough?

2020-04-10 19:34 UTC, spolti commented on README.md
> +```
I think we already discussed in on the gchat, yes?

2020-04-10 19:37 UTC, spolti commented on README.md
> +- Build all images with only one command
actually it only builds, will fix the makefile on another jira.

2020-04-10 19:45 UTC, spolti commented on README.md
> +- [kogito-data-index](modules/kogito-data-index): Installs and Configure the data-index jar inside the image.
That's make sense, but I was thinking a little bit different, each module would have its own README documenting it and here we would refer the readme files. but I was planning to do it later.

Are you ok keeping it this way until we do what I suggested above?

2020-04-10 19:46 UTC, spolti commented on README.md
> +There is two kind of tests that we could run locally and also it is ran by CI, **behave** and **bats** tests.
+1

2020-04-14 08:50 UTC, sutaakar commented on README.md
> +        * used to perform local s2i images uisng some of the [builder images](#builder-images)
```suggestion
        * used to perform local s2i images using some of the [builder images](#builder-images)
```

2020-04-14 09:05 UTC, sutaakar commented on README.md
> +- Assets nly
```suggestion
- Assets only
```

2020-04-14 09:06 UTC, sutaakar commented on README.md
> +dependencies and or files to execute it on the target runtime, either Quarkus or Spring Boot.
```suggestion
dependencies and files to execute it on the target runtime, either Quarkus or Spring Boot.
```

2020-04-14 09:20 UTC, sutaakar commented on README.md
> +All images already have the feature files, if a new image are being created a new feature file will need to be created
```suggestion
All images already have the feature files, if a new image is being created a new feature file will need to be created
```

2020-04-14 09:24 UTC, sutaakar approved these changes
Minor typos, otherwise looks good to me.

2020-04-14 13:31 UTC, cristianonicolai approved these changes

2020-04-14 17:20 UTC, radtriste commented on kogito-management-console-overrides.yaml
> +  - name: "KOGITO_DATAINDEX_HTTP_URL"
right. my mistake here ... sry

2020-04-14 17:20 UTC, radtriste commented on README.md
> + * OpenJDK 11.0.6
maybe it is clearer like that

2020-04-14 18:30 UTC, spolti commented on kogito-management-console-overrides.yaml
> +  - name: "KOGITO_DATAINDEX_HTTP_URL"
we cant use podman for images yet =/
cekit and s2i does not play smoothly with podman yet.

2020-04-14 18:35 UTC, spolti commented on README.md
> + * OpenJDK 11.0.6
changed to:  GraalVM 19.3.1-java11

2020-04-14 18:38 UTC, spolti commented on README.md
> +Note that, when building Quarkus based application that's **not** a *UberJAR* we also need to copy the **target/lib**
changed to ```
Note that, when building Quarkus based application that's **not** a *UberJAR* we also need to copy the **lib** directory
located inside the *target* directory. ```

let me know if it looks ok

2020-04-14 18:42 UTC, spolti commented on README.md
> +## Using Kogito Images to Deploy Apps on OpenShift
moved.

2020-04-14 18:43 UTC, spolti commented
@radtriste thanks for the detailed review.
I think I addressed all your suggestions, if not please let me know.

2020-04-15 06:51 UTC, Sgitario approved these changes

2020-04-15 10:56 UTC, radtriste requested changes
went a bit deeper. See my propositions of changes

2020-04-15 10:56 UTC, radtriste commented on README.md
> +- [kogito-data-index](modules/kogito-data-index): Installs and Configure the data-index jar inside the image.
ok

2020-04-15 10:56 UTC, radtriste commented on README.md
> +The Kogito Builder Images are responsible for building the project with Apache Maven and generate the binary that will be used by the Runtime images to run the Kogito application.
```suggestion
The Kogito Builder Images are responsible for building the project with Apache Maven and generate the binary that will be used by the Kogito Runtime images to run the Kogito application.
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +* [quay.io/kiegroup/kogito-quarkus-ubi8-s2i](kogito-quarkus-s2i-overrides.yaml)
I would put the link to the quay.io website here.
The link to specific yaml files should be done into the contributing part IMO

2020-04-15 10:56 UTC, radtriste commented on README.md
> +lightweight and fast applications ready to run on Cloud.
```suggestion
lightweight and fast applications ready to run in the Cloud.
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +This image contains a helper option to better understand how to use this image:
```suggestion
This image contains a helper option to better understand how to use it:
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +build environment variable to **false**. See the next topic for an example.
```suggestion
build environment variable to **false**.

See the next topic for an example.
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +**modules/install** section.
```suggestion
**modules.install** section. 
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +This image contains a helper option to better understand how to use this image:
```suggestion
This image contains a helper option to better understand how to use it:
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +Let's use here the *rules-quarkus-helloworld* example, with native compilation disabled.
```suggestion
the *rules-quarkus-helloworld* example, with native compilation disabled.
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +Let's use here the *rules-quarkus-helloworld* example, with native compilation disabled.
```suggestion
In this example, let's use a simple application available in the [Kogito Examples](https://github.com/kiegroup/kogito-examples) repository: the *rules-quarkus-helloworld* example, with native compilation disabled.
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +Let's use the *process-springboot-example*.
```suggestion
In this example, let's use a simple application available in the [Kogito Examples](https://github.com/kiegroup/kogito-examples) repository: the *process-springboot-example*.
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +Let's start 2 builds with the incremental option enabled and compare the time spent to build each one:
```suggestion
If you are planning to build many times the same application, you can use the incremental builds which will improve drastically the build time.  
Let's start 2 builds with the incremental option enabled and compare the time spent to build each one:
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +This can significantly improve the build time.
```suggestion
In the second try, you can see the artifacts getting unpacked and reused from the previous build.  
Now, pay also attention to the time spent to build it. There is a big difference.  
In fact, an incremental build reuses the previously built image and it takes advantage of already downloaded artifacts.  
This can significantly improve the build time.
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +To turn it possible we just need to set the **MAVEN_MIRROR_URL** environment variable when starting a new build, see the example below:
```suggestion
Another option is to use a Maven Mirror.  
This can be used together with incremental builds to speed up the build even more.  
To turn it possible we just need to set the **MAVEN_MIRROR_URL** environment variable when starting a new build, see the example below:
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +or run Kogito applications: Runtime image and Builder image. Those are described bellow.
```suggestion
or run Kogito applications: Runtime image and Builder image.  
Those are described bellow.
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +The time needed to build the application is rather long. This is mainly due to maven downloading all dependencies, which takes several minutes.
```suggestion
The time needed to build the application is rather long: this is mainly due to maven downloading all dependencies, which takes several minutes.
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +If the maven mirror already have all the dependencies there, the build time can be even faster.
```suggestion
Here you can see that the build time has again been reduced.  
If the maven mirror have already all the dependencies there, the build time can be even faster.
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +For non-native built applications, they have a JRE installed to allow to execute Java applications.
```suggestion
* Run your pre-built local artifacts, via what we call a _Binary Build_.  
For non-native built applications, they have a JRE installed to allow to execute Java applications.
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +* [quay.io/kiegroup/kogito-quarkus-jvm-ubi8](kogito-quarkus-jvm-overrides.yaml)
same here about links to quay.io instead of yaml files (do that in contributing part)

2020-04-15 10:56 UTC, radtriste commented on README.md
> +Both methods will be described in the next topic.
```suggestion
Both methods are described below.
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +to generate project structure, the available archetypes are:
```suggestion
to generate project structure.  
The available archetypes are:
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +located inside the *target* directory. Examples on how to use this feature can be found in the next topics.
```suggestion
Note that, when building Quarkus based application that is **not** a *UberJAR* we also need to copy the **lib** directory located inside the *target* directory.  
Examples on how to use this feature can be found in the next topics.
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +This is a lightweight and it contains basically only the JRE. This Kogito Runtime Image contains only the needed files to execute a pre built Kogito application.
```suggestion
This Kogito Runtime Image contains only the needed files to execute a pre built Kogito application and a JRE.
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +This image contains a helper option to better understand how to use this image:
```suggestion
This image contains a helper option to better understand how to use it:
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +To configure Quarkus to generate a UberJAR please follow the instructions described [here](https://quarkus.io/guides/maven-tooling#configuration-reference)
```suggestion
In the next few lines let's take a look on how this image can be used to receive an already built UberJAR.  
To configure Quarkus to generate a UberJAR please follow the instructions described [here](https://quarkus.io/guides/maven-tooling#configuration-reference)
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +For this example lets use the [process-quarkus-example](https://github.com/kiegroup/kogito-examples/tree/stable/process-quarkus-example).
```suggestion
For this example, let's use the [process-quarkus-example](https://github.com/kiegroup/kogito-examples/tree/stable/process-quarkus-example).
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +Once you have checked the example on your local machine follow the steps below:
```suggestion
Once you have checked out the example on your local machine follow the steps below:
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +$ s2i build target/ quay.io/kiegroup/kogito-quarkus-jvm-ubi8:latest process-quarkus-example
```suggestion
$ s2i build target/jbpm-quarkus-example-8.0.0-SNAPSHOT-runner.jar quay.io/kiegroup/kogito-quarkus-jvm-ubi8:latest process-quarkus-example
```

Is that possible ?

2020-04-15 10:56 UTC, radtriste commented on README.md
> +Note that this time there is a *lib* on the **target** directory, the s2i build will take care of copying it to the correct place, just
```suggestion
Note that this time there is a *lib* folder into the **target** directory. The s2i build will take care of copying it to the correct place. Just
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +This is a lightweight and compact application container image.
```suggestion

```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +This image contains a helper option to better understand how to use this image:
```suggestion
This image contains a helper option to better understand how to use it:
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +For this example let's use the same than the previous one (process-quarkus-example). But this time, let's perform a native build:
```suggestion
For this example let's use the same than the previous one (process-quarkus-example).  
But this time, let's perform a native build:
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +$ mvn clean package
```suggestion
**Example with non UberJAR**
For non uberjar the process is the same, but you only need to remove the property from Quarkus configuration to not generate uberjar.
```bash
$ mvn clean package
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +So this one will only get the binaries and place into the container.
```suggestion
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +So this one will only get the binaries and place into the container.
Is this useful ?

2020-04-15 10:56 UTC, radtriste commented on README.md
> +On top of the OS it has JRE installed (OpenJDK 11) to be able to execute fat jar.
```suggestion
This Kogito Runtime Image has a JRE installed (OpenJDK 11) to be able to execute fat jar.
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +This image contains a helper option to better understand how to use this image:
```suggestion
This image contains a helper option to better understand how to use it:
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +For this example let's use the *process-springboot-example*:
```suggestion
Let's try, here, the *process-springboot-example*: 
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +Let's use this uberjar to perform the build:
```suggestion
A uberjar file has been generated into the **target directory**.  
Let's use this uberjar to perform the build:
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +* [quay.io/kiegroup/kogito-data-index](kogito-data-index-overrides.yaml)
same here about links

2020-04-15 10:56 UTC, radtriste commented on README.md
> +The Data Index Service depends on a running Infinispan Server.
```suggestion
The Data Index Service aims at capturing and indexing data produced by one more Kogito runtime services.
For more information please visit this (link)(https://docs.jboss.org/kogito/release/latest/html_single/#proc_kogito-travel-agency-enable-data-index).  
The Data Index Service depends on a running Infinispan Server.
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +The [Kogito Operator](https://github.com/kiegroup/kogito-cloud-operator) can be used to deploy the Kogito Data Index Service
move that part to the end of this section

2020-04-15 10:56 UTC, radtriste commented on README.md
> +The Kogito Jobs Service is a dedicated lightweight service responsible for scheduling jobs that aim to be fired at a given time.
```suggestion
The Kogito Jobs Service is a dedicated lightweight service responsible for scheduling jobs that aim at firing at a given time.  
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +on the job request, or any other callback that could be supported by the service.
```suggestion
on the job request, or any other callback that could be supported by the service.  
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +The [Kogito Operator](https://github.com/kiegroup/kogito-cloud-operator) can be used to deploy the Kogito Jobs Service
move that part to the end of this section

2020-04-15 10:56 UTC, radtriste commented on README.md
> +The [Kogito Operator](https://github.com/kiegroup/kogito-cloud-operator) can be used to deploy the Kogito Management Console
move that part to the end of this section

2020-04-15 10:56 UTC, radtriste commented on README.md
> +rights you can deploy it on the **openshift** namespace, otherwise, deploy it into the namespace where you have permissions.
```suggestion
rights you can deploy it into the **openshift** namespace, otherwise, deploy it into the namespace where you have permissions.
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +Then we need to tag the image properly, suppose your local registry is openshift.local.registry:8443, you should do:
```suggestion
Then we need to tag the image properly.  
Suppose your local registry is openshift.local.registry:8443, you should do:
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +Once the image is properly tagged, log in on the registry and push the new image:
```suggestion
Where the namespace is the place where you want the image to be available for usage.  
Once the image is properly tagged, log in to the registry and push the new image:
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +Before proceed please make sure you have met the [requirements](#kogito-images-requirements).
```suggestion
Before proceed please make sure you have checked the [requirements](#kogito-images-requirements).
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +      $ make push
```suggestion
- Build and Push the Images to quay or a repo for you preference, for this you need to edit the Makefile accordingly:  
      ```bash
      $ make push
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +      ```bash
```suggestion
- Push staging images (release candidates, a.k.a rcX tags), the following command will build and push RC images to quay.  
      ```bash
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +On the Kogito Images we have several CeKit modules that are used during builds. To better understanding
```suggestion
On the Kogito Images we have several CeKit modules that are used during builds.
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +CeKit can use modules to better separate concerns and reuse these modules on different images.
```suggestion
CeKit can use modules to better separate concerns and reuse these modules on different images.  
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +- [kogito-data-index-overrides.yaml](kogito-data-index-overrides.yaml)
here I would reference the corresponding image

2020-04-15 10:56 UTC, radtriste commented on README.md
> +The **Then** clause is used to do your validations, test something, looking for a keyword in the logs, etc.
```suggestion
The **Then** clause is used to do your validations, test something, looking for a keyword in the logs, etc.  
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +specific test or feature to run, a example can be found on [this common test](tests/features/common.feature)
```suggestion
CeKit allow us to use tags, it is very useful to segregate tests, if we want to run only the tests for the 
given image, we need to annotate the test specific or the entire feature with the image name, for example, 
we have the common tests that needs to run against almost all images, instead to add the same tests for every 
image feature, we create a common feature and annotate it with the images we want that
specific test or feature to run, a example can be found on [this common test](tests/features/common.feature)

For example, suppose you are working on a new feature and add tests to cover your changes. You don't want to run all existing tests, this can be easily done by adding the **@wip** tag on the behave test that you are creating.
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +and the very first line of this file would need to contain a tag with the image name.
```suggestion
All images have already test feature files. If a new image is being created, a new feature file will need to be created
and the very first line of this file would need to contain a tag with the image name.
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +Example, if we are creating a new image called quay.io/kiegroup/kogito-moon-service, we would have a feature called
```suggestion
For example, if we are creating a new image called quay.io/kiegroup/kogito-moon-service, we would have a feature called
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +For a complete list of all available sentences please refer the cekit source code:
```suggestion
For a complete list of all available sentences, please refer the cekit source code:
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +Under the hood, each test case is just a function with a description.
```suggestion
What is Bats tests ? 
From google: Bats is a TAP-compliant testing framework for Bash.
It provides a simple way to verify that the UNIX programs you write behave as expected.  
A Bats test file is a Bash script with special syntax for defining test cases.  
Under the hood, each test case is just a function with a description.
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +To run the bats tests, we need to specify which module and test we want to run, to exemplify this let's execute the tests
```suggestion
To run the bats tests, we need to specify which module and test we want to run.  
As an example, let's execute the tests
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +called **Image** that should be added in this case.
```suggestion
For the Kogito Images, we use the [Jira issue tracker](https://issues.redhat.com/projects/KOGITO) under the 
**KOGITO** project.  
And to specify that the issue is specific to the Kogito images, there is a component called **Image** that should be added for any issue related to this repository.
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +When submitting the Pull Request with the fix for the reported issue, for a better readability we use the following pattern:
```suggestion
When submitting the Pull Request with the fix for the reported issue, and for a better readability, we use the following pattern:
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +Create the Pull Request with the following pattern:
```suggestion

```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +[KOGITO-XXXX] - Description of the Issue
```suggestion
- Pull Requests targeting only master branch:  
```text
[KOGITO-XXXX] - Description of the Issue
```

2020-04-15 10:56 UTC, radtriste commented on README.md
> +[0.9.x][KOGITO-XXXX] - Description of the Issue
```suggestion
- But if the Pull Request also needs to be part of a different branch/version and is cherry picked from master:  
```text
Master PR:
[master][KOGITO-XXXX] - Description of the Issue
[0.9.x][KOGITO-XXXX] - Description of the Issue
```

2020-04-15 14:26 UTC, spolti commented on README.md
> +* [quay.io/kiegroup/kogito-quarkus-ubi8-s2i](kogito-quarkus-s2i-overrides.yaml)
make sense.

2020-04-15 14:56 UTC, spolti commented on README.md
> +Let's use here the *rules-quarkus-helloworld* example, with native compilation disabled.
If remove the "let's use" with only "the" it looses context,no?

2020-04-15 14:56 UTC, spolti commented on README.md
> +Let's use here the *rules-quarkus-helloworld* example, with native compilation disabled.
ah right, understand on next comment

2020-04-15 14:58 UTC, spolti commented on README.md
> +The time needed to build the application is rather long. This is mainly due to maven downloading all dependencies, which takes several minutes.
don't understand why use ":" here

2020-04-15 15:06 UTC, spolti commented on README.md
> +$ s2i build target/ quay.io/kiegroup/kogito-quarkus-jvm-ubi8:latest process-quarkus-example
unfortunately no.

2020-04-15 15:09 UTC, spolti commented on README.md
> +So this one will only get the binaries and place into the container.
not really.

2020-04-15 15:09 UTC, spolti commented on README.md
> +On top of the OS it has JRE installed (OpenJDK 11) to be able to execute fat jar.
change to the same sentence than the quarkus-jvm one.

2020-04-15 15:18 UTC, spolti commented on README.md
> +- [kogito-data-index-overrides.yaml](kogito-data-index-overrides.yaml)
In this case keep the yaml file is better since this topic is referring to the files so use/reader can check for more information about modules being installed.

2020-04-15 16:34 UTC, radtriste approved these changes
2 minor comments. otherwise good to go

2020-04-15 16:34 UTC, radtriste commented on README.md
> +- [kogito-data-index-overrides.yaml](kogito-data-index-overrides.yaml)
it is just to have the mapping image <-> yaml file

2020-04-15 16:34 UTC, radtriste commented on README.md
> +The time needed to build the application is rather long. This is mainly due to maven downloading all dependencies, which takes several minutes.
yeah you can skip that one

2020-04-15 17:42 UTC, spolti commented on README.md
> +- [kogito-data-index-overrides.yaml](kogito-data-index-overrides.yaml)
right.

2020-04-15 17:51 UTC, radtriste approved these changes
lgtm

2020-04-15 17:54 UTC, spolti commented
o.9.x pr created, please take a look as well: https://github.com/kiegroup/kogito-images/pull/140

2020-04-16 14:09 UTC, merged