Build `kogito-swf-builder` quarkus app locally
apache/incubator-kie-kogito-images pull request #1364
Opened 2022-11-08 11:53 UTC by radtriste

@desmax74 @spolti I changed the way the kogito-swf-builder is built
The scaffold project is no more built during the cekit build but before and we copy project and maven repo to the image
This is done so that we can use specific Maven configuration on the scaffold project creation and build, based on node env variables. We cannot do that if the build happens on Cekit

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [ ] Pull Request title is properly formatted: `[KOGITO|RHPAM-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

2022-11-08 11:56 UTC, kie-ci1 commented
**PR job** `#347` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/347/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] error<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Prepare for tests)<br/>Stage "Prepare for tests" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build & Test Images)<br/>Stage "Build & Test Images" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-images/workspaces<br/>[Pipeline] sh<br/>++ docker ps -a -q<br/>+ docker rm -f 11ff6055f7af<br/>11ff6055f7af<br/>[Pipeline] sh<br/>++ docker images -q<br/>+ docker rmi -f 8da03e408fae<br/>Untagged: sonatype/nexus3:latest<br/>Untagged: sonatype/nexus3@sha256:c60752862ab18e347ae686185ffc22fbf05dbc812b0f33cd1a5d4edef7db4382<br/>Deleted: sha256:8da03e408fae2d6a4cf8ba282111a62a9f43a7d88caf5d9f22f6a80784a36f07<br/>Deleted: sha256:5c66fef0e785f26ec141397cc72102d0657ad340c60e82b944a96ff78e4701b2<br/>Deleted: sha256:82edb1ed6dd42bb8ff2dbeb891fa516a310b02137a98b47daf2e85445d672559<br/>Deleted: sha256:2d9e805cacc4f3c2936eae944ba48da98517c6ebef1ae8bab8bd3633b043d3ca<br/>Deleted: sha256:17770559fbe0d327fe1097c84c09bbb296e260d9c755627c7cb4ba2320e27841<br/>Deleted: sha256:48a911dfbe541056e35f0d3fcf98e41c67a9a9bc6159bf3395bb9700b99c6bf1<br/>Deleted: sha256:6f0dfdbc9720aee9f230eed5e567252036844677bde6abd61cceb7ca0408e84a<br/>Deleted: sha256:9aaca8eae7c07b489cefc9ae800e862332cecf50af417a840007a93709943673<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/.cekit/cache<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/347/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

2022-11-08 12:11 UTC, kie-ci1 commented
**PR job** `#348` was: **ABORTED**
Possible explanation: Most probably a timeout, please review

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/348/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Prepare for tests)<br/>Stage "Prepare for tests" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build & Test Images)<br/>Stage "Build & Test Images" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-images/workspaces<br/>[Pipeline] sh<br/>++ docker ps -a -q<br/>+ docker rm -f 9cd5471d7530<br/>9cd5471d7530<br/>[Pipeline] sh<br/>++ docker images -q<br/>+ docker rmi -f 8da03e408fae<br/>Untagged: sonatype/nexus3:latest<br/>Untagged: sonatype/nexus3@sha256:c60752862ab18e347ae686185ffc22fbf05dbc812b0f33cd1a5d4edef7db4382<br/>Deleted: sha256:8da03e408fae2d6a4cf8ba282111a62a9f43a7d88caf5d9f22f6a80784a36f07<br/>Deleted: sha256:5c66fef0e785f26ec141397cc72102d0657ad340c60e82b944a96ff78e4701b2<br/>Deleted: sha256:82edb1ed6dd42bb8ff2dbeb891fa516a310b02137a98b47daf2e85445d672559<br/>Deleted: sha256:2d9e805cacc4f3c2936eae944ba48da98517c6ebef1ae8bab8bd3633b043d3ca<br/>Deleted: sha256:17770559fbe0d327fe1097c84c09bbb296e260d9c755627c7cb4ba2320e27841<br/>Deleted: sha256:48a911dfbe541056e35f0d3fcf98e41c67a9a9bc6159bf3395bb9700b99c6bf1<br/>Deleted: sha256:6f0dfdbc9720aee9f230eed5e567252036844677bde6abd61cceb7ca0408e84a<br/>Deleted: sha256:9aaca8eae7c07b489cefc9ae800e862332cecf50af417a840007a93709943673<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/.cekit/cache<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/348/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

2022-11-08 12:51 UTC, kie-ci1 commented
**PR job** `#349` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/349/display/redirect

**Test results:**
- PASSED: 243
- FAILED: 6

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/349/testReport/features.image.kogito-swf-builder/SWF and Quarkus installation/Verify_if_a_build_run_correctly/">features.image.kogito-swf-builder.SWF and Quarkus installation.Verify if a build run correctly</a></summary>
File /home/kogito/serverless-workflow-project/target/quarkus-app/quarkus-run.jar does not exist
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/349/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Verify_if_the_s2i_build_is_finished_as_expected_using_native_build_and_runtime_image/">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Verify if the s2i build is finished as expected using native build and runtime image</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/349/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Verify_if_the_s2i_build_is_finished_as_expected_using_native_build_and_no_runtime_image/">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Verify if the s2i build is finished as expected using native build and no runtime image</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/349/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Verify_if_the_s2i_build_is_finished_as_expected_performing_a_native_build_and_if_it_is_listening_on_the_expected_port,_test_uses_custom_properties_file_to_test_the_port_configuration./">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Verify if the s2i build is finished as expected performing a native build and if it is listening on the expected port, test uses custom properties file to test the port configuration.</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/349/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Verify_if_the_s2i_build_is_finished_as_expected_performing_a_native_build_with_persistence_enabled___Step_1:_build_the_application_and_copy_to_the_runtime_image/">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Verify if the s2i build is finished as expected performing a native build with persistence enabled - Step 1: build the application and copy to the runtime image</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/349/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Perform_a_second_incremental_s2i_build_for_native_scenario,_this_time,_with_native_enabled/">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Perform a second incremental s2i build for native scenario, this time, with native enabled</a></summary>
S2I build failed, check logs!
</details>

2022-11-08 14:14 UTC, kie-ci1 commented
**PR job** `#350` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/350/display/redirect

**Test results:**
- PASSED: 244
- FAILED: 5

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/350/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Verify_if_the_s2i_build_is_finished_as_expected_using_native_build_and_runtime_image/">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Verify if the s2i build is finished as expected using native build and runtime image</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/350/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Verify_if_the_s2i_build_is_finished_as_expected_using_native_build_and_no_runtime_image/">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Verify if the s2i build is finished as expected using native build and no runtime image</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/350/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Verify_if_the_s2i_build_is_finished_as_expected_performing_a_native_build_and_if_it_is_listening_on_the_expected_port,_test_uses_custom_properties_file_to_test_the_port_configuration./">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Verify if the s2i build is finished as expected performing a native build and if it is listening on the expected port, test uses custom properties file to test the port configuration.</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/350/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Verify_if_the_s2i_build_is_finished_as_expected_performing_a_native_build_with_persistence_enabled___Step_1:_build_the_application_and_copy_to_the_runtime_image/">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Verify if the s2i build is finished as expected performing a native build with persistence enabled - Step 1: build the application and copy to the runtime image</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/350/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Perform_a_second_incremental_s2i_build_for_native_scenario,_this_time,_with_native_enabled/">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Perform a second incremental s2i build for native scenario, this time, with native enabled</a></summary>
S2I build failed, check logs!
</details>

2022-11-08 14:55 UTC, kie-ci1 commented
**PR job** `#351` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/351/display/redirect

**Test results:**
- PASSED: 244
- FAILED: 5

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/351/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Verify_if_the_s2i_build_is_finished_as_expected_using_native_build_and_runtime_image/">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Verify if the s2i build is finished as expected using native build and runtime image</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/351/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Verify_if_the_s2i_build_is_finished_as_expected_using_native_build_and_no_runtime_image/">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Verify if the s2i build is finished as expected using native build and no runtime image</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/351/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Verify_if_the_s2i_build_is_finished_as_expected_performing_a_native_build_and_if_it_is_listening_on_the_expected_port,_test_uses_custom_properties_file_to_test_the_port_configuration./">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Verify if the s2i build is finished as expected performing a native build and if it is listening on the expected port, test uses custom properties file to test the port configuration.</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/351/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Verify_if_the_s2i_build_is_finished_as_expected_performing_a_native_build_with_persistence_enabled___Step_1:_build_the_application_and_copy_to_the_runtime_image/">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Verify if the s2i build is finished as expected performing a native build with persistence enabled - Step 1: build the application and copy to the runtime image</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/351/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Perform_a_second_incremental_s2i_build_for_native_scenario,_this_time,_with_native_enabled/">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Perform a second incremental s2i build for native scenario, this time, with native enabled</a></summary>
S2I build failed, check logs!
</details>

2022-11-08 16:38 UTC, spolti commented
Similar way we are doing with the component apps, that's fine though.
we need to add it in the makefile as well.

2022-11-09 07:55 UTC, radtriste commented
> Similar way we are doing with the component apps, that's fine though. we need to add it in the makefile as well.

What do you want to add more into the Makefile ?
The `build-quarkus-app.sh` is already in

2022-11-09 15:22 UTC, radtriste commented
jenkins retest this

2022-11-09 16:08 UTC, kie-ci1 commented
**PR job** `#354` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/354/display/redirect

**Test results:**
- PASSED: 244
- FAILED: 5

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/354/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Verify_if_the_s2i_build_is_finished_as_expected_using_native_build_and_runtime_image/">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Verify if the s2i build is finished as expected using native build and runtime image</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/354/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Verify_if_the_s2i_build_is_finished_as_expected_using_native_build_and_no_runtime_image/">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Verify if the s2i build is finished as expected using native build and no runtime image</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/354/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Verify_if_the_s2i_build_is_finished_as_expected_performing_a_native_build_and_if_it_is_listening_on_the_expected_port,_test_uses_custom_properties_file_to_test_the_port_configuration./">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Verify if the s2i build is finished as expected performing a native build and if it is listening on the expected port, test uses custom properties file to test the port configuration.</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/354/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Verify_if_the_s2i_build_is_finished_as_expected_performing_a_native_build_with_persistence_enabled___Step_1:_build_the_application_and_copy_to_the_runtime_image/">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Verify if the s2i build is finished as expected performing a native build with persistence enabled - Step 1: build the application and copy to the runtime image</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/354/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Perform_a_second_incremental_s2i_build_for_native_scenario,_this_time,_with_native_enabled/">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Perform a second incremental s2i build for native scenario, this time, with native enabled</a></summary>
S2I build failed, check logs!
</details>

2022-11-10 10:30 UTC, radtriste commented
jenkins retest this

2022-11-10 11:20 UTC, kie-ci1 commented
**PR job** `#356` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/356/display/redirect

**Test results:**
- PASSED: 244
- FAILED: 5

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/356/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Verify_if_the_s2i_build_is_finished_as_expected_using_native_build_and_runtime_image/">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Verify if the s2i build is finished as expected using native build and runtime image</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/356/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Verify_if_the_s2i_build_is_finished_as_expected_using_native_build_and_no_runtime_image/">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Verify if the s2i build is finished as expected using native build and no runtime image</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/356/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Verify_if_the_s2i_build_is_finished_as_expected_performing_a_native_build_and_if_it_is_listening_on_the_expected_port,_test_uses_custom_properties_file_to_test_the_port_configuration./">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Verify if the s2i build is finished as expected performing a native build and if it is listening on the expected port, test uses custom properties file to test the port configuration.</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/356/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Verify_if_the_s2i_build_is_finished_as_expected_performing_a_native_build_with_persistence_enabled___Step_1:_build_the_application_and_copy_to_the_runtime_image/">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Verify if the s2i build is finished as expected performing a native build with persistence enabled - Step 1: build the application and copy to the runtime image</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/356/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Perform_a_second_incremental_s2i_build_for_native_scenario,_this_time,_with_native_enabled/">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Perform a second incremental s2i build for native scenario, this time, with native enabled</a></summary>
S2I build failed, check logs!
</details>

2022-11-14 10:20 UTC, radtriste commented
jenkins retest this

2022-11-14 10:22 UTC, kie-ci1 commented
**PR job** `#358` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/358/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Prepare for tests)<br/>Stage "Prepare for tests" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build & Test Images)<br/>Stage "Build & Test Images" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-images/workspaces<br/>[Pipeline] sh<br/>++ docker ps -a -q<br/>+ docker rm -f<br/>"docker rm" requires at least 1 argument.<br/>See 'docker rm --help'.<br/><br/>Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]<br/><br/>Remove one or more containers<br/>+ date<br/>Mon Nov 14 05:22:28 EST 2022<br/>[Pipeline] sh<br/>++ docker images -q<br/>+ docker rmi -f<br/>"docker rmi" requires at least 1 argument.<br/>See 'docker rmi --help'.<br/><br/>Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]<br/><br/>Remove one or more images<br/>+ date<br/>Mon Nov 14 05:22:29 EST 2022<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/.cekit/cache<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/358/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

2022-11-14 13:00 UTC, kie-ci1 commented
**PR job** `#359` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/359/display/redirect

**Test results:**
- PASSED: 244
- FAILED: 5

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/359/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Verify_if_the_s2i_build_is_finished_as_expected_using_native_build_and_runtime_image/">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Verify if the s2i build is finished as expected using native build and runtime image</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/359/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Verify_if_the_s2i_build_is_finished_as_expected_using_native_build_and_no_runtime_image/">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Verify if the s2i build is finished as expected using native build and no runtime image</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/359/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Verify_if_the_s2i_build_is_finished_as_expected_performing_a_native_build_and_if_it_is_listening_on_the_expected_port,_test_uses_custom_properties_file_to_test_the_port_configuration./">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Verify if the s2i build is finished as expected performing a native build and if it is listening on the expected port, test uses custom properties file to test the port configuration.</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/359/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Verify_if_the_s2i_build_is_finished_as_expected_performing_a_native_build_with_persistence_enabled___Step_1:_build_the_application_and_copy_to_the_runtime_image/">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Verify if the s2i build is finished as expected performing a native build with persistence enabled - Step 1: build the application and copy to the runtime image</a></summary>
S2I build failed, check logs!
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/359/testReport/features.image.kogito-s2i-builder-native/kogito-s2i-builder image native build tests/Perform_a_second_incremental_s2i_build_for_native_scenario,_this_time,_with_native_enabled/">features.image.kogito-s2i-builder-native.kogito-s2i-builder image native build tests.Perform a second incremental s2i build for native scenario, this time, with native enabled</a></summary>
S2I build failed, check logs!
</details>

2022-11-14 15:16 UTC, desmax74 approved these changes

2022-11-14 18:38 UTC, spolti requested changes

2022-11-14 18:38 UTC, spolti commented on modules/kogito-s2i-core/module.yaml
> -  - name: QUARKUS_VERSION
can't we keep it as it still configurable in the kogito-builder image?

2022-11-14 18:38 UTC, spolti commented on image.yaml
> +  - name: "QUARKUS_VERSION"
Why did you move it to the main img.yaml?
Isn't this property to be used only by the builder images?

2022-11-14 18:38 UTC, spolti commented on image.yaml
> +    description: Please do not change
```suggestion
    description: Defines the Kogito version to be used by the builder images. Not intended to be changed by end user.
```

2022-11-14 18:38 UTC, spolti commented on modules/kogito-swf-builder/added/add-extension.sh
>      set -x
maybe add the maven debug flag here as well and append it in the maven command below.

2022-11-14 18:38 UTC, spolti commented on modules/kogito-swf-builder/configure.sh
> +ls -al "${KOGITO_HOME}/.m2/repository"
do we need this ls here?

2022-11-14 19:55 UTC, desmax74 commented on modules/kogito-swf-builder/module.yaml
> +  - path: /tmp/build/kogito-swf-builder/kogito-swf-builder-maven-repo.zip
Do you want to prepare a maven repo ? Which advantage over download the deps during the build ?

2022-11-14 19:59 UTC, desmax74 commented on scripts/build-quarkus-app.sh
> +echo "Zip and copy maven repo"
Which is the advantage to zip and move the repo instead of leave in the final place during the build ? If the maven repo grows the unzip take time

2022-11-15 13:20 UTC, radtriste commented
@desmax74 The idea is to follow what is done by other build as well, aka build outside of the image and copy the resources for the image to be ready.
One advantage is the Maven configuration that we can use when we build outside of the image, configuration that we cannot set when cekit build the image ... And we should use the maven mirror instead of maven central when building a maven app ...
That is why the script:

- Build the quarkus-app locally
- Copy the scaffold project on cekit build
- Copy the maven repo on cekit build

2022-11-15 13:36 UTC, radtriste commented on modules/kogito-swf-builder/configure.sh
> +ls -al "${KOGITO_HOME}/.m2/repository"
we do need the maven repository into the image so that the build is fast

2022-11-15 13:36 UTC, radtriste commented on modules/kogito-swf-builder/module.yaml
> +  - path: /tmp/build/kogito-swf-builder/kogito-swf-builder-maven-repo.zip
See my comment here: https://github.com/kiegroup/kogito-images/pull/1364#issuecomment-1315303408

2022-11-15 13:37 UTC, radtriste commented on scripts/build-quarkus-app.sh
> +echo "Zip and copy maven repo"
unzip is done only as build time, not at runtime time. So there won't be any impact when using the image in the end.

2022-11-15 13:38 UTC, radtriste commented on image.yaml
> +  - name: "QUARKUS_VERSION"
I think it would be good to keep both values together. This makes it more visible to everybody.

2022-11-15 13:38 UTC, radtriste commented on modules/kogito-s2i-core/module.yaml
> -  - name: QUARKUS_VERSION
moved to the image.yaml file.
And I think it is preferrable that the user does not change it in the end as our image are made more or less to work with a specific Kogito version

2022-11-16 13:56 UTC, spolti commented on modules/kogito-swf-builder/configure.sh
> +ls -al "${KOGITO_HOME}/.m2/repository"
I meant, is the `ls` command necessary?

2022-11-16 13:59 UTC, radtriste commented on modules/kogito-swf-builder/configure.sh
> +ls -al "${KOGITO_HOME}/.m2/repository"
oh I see ^^ yeah it was for debug, gonna remove it

2022-11-18 13:55 UTC, radtriste commented on image.yaml
> +    description: Please do not change
updated

2022-11-18 13:56 UTC, radtriste commented on modules/kogito-swf-builder/configure.sh
> +ls -al "${KOGITO_HOME}/.m2/repository"
removed

2022-11-18 13:56 UTC, radtriste commented on modules/kogito-swf-builder/added/add-extension.sh
>      set -x
I changed the start of the script to:

```
source "${script_dir_path}"/logging.sh

if [ "${SCRIPT_DEBUG}" = "true" ] ; then
    set -x
    export MAVEN_ARGS_APPEND="${MAVEN_ARGS_APPEND} -X --batch-mode" 
    log_info "Script debugging is enabled, allowing bash commands and their arguments to be printed as they are executed"
    printenv
fi

# Call the configure-maven here
source "${script_dir_path}"/configure-maven.sh
configure
```

to set everything correctly

2022-11-18 13:57 UTC, radtriste commented
I guess we will add it for next Sprint, it will be safer

2022-11-18 14:11 UTC, desmax74 approved these changes

2022-11-21 14:10 UTC, radtriste commented
@spolti please review and merge then you see fit.
Branching for 1.30.x has already been done, so it is safe to merge now :)

2022-11-22 14:25 UTC, spolti approved these changes

2022-11-22 14:35 UTC, merged