KOGITO-8526: Data Index Adds quarkus profile 'kafka-events-support' by default
apache/incubator-kie-kogito-images pull request #1415
Opened 2023-01-25 18:10 UTC by nmirasch

jira: https://issues.redhat.com/browse/KOGITO-8526 

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- <b>(Re)run Jenkins tests</b>  
  Please add comment: <b>Jenkins [test|retest] this</b>

- <b>Prod tests</b>  
  Please add comment: <b>Jenkins (re)run [prod|Prod|PROD]</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

2023-01-25 18:19 UTC, spolti commented on modules/kogito-data-index-common/added/launch/kogito-data-index-common.sh
> +    KOGITO_DATA_INDEX_PROPS="${KOGITO_DATA_INDEX_PROPS} -Dquarkus.profile=kafka-events-support"
maybe create the env QUARKUS_PROFILE and default to kafka-events-support so it can be configured if needed.

2023-01-25 19:07 UTC, kie-ci1 commented
**PR job** `#433` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Build failures on those images:
- kogito-task-console
- kogito-trusty-ui


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/433/display/redirect

**Test results:**
- PASSED: 208
- FAILED: 20

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/433/testReport/features.image.data-index.kogito-data-index-oracle.Kogito-data-index oracle feature//verify_if_of_container_is_correctly_started_with_oracle_parameters/">features.image.data-index.kogito-data-index-oracle.Kogito-data-index oracle feature..verify if of container is correctly started with oracle parameters</a></summary>
Message '-Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080 -jar /home/kogito/bin/quarkus-app/quarkus-run.jar' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/433/testReport/features.image.common-custom-truststore/Common tests for Custom TrustStore configuration/Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Verify_if_a_custom_certificate_is_correctly_handled/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.common-custom-truststore.Common tests for Custom TrustStore configuration.Verify if a custom certificate is correctly handled</a></summary>
Message 'INFO ---> Configuring custom Java Truststore 'my-truststore.jks' in the path /home/kogito/certs/custom-truststore' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/433/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Verify_if_the_properties_were_correctly_set_using_DEFAULT_MEM_RATIO/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if the properties were correctly set using DEFAULT MEM RATIO</a></summary>
Regex '-Xms205m' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/433/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Verify_if_the_DEFAULT_MEM_RATIO_properties_are_overridden_with_different_values/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if the DEFAULT MEM RATIO properties are overridden with different values</a></summary>
Regex '-Xms51m' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/433/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Verify_if_the_properties_were_correctly_set_when_aren't_passed/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if the properties were correctly set when aren't passed</a></summary>
Regex '-Xms128m' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/433/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Verify_if_Java_Remote_Debug_is_correctly_configured/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if Java Remote Debug is correctly configured</a></summary>
Regex '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9222' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/433/testReport/features.image.data-index.kogito-data-index-common.Kogito-data-index common feature//Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Scenario:_Verify_if_the_debug_is_correctly_enabled_and_test_default_http_port/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.data-index.kogito-data-index-common.Kogito-data-index common feature..Scenario: Verify if the debug is correctly enabled and test default http port</a></summary>
Message '-Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/433/testReport/features.image.common-custom-truststore/Common tests for Custom TrustStore configuration/Build___Test_Images___Build_Test_kogito_data_index_infinispan___Build/Test_kogito_data_index_infinispan___Verify_if_a_custom_certificate_is_correctly_handled/">Build & Test Images / Build&Test kogito-data-index-infinispan / Build/Test kogito-data-index-infinispan / features.image.common-custom-truststore.Common tests for Custom TrustStore configuration.Verify if a custom certificate is correctly handled</a></summary>
Message 'INFO ---> Configuring custom Java Truststore 'my-truststore.jks' in the path /home/kogito/certs/custom-truststore' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/433/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_infinispan___Build/Test_kogito_data_index_infinispan___Verify_if_the_properties_were_correctly_set_using_DEFAULT_MEM_RATIO/">Build & Test Images / Build&Test kogito-data-index-infinispan / Build/Test kogito-data-index-infinispan / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if the properties were correctly set using DEFAULT MEM RATIO</a></summary>
Regex '-Xms205m' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/433/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_infinispan___Build/Test_kogito_data_index_infinispan___Verify_if_the_DEFAULT_MEM_RATIO_properties_are_overridden_with_different_values/">Build & Test Images / Build&Test kogito-data-index-infinispan / Build/Test kogito-data-index-infinispan / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if the DEFAULT MEM RATIO p [...]

2023-01-26 20:19 UTC, nmirasch commented
@spolti updated, could you take a look please? Thanks!

2023-01-26 21:03 UTC, kie-ci1 commented
**PR job** `#438` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/438/display/redirect

**Test results:**
- PASSED: 228
- FAILED: 21

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/438/testReport/features.image.data-index.kogito-data-index-oracle.Kogito-data-index oracle feature//verify_if_of_container_is_correctly_started_with_oracle_parameters/">features.image.data-index.kogito-data-index-oracle.Kogito-data-index oracle feature..verify if of container is correctly started with oracle parameters</a></summary>
Message '-Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080 -jar /home/kogito/bin/quarkus-app/quarkus-run.jar' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/438/testReport/features.image.kogito-swf-builder/SWF and Quarkus installation/verify_if_there_is_no_dependencies_with_multiple_versions_in_/home/kogito/.m2/repository/">features.image.kogito-swf-builder.SWF and Quarkus installation.verify if there is no dependencies with multiple versions in /home/kogito/.m2/repository</a></summary>
local variable 'exception_cause' referenced before assignment
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/438/testReport/features.image.common-custom-truststore/Common tests for Custom TrustStore configuration/Build___Test_Images___Build_Test_kogito_data_index_infinispan___Build/Test_kogito_data_index_infinispan___Verify_if_a_custom_certificate_is_correctly_handled/">Build & Test Images / Build&Test kogito-data-index-infinispan / Build/Test kogito-data-index-infinispan / features.image.common-custom-truststore.Common tests for Custom TrustStore configuration.Verify if a custom certificate is correctly handled</a></summary>
Message 'INFO ---> Configuring custom Java Truststore 'my-truststore.jks' in the path /home/kogito/certs/custom-truststore' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/438/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_infinispan___Build/Test_kogito_data_index_infinispan___Verify_if_the_properties_were_correctly_set_using_DEFAULT_MEM_RATIO/">Build & Test Images / Build&Test kogito-data-index-infinispan / Build/Test kogito-data-index-infinispan / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if the properties were correctly set using DEFAULT MEM RATIO</a></summary>
Regex '-Xms205m' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/438/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_infinispan___Build/Test_kogito_data_index_infinispan___Verify_if_the_DEFAULT_MEM_RATIO_properties_are_overridden_with_different_values/">Build & Test Images / Build&Test kogito-data-index-infinispan / Build/Test kogito-data-index-infinispan / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if the DEFAULT MEM RATIO properties are overridden with different values</a></summary>
Regex '-Xms51m' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/438/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_infinispan___Build/Test_kogito_data_index_infinispan___Verify_if_the_properties_were_correctly_set_when_aren't_passed/">Build & Test Images / Build&Test kogito-data-index-infinispan / Build/Test kogito-data-index-infinispan / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if the properties were correctly set when aren't passed</a></summary>
Regex '-Xms128m' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/438/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_infinispan___Build/Test_kogito_data_index_infinispan___Verify_if_Java_Remote_Debug_is_correctly_configured/">Build & Test Images / Build&Test kogito-data-index-infinispan / Build/Test kogito-data-index-infinispan / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if Java Remote Debug is correctly configured</a></summary>
Regex '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9222' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/438/testReport/features.image.data-index.kogito-data-index-common.Kogito-data-index common feature//Build___Test_Images___Build_Test_kogito_data_index_infinispan___Build/Test_kogito_data_index_infinispan___Scenario:_Verify_if_the_debug_is_correctly_enabled_and_test_default_http_port/">Build & Test Images / Build&Test kogito-data-index-infinispan / Build/Test kogito-data-index-infinispan / features.image.data-index.kogito-data-index-common.Kogito-data-index common feature..Scenario: Verify if the debug is correctly enabled and test default http port</a></summary>
Message '-Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/438/testReport/features.image.common-custom-truststore/Common tests for Custom TrustStore configuration/Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Verify_if_a_custom_certificate_is_correctly_handled/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.common-custom-truststore.Common tests for Custom TrustStore configuration.Verify if a custom certificate is correctly handled</a></summary>
Message 'INFO ---> Configuring custom Java Truststore 'my-truststore.jks' in the path /home/kogito/certs/custom-truststore' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/438/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Verify_if_the_properties_were_correctly_set_using_DEFAULT_MEM_RATIO/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if the properties were correctly set using DEFAULT MEM RATIO</a></summary>
Regex '-Xms205m' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job [...]

2023-01-27 14:09 UTC, spolti requested changes
Thanks for the changes @nmirasch 
Just one thing, do you mind adding three behave tests as well?
One for testing the default, the other supported value and a wrong value? 
Then you can assert the log messages.

2023-01-27 16:51 UTC, nmirasch commented on modules/kogito-data-index-common/tests/bats/kogito-data-index-common.bats
> +@test "check if the default quarkus profile is correctly set on data index" {
@spolti Here is where I tried to add the testing for the different cases of KOGITO_DATA_INDEX_QUARKUS_PROFILE configuration. Could you point me where should I add the test you required in your review comment, please? Thanks!

2023-01-27 17:35 UTC, spolti commented on modules/kogito-data-index-common/tests/bats/kogito-data-index-common.bats
> +@test "check if the default quarkus profile is correctly set on data index" {
@nmirasch this is the bats tests, the behave for data-index you can find at https://github.com/kiegroup/kogito-images/tree/main/tests/features/data-index

you can use the common feature to add these tests.

2023-01-30 09:15 UTC, kie-ci1 commented
**PR job** `#455` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/455/display/redirect

**Test results:**
- PASSED: 229
- FAILED: 33

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/455/testReport/features.image.data-index.kogito-data-index-oracle.Kogito-data-index oracle feature//verify_if_of_container_is_correctly_started_with_oracle_parameters/">features.image.data-index.kogito-data-index-oracle.Kogito-data-index oracle feature..verify if of container is correctly started with oracle parameters</a></summary>
Message '-Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080 -jar /home/kogito/bin/quarkus-app/quarkus-run.jar' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/455/testReport/features.image.kogito-swf-builder/SWF and Quarkus installation/verify_if_there_is_no_dependencies_with_multiple_versions_in_/home/kogito/.m2/repository/">features.image.kogito-swf-builder.SWF and Quarkus installation.verify if there is no dependencies with multiple versions in /home/kogito/.m2/repository</a></summary>
local variable 'exception_cause' referenced before assignment
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/455/testReport/features.image.data-index.kogito-data-index-common.Kogito-data-index common feature//Build___Test_Images___Build_Test_kogito_data_index_ephemeral___Build/Test_kogito_data_index_ephemeral___Scenario:_check_if_the_default_quarkus_profile_is_correctly_set_on_data_index/">Build & Test Images / Build&Test kogito-data-index-ephemeral / Build/Test kogito-data-index-ephemeral / features.image.data-index.kogito-data-index-common.Kogito-data-index common feature..Scenario: check if the default quarkus profile is correctly set on data index</a></summary>
Message '-Dquarkus.profile=kafka-events-support' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/455/testReport/features.image.data-index.kogito-data-index-common.Kogito-data-index common feature//Build___Test_Images___Build_Test_kogito_data_index_ephemeral___Build/Test_kogito_data_index_ephemeral___Scenario:_check_if_a_provided_data_index_quarkus_profile_is_correctly_set_on_data_index/">Build & Test Images / Build&Test kogito-data-index-ephemeral / Build/Test kogito-data-index-ephemeral / features.image.data-index.kogito-data-index-common.Kogito-data-index common feature..Scenario: check if a provided data index quarkus profile is correctly set on data index</a></summary>
Message '-Dquarkus.profile=http-events-support' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/455/testReport/features.image.data-index.kogito-data-index-common.Kogito-data-index common feature//Build___Test_Images___Build_Test_kogito_data_index_ephemeral___Build/Test_kogito_data_index_ephemeral___Scenario:_test_if_a_invalid_value_for_data_index_quarkus_profile_will_set_the_default_value/">Build & Test Images / Build&Test kogito-data-index-ephemeral / Build/Test kogito-data-index-ephemeral / features.image.data-index.kogito-data-index-common.Kogito-data-index common feature..Scenario: test if a invalid value for data-index quarkus profile will set the default value</a></summary>
Message '-Dquarkus.profile=kafka-events-support' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/455/testReport/features.image.common-custom-truststore/Common tests for Custom TrustStore configuration/Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Verify_if_a_custom_certificate_is_correctly_handled/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.common-custom-truststore.Common tests for Custom TrustStore configuration.Verify if a custom certificate is correctly handled</a></summary>
Message 'INFO ---> Configuring custom Java Truststore 'my-truststore.jks' in the path /home/kogito/certs/custom-truststore' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/455/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Verify_if_the_properties_were_correctly_set_using_DEFAULT_MEM_RATIO/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if the properties were correctly set using DEFAULT MEM RATIO</a></summary>
Regex '-Xms205m' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/455/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Verify_if_the_DEFAULT_MEM_RATIO_properties_are_overridden_with_different_values/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if the DEFAULT MEM RATIO properties are overridden with different values</a></summary>
Regex '-Xms51m' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/455/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Verify_if_the_properties_were_correctly_set_when_aren't_passed/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if the properties were correctly set when aren't passed</a></summary>
Regex '-Xms128m' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/455/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Verify_if_Java_Remote_Debug_is_correctly_configured/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if Java Remote Debug is correctly configured</a></summary>
Regex '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9222' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job [...]

2023-01-30 19:18 UTC, spolti commented on modules/kogito-data-index-common/added/launch/kogito-data-index-common.sh
> +        if [[ "${quarkusProfile}" != "kafka-events-support"  &&  "${quarkusProfile}" != "http-events-support" ]]; then
shouldn't be `||` instead `&&`?

2023-01-31 09:11 UTC, kie-ci1 commented
**PR job** `#471` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/471/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
make: *** [clone-repos] Error 1<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build & Test Images)<br/>Stage "Build & Test Images" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-images/workspaces<br/>[Pipeline] sh<br/>++ docker ps -a -q<br/>+ docker rm -f<br/>"docker rm" requires at least 1 argument.<br/>See 'docker rm --help'.<br/><br/>Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]<br/><br/>Remove one or more containers<br/>+ date<br/>Tue Jan 31 04:11:46 EST 2023<br/>[Pipeline] sh<br/>++ docker images -q<br/>+ docker rmi -f<br/>"docker rmi" requires at least 1 argument.<br/>See 'docker rmi --help'.<br/><br/>Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]<br/><br/>Remove one or more images<br/>+ date<br/>Tue Jan 31 04:11:47 EST 2023<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/.cekit/cache<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/471/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

2023-01-31 14:32 UTC, nmirasch commented
jenkins please retest this

2023-01-31 14:35 UTC, kie-ci1 commented
**PR job** `#472` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/472/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
make: *** [clone-repos] Error 1<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build & Test Images)<br/>Stage "Build & Test Images" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-images/workspaces<br/>[Pipeline] sh<br/>++ docker ps -a -q<br/>+ docker rm -f<br/>"docker rm" requires at least 1 argument.<br/>See 'docker rm --help'.<br/><br/>Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]<br/><br/>Remove one or more containers<br/>+ date<br/>Tue Jan 31 09:34:59 EST 2023<br/>[Pipeline] sh<br/>++ docker images -q<br/>+ docker rmi -f<br/>"docker rmi" requires at least 1 argument.<br/>See 'docker rmi --help'.<br/><br/>Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]<br/><br/>Remove one or more images<br/>+ date<br/>Tue Jan 31 09:34:59 EST 2023<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/.cekit/cache<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/472/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

2023-01-31 16:09 UTC, spolti commented on tests/features/data-index/kogito-data-index-infinispan.feature
> +  Scenario:   Scenario: check if the default quarkus profile is correctly set on data index
maybe move these scenarios to the common.feature?

2023-02-01 10:07 UTC, kie-ci1 commented
**PR job** `#473` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/473/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
make: *** [clone-repos] Error 1<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build & Test Images)<br/>Stage "Build & Test Images" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-images/workspaces<br/>[Pipeline] sh<br/>++ docker ps -a -q<br/>+ docker rm -f<br/>"docker rm" requires at least 1 argument.<br/>See 'docker rm --help'.<br/><br/>Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]<br/><br/>Remove one or more containers<br/>+ date<br/>Wed Feb  1 05:07:32 EST 2023<br/>[Pipeline] sh<br/>++ docker images -q<br/>+ docker rmi -f<br/>"docker rmi" requires at least 1 argument.<br/>See 'docker rmi --help'.<br/><br/>Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]<br/><br/>Remove one or more images<br/>+ date<br/>Wed Feb  1 05:07:32 EST 2023<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/.cekit/cache<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/473/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

2023-02-01 10:12 UTC, nmirasch commented on modules/kogito-data-index-common/added/launch/kogito-data-index-common.sh
> +        if [[ "${quarkusProfile}" != "kafka-events-support"  &&  "${quarkusProfile}" != "http-events-support" ]]; then
@spolti the only values allowed are 'kafka-events-support' and 'http-events-support', If the configured value is different from both of them then, the idea is to set the quarkus profile to the default value 'kafka-events-support'.

2023-02-01 10:16 UTC, nmirasch commented on tests/features/data-index/kogito-data-index-infinispan.feature
> +  Scenario:   Scenario: check if the default quarkus profile is correctly set on data index
@spolti I agree, I put them at the beginning to the common feature but the ephemeral image wasn't calling the new script to handle the new quarkus.profile configuration. I've added the script  to the ephemeral image too now and that allows me to place these checks at common.feature again. Thanks!

2023-02-01 15:55 UTC, spolti commented on modules/kogito-data-index-common/added/launch/kogito-data-index-common.sh
> +            log_info "Data Index Quarkus profile ${quarkusProfile} undefined. Replacing by the default: `kafka-events-support`"
```suggestion
            log_info "Data Index Quarkus profile ${quarkusProfile} is not valid. Replacing by the default: `kafka-events-support`"
```

2023-02-01 15:56 UTC, spolti approved these changes

2023-02-01 15:56 UTC, spolti commented
/jenkins retest this

2023-02-01 15:57 UTC, kie-ci1 commented
**PR job** `#475` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/475/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
make: *** [clone-repos] Error 1<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build & Test Images)<br/>Stage "Build & Test Images" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-images/workspaces<br/>[Pipeline] sh<br/>++ docker ps -a -q<br/>+ docker rm -f<br/>"docker rm" requires at least 1 argument.<br/>See 'docker rm --help'.<br/><br/>Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]<br/><br/>Remove one or more containers<br/>+ date<br/>Wed Feb  1 10:57:27 EST 2023<br/>[Pipeline] sh<br/>++ docker images -q<br/>+ docker rmi -f<br/>"docker rmi" requires at least 1 argument.<br/>See 'docker rmi --help'.<br/><br/>Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]<br/><br/>Remove one or more images<br/>+ date<br/>Wed Feb  1 10:57:28 EST 2023<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/.cekit/cache<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/475/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

2023-02-03 17:35 UTC, kie-ci1 commented
**PR job** `#478` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Build failures on those images:
- kogito-management-console


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/478/display/redirect

**Test results:**
- PASSED: 211
- FAILED: 39

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/478/testReport/features.image.data-index.kogito-data-index-oracle.Kogito-data-index oracle feature//verify_if_of_container_is_correctly_started_with_oracle_parameters/">features.image.data-index.kogito-data-index-oracle.Kogito-data-index oracle feature..verify if of container is correctly started with oracle parameters</a></summary>
Message '-Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080 -jar /home/kogito/bin/quarkus-app/quarkus-run.jar' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/478/testReport/features.image.common-custom-truststore/Common tests for Custom TrustStore configuration/Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Verify_if_a_custom_certificate_is_correctly_handled/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.common-custom-truststore.Common tests for Custom TrustStore configuration.Verify if a custom certificate is correctly handled</a></summary>
Message 'INFO ---> Configuring custom Java Truststore 'my-truststore.jks' in the path /home/kogito/certs/custom-truststore' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/478/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Verify_if_the_properties_were_correctly_set_using_DEFAULT_MEM_RATIO/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if the properties were correctly set using DEFAULT MEM RATIO</a></summary>
Regex '-Xms205m' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/478/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Verify_if_the_DEFAULT_MEM_RATIO_properties_are_overridden_with_different_values/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if the DEFAULT MEM RATIO properties are overridden with different values</a></summary>
Regex '-Xms51m' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/478/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Verify_if_the_properties_were_correctly_set_when_aren't_passed/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if the properties were correctly set when aren't passed</a></summary>
Regex '-Xms128m' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/478/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Verify_if_Java_Remote_Debug_is_correctly_configured/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if Java Remote Debug is correctly configured</a></summary>
Regex '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9222' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/478/testReport/features.image.data-index.kogito-data-index-common.Kogito-data-index common feature//Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Scenario:_Verify_if_the_debug_is_correctly_enabled_and_test_default_http_port/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.data-index.kogito-data-index-common.Kogito-data-index common feature..Scenario: Verify if the debug is correctly enabled and test default http port</a></summary>
Message '-Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/478/testReport/features.image.data-index.kogito-data-index-common.Kogito-data-index common feature//Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Scenario:_check_if_the_default_quarkus_profile_is_correctly_set_on_data_index/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.data-index.kogito-data-index-common.Kogito-data-index common feature..Scenario: check if the default quarkus profile is correctly set on data index</a></summary>
Message '-Dquarkus.profile=kafka-events-support' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/478/testReport/features.image.data-index.kogito-data-index-common.Kogito-data-index common feature//Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Scenario:_check_if_a_provided_data_index_quarkus_profile_is_correctly_set_on_data_index/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.data-index.kogito-data-index-common.Kogito-data-index common feature..Scenario: check if a provided data index quarkus profile is correctly set on data index</a></summary>
Message '-Dquarkus.profile=http-events-support' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/478/testReport/features.image.data-index.kogito-data-index-common.Kogito-data-index common feature//Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Scenario:_test_if_a_invalid_value_for_data_index_quarkus_profile_will_set_the_default_value/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.data-index.kogito-data-index-common.Kogit [...]

2023-02-08 11:23 UTC, radtriste requested changes

2023-02-08 11:23 UTC, radtriste commented on modules/kogito-data-index-common/added/launch/kogito-data-index-common.sh
> +    fi
`kafka-events-support` is already the default env defined in `KOGITO_DATA_INDEX_QUARKUS_PROFILE`
I would not check the value. That would allow to extend easily if needed.
if that `KOGITO_DATA_INDEX_QUARKUS_PROFILE` is changed, this is done on purpose and you should let the user be responsible of that change. You should not fallback to anything IMO

2023-02-08 11:24 UTC, radtriste commented
jenkins retest this

2023-02-08 11:26 UTC, kie-ci1 commented
**PR job** `#479` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/479/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Prepare for tests)<br/>Stage "Prepare for tests" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build & Test Images)<br/>Stage "Build & Test Images" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-images/workspaces<br/>[Pipeline] sh<br/>++ docker ps -a -q<br/>+ docker rm -f<br/>"docker rm" requires at least 1 argument.<br/>See 'docker rm --help'.<br/><br/>Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]<br/><br/>Remove one or more containers<br/>+ date<br/>Wed Feb  8 06:26:20 EST 2023<br/>[Pipeline] sh<br/>++ docker images -q<br/>+ docker rmi -f<br/>"docker rmi" requires at least 1 argument.<br/>See 'docker rmi --help'.<br/><br/>Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]<br/><br/>Remove one or more images<br/>+ date<br/>Wed Feb  8 06:26:20 EST 2023<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/.cekit/cache<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/479/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

2023-02-08 11:27 UTC, radtriste commented
@nmirasch Could you rebase your PR ? :)

2023-02-08 12:14 UTC, nmirasch commented on modules/kogito-data-index-common/added/launch/kogito-data-index-common.sh
> +    fi
@radtriste then only add the default value kafka-events-support, in case nothing is passed in KOGITO_DATA_INDEX_QUARKUS_PROFILE, is that the suggestion? For sure, as you said it would let to extend easily without having to change the image generation.  Let me give this a try.

2023-02-08 14:28 UTC, nmirasch commented
@spolti Following the @radtriste suggestion about to simplify the check on the provided KOGITO_DATA_INDEX_QUARKUS_PROFILE variable, the code has change to just add the default kafka-events-support only when no value is provided. Could you take a look again and let me know what do you think? Thanks!

2023-02-08 15:45 UTC, radtriste commented
> @spolti Following the @radtriste suggestion about to simplify the check on the provided KOGITO_DATA_INDEX_QUARKUS_PROFILE variable, the code has change to just add the default kafka-events-support only when no value is provided. Could you take a look again and let me know what do you think? Thanks!

@nmirasch In fact I meant that, due to [this](https://github.com/kiegroup/kogito-images/pull/1415/files#diff-34980a10264383333ab7eb37709857df7f6521b3b543e02a134611efe5338086R8), you don't need to check for a default value, it is already setup as default environment variable.
But the user can still override it if needed.
So even the check for empty value does not make much sense to me. @spolti wdyt ?

2023-02-09 14:24 UTC, nmirasch commented
@radtriste I think makes sense your suggestion, I removed the check if empty and just let the kafka-events-support as default value for the environment var.

2023-02-09 14:28 UTC, radtriste approved these changes

2023-02-09 15:31 UTC, spolti commented
feel free to merge once ci is green.

2023-02-09 15:34 UTC, kie-ci1 commented
**PR job** `#482` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Build failures on those images:
- kogito-management-console


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/482/display/redirect

**Test results:**
- PASSED: 211
- FAILED: 35

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/482/testReport/features.image.data-index.kogito-data-index-oracle.Kogito-data-index oracle feature//verify_if_of_container_is_correctly_started_with_oracle_parameters/">features.image.data-index.kogito-data-index-oracle.Kogito-data-index oracle feature..verify if of container is correctly started with oracle parameters</a></summary>
Message '-Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080 -jar /home/kogito/bin/quarkus-app/quarkus-run.jar' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/482/testReport/features.image.common-custom-truststore/Common tests for Custom TrustStore configuration/Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Verify_if_a_custom_certificate_is_correctly_handled/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.common-custom-truststore.Common tests for Custom TrustStore configuration.Verify if a custom certificate is correctly handled</a></summary>
Message 'INFO ---> Configuring custom Java Truststore 'my-truststore.jks' in the path /home/kogito/certs/custom-truststore' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/482/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Verify_if_the_properties_were_correctly_set_using_DEFAULT_MEM_RATIO/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if the properties were correctly set using DEFAULT MEM RATIO</a></summary>
Regex '-Xms205m' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/482/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Verify_if_the_DEFAULT_MEM_RATIO_properties_are_overridden_with_different_values/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if the DEFAULT MEM RATIO properties are overridden with different values</a></summary>
Regex '-Xms51m' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/482/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Verify_if_the_properties_were_correctly_set_when_aren't_passed/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if the properties were correctly set when aren't passed</a></summary>
Regex '-Xms128m' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/482/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Verify_if_Java_Remote_Debug_is_correctly_configured/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if Java Remote Debug is correctly configured</a></summary>
Regex '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9222' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/482/testReport/features.image.data-index.kogito-data-index-common.Kogito-data-index common feature//Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Scenario:_Verify_if_the_debug_is_correctly_enabled_and_test_default_http_port/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.data-index.kogito-data-index-common.Kogito-data-index common feature..Scenario: Verify if the debug is correctly enabled and test default http port</a></summary>
Message '-Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/482/testReport/features.image.data-index.kogito-data-index-common.Kogito-data-index common feature//Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Scenario:_check_if_the_default_quarkus_profile_is_correctly_set_on_data_index/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.data-index.kogito-data-index-common.Kogito-data-index common feature..Scenario: check if the default quarkus profile is correctly set on data index</a></summary>
Message '-Dquarkus.profile=kafka-events-support' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/482/testReport/features.image.data-index.kogito-data-index-common.Kogito-data-index common feature//Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Scenario:_check_if_a_provided_data_index_quarkus_profile_is_correctly_set_on_data_index/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.data-index.kogito-data-index-common.Kogito-data-index common feature..Scenario: check if a provided data index quarkus profile is correctly set on data index</a></summary>
Message '-Dquarkus.profile=http-events-support' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/482/testReport/features.image.common-custom-truststore/Common tests for Custom TrustStore configuration/Build___Test_Images___Build_Test_kogito_data_index_ephemeral___Build/Test_kogito_data_index_ephemeral___Verify_if_a_custom_certificate_is_correctly_handled/">Build & Test Images / Build&Test kogito-data-index-ephemeral / Build/Test kogito-data-index-ephemeral / features.image.common-custom-truststore.Common tests for Custom TrustStore configura [...]

2023-02-13 09:32 UTC, nmirasch commented
jenkins please retest this

2023-02-13 09:36 UTC, kie-ci1 commented
**PR job** `#487` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/487/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Prepare for tests)<br/>Stage "Prepare for tests" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build & Test Images)<br/>Stage "Build & Test Images" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-images/workspaces<br/>[Pipeline] sh<br/>++ docker ps -a -q<br/>+ docker rm -f<br/>"docker rm" requires at least 1 argument.<br/>See 'docker rm --help'.<br/><br/>Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]<br/><br/>Remove one or more containers<br/>+ date<br/>Mon Feb 13 04:36:24 EST 2023<br/>[Pipeline] sh<br/>++ docker images -q<br/>+ docker rmi -f<br/>"docker rmi" requires at least 1 argument.<br/>See 'docker rmi --help'.<br/><br/>Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]<br/><br/>Remove one or more images<br/>+ date<br/>Mon Feb 13 04:36:25 EST 2023<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/.cekit/cache<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/487/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

2023-02-14 09:19 UTC, radtriste commented
@nmirasch I rebased your branch

2023-02-14 10:21 UTC, kie-ci1 commented
**PR job** `#489` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Build failures on those images:
- kogito-management-console
- kogito-task-console
- kogito-trusty-ui


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/489/display/redirect

**Test results:**
- PASSED: 190
- FAILED: 35

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/489/testReport/features.image.data-index.kogito-data-index-oracle.Kogito-data-index oracle feature//verify_if_of_container_is_correctly_started_with_oracle_parameters/">features.image.data-index.kogito-data-index-oracle.Kogito-data-index oracle feature..verify if of container is correctly started with oracle parameters</a></summary>
Message '-Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080 -jar /home/kogito/bin/quarkus-app/quarkus-run.jar' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/489/testReport/features.image.common-custom-truststore/Common tests for Custom TrustStore configuration/Build___Test_Images___Build_Test_kogito_data_index_infinispan___Build/Test_kogito_data_index_infinispan___Verify_if_a_custom_certificate_is_correctly_handled/">Build & Test Images / Build&Test kogito-data-index-infinispan / Build/Test kogito-data-index-infinispan / features.image.common-custom-truststore.Common tests for Custom TrustStore configuration.Verify if a custom certificate is correctly handled</a></summary>
Message 'INFO ---> Configuring custom Java Truststore 'my-truststore.jks' in the path /home/kogito/certs/custom-truststore' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/489/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_infinispan___Build/Test_kogito_data_index_infinispan___Verify_if_the_properties_were_correctly_set_using_DEFAULT_MEM_RATIO/">Build & Test Images / Build&Test kogito-data-index-infinispan / Build/Test kogito-data-index-infinispan / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if the properties were correctly set using DEFAULT MEM RATIO</a></summary>
Regex '-Xms205m' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/489/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_infinispan___Build/Test_kogito_data_index_infinispan___Verify_if_the_DEFAULT_MEM_RATIO_properties_are_overridden_with_different_values/">Build & Test Images / Build&Test kogito-data-index-infinispan / Build/Test kogito-data-index-infinispan / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if the DEFAULT MEM RATIO properties are overridden with different values</a></summary>
Regex '-Xms51m' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/489/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_infinispan___Build/Test_kogito_data_index_infinispan___Verify_if_the_properties_were_correctly_set_when_aren't_passed/">Build & Test Images / Build&Test kogito-data-index-infinispan / Build/Test kogito-data-index-infinispan / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if the properties were correctly set when aren't passed</a></summary>
Regex '-Xms128m' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/489/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_infinispan___Build/Test_kogito_data_index_infinispan___Verify_if_Java_Remote_Debug_is_correctly_configured/">Build & Test Images / Build&Test kogito-data-index-infinispan / Build/Test kogito-data-index-infinispan / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if Java Remote Debug is correctly configured</a></summary>
Regex '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9222' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/489/testReport/features.image.data-index.kogito-data-index-common.Kogito-data-index common feature//Build___Test_Images___Build_Test_kogito_data_index_infinispan___Build/Test_kogito_data_index_infinispan___Scenario:_Verify_if_the_debug_is_correctly_enabled_and_test_default_http_port/">Build & Test Images / Build&Test kogito-data-index-infinispan / Build/Test kogito-data-index-infinispan / features.image.data-index.kogito-data-index-common.Kogito-data-index common feature..Scenario: Verify if the debug is correctly enabled and test default http port</a></summary>
Message '-Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/489/testReport/features.image.data-index.kogito-data-index-common.Kogito-data-index common feature//Build___Test_Images___Build_Test_kogito_data_index_infinispan___Build/Test_kogito_data_index_infinispan___Scenario:_check_if_the_default_quarkus_profile_is_correctly_set_on_data_index/">Build & Test Images / Build&Test kogito-data-index-infinispan / Build/Test kogito-data-index-infinispan / features.image.data-index.kogito-data-index-common.Kogito-data-index common feature..Scenario: check if the default quarkus profile is correctly set on data index</a></summary>
Message '-Dquarkus.profile=kafka-events-support' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/489/testReport/features.image.data-index.kogito-data-index-common.Kogito-data-index common feature//Build___Test_Images___Build_Test_kogito_data_index_infinispan___Build/Test_kogito_data_index_infinispan___Scenario:_check_if_a_provided_data_index_quarkus_profile_is_correctly_set_on_data_index/">Build & Test Images / Build&Test kogito-data-index-infinispan / Build/Test kogito-data-index-infinispan / features.image.data-index.kogito-data-index-common.Kogito-data-index common feature..Scenario: check if a provided data index quarkus profile is correctly set on data index</a></summary>
Message '-Dquarkus.profile=http-events-support' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/489/testReport/features.image.common-custom-truststore/Common tests for Custom TrustStore configuration/Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Verify_if_a_custom_certificate_is_correctly_handled/">Build & Test Images / Build&Test kogito-data-index-mong [...]

2023-02-15 09:46 UTC, kie-ci1 commented
**PR job** `#492` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Build failures on those images:
- kogito-management-console


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/492/display/redirect

**Test results:**
- PASSED: 212
- FAILED: 35

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/492/testReport/features.image.data-index.kogito-data-index-oracle.Kogito-data-index oracle feature//verify_if_of_container_is_correctly_started_with_oracle_parameters/">features.image.data-index.kogito-data-index-oracle.Kogito-data-index oracle feature..verify if of container is correctly started with oracle parameters</a></summary>
Message '-Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080 -jar /home/kogito/bin/quarkus-app/quarkus-run.jar' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/492/testReport/features.image.common-custom-truststore/Common tests for Custom TrustStore configuration/Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Verify_if_a_custom_certificate_is_correctly_handled/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.common-custom-truststore.Common tests for Custom TrustStore configuration.Verify if a custom certificate is correctly handled</a></summary>
Message 'INFO ---> Configuring custom Java Truststore 'my-truststore.jks' in the path /home/kogito/certs/custom-truststore' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/492/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Verify_if_the_properties_were_correctly_set_using_DEFAULT_MEM_RATIO/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if the properties were correctly set using DEFAULT MEM RATIO</a></summary>
Regex '-Xms205m' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/492/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Verify_if_the_DEFAULT_MEM_RATIO_properties_are_overridden_with_different_values/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if the DEFAULT MEM RATIO properties are overridden with different values</a></summary>
Regex '-Xms51m' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/492/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Verify_if_the_properties_were_correctly_set_when_aren't_passed/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if the properties were correctly set when aren't passed</a></summary>
Regex '-Xms128m' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/492/testReport/features.image.common-dynamic-resources/Common tests for Kogito images/Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Verify_if_Java_Remote_Debug_is_correctly_configured/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.common-dynamic-resources.Common tests for Kogito images.Verify if Java Remote Debug is correctly configured</a></summary>
Regex '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9222' did not match the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/492/testReport/features.image.data-index.kogito-data-index-common.Kogito-data-index common feature//Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Scenario:_Verify_if_the_debug_is_correctly_enabled_and_test_default_http_port/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.data-index.kogito-data-index-common.Kogito-data-index common feature..Scenario: Verify if the debug is correctly enabled and test default http port</a></summary>
Message '-Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/492/testReport/features.image.data-index.kogito-data-index-common.Kogito-data-index common feature//Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Scenario:_check_if_the_default_quarkus_profile_is_correctly_set_on_data_index/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.data-index.kogito-data-index-common.Kogito-data-index common feature..Scenario: check if the default quarkus profile is correctly set on data index</a></summary>
Message '-Dquarkus.profile=kafka-events-support' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/492/testReport/features.image.data-index.kogito-data-index-common.Kogito-data-index common feature//Build___Test_Images___Build_Test_kogito_data_index_mongodb___Build/Test_kogito_data_index_mongodb___Scenario:_check_if_a_provided_data_index_quarkus_profile_is_correctly_set_on_data_index/">Build & Test Images / Build&Test kogito-data-index-mongodb / Build/Test kogito-data-index-mongodb / features.image.data-index.kogito-data-index-common.Kogito-data-index common feature..Scenario: check if a provided data index quarkus profile is correctly set on data index</a></summary>
Message '-Dquarkus.profile=http-events-support' was not found in the logs
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/492/testReport/features.image.common-custom-truststore/Common tests for Custom TrustStore configuration/Build___Test_Images___Build_Test_kogito_data_index_infinispan___Build/Test_kogito_data_index_infinispan___Verify_if_a_custom_certificate_is_correctly_handled/">Build & Test Images / Build&Test kogito-data-index-infinispan / Build/Test kogito-data-index-infinispan / features.image.common-custom-truststore.Common tests for Custom TrustStore confi [...]

2023-02-15 17:37 UTC, spolti commented on modules/kogito-data-index-common/added/launch/kogito-data-index-common.sh
> +    KOGITO_DATA_INDEX_PROPS="${KOGITO_DATA_INDEX_PROPS} -Dquarkus.profile=${quarkusProfile}"
seems that you have changed it, what happens if user now sets a invalid value?

2023-02-16 08:27 UTC, radtriste commented on modules/kogito-data-index-common/added/launch/kogito-data-index-common.sh
> +    KOGITO_DATA_INDEX_PROPS="${KOGITO_DATA_INDEX_PROPS} -Dquarkus.profile=${quarkusProfile}"
I guess the application will complain that the profile does not exist and the application may not start. But that is not the duty of the image

2023-02-16 08:38 UTC, radtriste commented
@nmirasch trying to build and run the `kogito-data-index-ephemeral` image, I get:
```
/home/kogito/launch/configure.sh: line 68: /home/kogito/launch/kogito-data-index-common.sh: No such file or directory
```

2023-02-16 09:02 UTC, radtriste commented
pushed a fix :)

2023-02-16 09:15 UTC, radtriste commented
Jenkins retest this

2023-02-16 09:41 UTC, radtriste commented
Jenkins retest this

2023-02-16 09:51 UTC, kie-ci1 commented
**PR job** `#495` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/495/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Prepare for tests)<br/>Stage "Prepare for tests" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build & Test Images)<br/>Stage "Build & Test Images" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-images/workspaces<br/>[Pipeline] sh<br/>++ docker ps -a -q<br/>+ docker rm -f<br/>"docker rm" requires at least 1 argument.<br/>See 'docker rm --help'.<br/><br/>Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]<br/><br/>Remove one or more containers<br/>+ date<br/>Thu Feb 16 04:51:20 EST 2023<br/>[Pipeline] sh<br/>++ docker images -q<br/>+ docker rmi -f<br/>"docker rmi" requires at least 1 argument.<br/>See 'docker rmi --help'.<br/><br/>Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]<br/><br/>Remove one or more images<br/>+ date<br/>Thu Feb 16 04:51:20 EST 2023<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/.cekit/cache<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/495/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

2023-02-16 09:51 UTC, kie-ci1 commented
**PR job** `#494` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/494/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Prepare for tests)<br/>Stage "Prepare for tests" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build & Test Images)<br/>Stage "Build & Test Images" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-images/workspaces<br/>[Pipeline] sh<br/>++ docker ps -a -q<br/>+ docker rm -f<br/>"docker rm" requires at least 1 argument.<br/>See 'docker rm --help'.<br/><br/>Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]<br/><br/>Remove one or more containers<br/>+ date<br/>Thu Feb 16 04:51:34 EST 2023<br/>[Pipeline] sh<br/>++ docker images -q<br/>+ docker rmi -f<br/>"docker rmi" requires at least 1 argument.<br/>See 'docker rmi --help'.<br/><br/>Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]<br/><br/>Remove one or more images<br/>+ date<br/>Thu Feb 16 04:51:34 EST 2023<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/.cekit/cache<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/494/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

2023-02-16 09:58 UTC, radtriste commented
jenkins retest this

2023-02-16 12:38 UTC, spolti commented
all green :)

2023-02-16 12:39 UTC, spolti commented
@nmirasch before merging, can you please add this jira in the release notes?

2023-02-21 11:08 UTC, kie-ci1 commented
**PR job** `#540` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Build failures on those images:
- kogito-management-console


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/540/display/redirect

**Test results:**
- PASSED: 247
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>kogito-management-console</b></summary>
++ '[' -z '' ']'<br/>++ hash -r<br/>++ '[' -z '' ']'<br/>++ unset VIRTUAL_ENV<br/>++ '[' '!' nondestructive = nondestructive ']'<br/>++ VIRTUAL_ENV=/home/jenkins/virtenvs/cekit<br/>++ '[' linux-gnu = cygwin ']'<br/>++ '[' linux-gnu = msys ']'<br/>++ export VIRTUAL_ENV<br/>++ _OLD_VIRTUAL_PATH=/opt/tools/jdk11/bin:/opt/tools/jdk11/bin:/home/jenkins/go/bin:/opt/tools/golang/1.19/go/bin:/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.8.7/bin:/opt/tools/apache-ant-1.10.9/bin:/opt/tools/mercurial/:/opt/tools/extras/:/usr/local/bin:/usr/bin:/opt/tools/graalvm/bin<br/>++ PATH=/home/jenkins/virtenvs/cekit/bin:/opt/tools/jdk11/bin:/opt/tools/jdk11/bin:/home/jenkins/go/bin:/opt/tools/golang/1.19/go/bin:/opt/tools/jdk11/bin:/opt/tools/apache-maven-3.8.7/bin:/opt/tools/apache-ant-1.10.9/bin:/opt/tools/mercurial/:/opt/tools/extras/:/usr/local/bin:/usr/bin:/opt/tools/graalvm/bin<br/>++ export PATH<br/>++ '[' -z '' ']'<br/>++ '[' -z '' ']'<br/>++ _OLD_VIRTUAL_PS1=<br/>++ '[' x '!=' x ']'<br/>+++ basename /home/jenkins/virtenvs/cekit<br/>++ PS1='(cekit) '<br/>++ export PS1<br/>++ alias pydoc<br/>++ true<br/>++ hash -r<br/>+ make build-image 'cekit_option=--work-dir .' KOGITO_APPS_TARGET_BRANCH=main image_name=kogito-base-builder ignore_build=true ignore_test_prepare=true ignore_tag=false<br/>docker tag quay.io/kiegroup/kogito-base-builder:2.0.0-snapshot quay.io/kiegroup/kogito-base-builder:2.0<br/> (deflated 10%)<br/>  adding: quarkus-app/lib/main/org.kie.kogito.kogito-addons-quarkus-persistence-infinispan-health-2.0.0-SNAPSHOT.jar (deflated 20%)<br/>  adding: quarkus-app/lib/main/io.smallrye.smallrye-health-3.3.1.jar (deflated 11%)<br/>  adding: quarkus-app/lib/main/io.smallrye.smallrye-health-api-3.3.1.jar (deflated 27%)<br/>  adding: quarkus-app/lib/boot/ (stored 0%)<br/>  adding: quarkus-app/lib/boot/org.jboss.logmanager.jboss-logmanager-embedded-1.0.11.jar (deflated 10%)<br/>  adding: quarkus-app/lib/boot/io.github.crac.org-crac-0.1.3.jar (deflated 16%)<br/>  adding: quarkus-app/lib/boot/io.quarkus.quarkus-vertx-latebound-mdc-provider-2.16.0.Final.jar (deflated 29%)<br/>  adding: quarkus-app/lib/boot/org.jboss.logging.jboss-logging-3.5.0.Final.jar (deflated 9%)<br/>  adding: quarkus-app/lib/boot/io.quarkus.quarkus-development-mode-spi-2.16.0.Final.jar (deflated 14%)<br/>  adding: quarkus-app/lib/boot/org.graalvm.sdk.graal-sdk-22.3.0.jar (deflated 75%)<br/>  adding: quarkus-app/lib/boot/org.wildfly.common.wildfly-common-1.5.4.Final-format-001.jar (deflated 11%)<br/>  adding: quarkus-app/lib/boot/io.quarkus.quarkus-bootstrap-runner-2.16.0.Final.jar (deflated 9%)<br/>  adding: quarkus-app/lib/boot/io.smallrye.common.smallrye-common-io-1.13.2.jar (deflated 43%)<br/>  adding: quarkus-app/app/ (stored 0%)<br/>  adding: quarkus-app/app/jobs-service-infinispan-2.0.0-SNAPSHOT.jar (deflated 20%)<br/>  adding: quarkus-app/quarkus/ (stored 0%)<br/>  adding: quarkus-app/quarkus/transformed-bytecode.jar (deflated 17%)<br/>  adding: quarkus-app/quarkus/generated-bytecode.jar (deflated 6%)<br/>  adding: quarkus-app/quarkus/quarkus-application.dat (deflated 81%)<br/>  adding: quarkus-app/quarkus-run.jar (deflated 22%)<br/>  adding: quarkus-app/quarkus-app-dependencies.txt (deflated 83%)<br/>‘jobs-service-infinispan-quarkus-app.zip’ -> ‘/tmp/build/jobs-service-infinispan-all-in-one/jobs-service-infinispan-quarkus-app.zip’<br/>/tmp/jobs-service-infinispan-all-in-one/kogito-apps<br/>Updating settings file /tmp/jobs-service-postgresql-all-in-one/settings.xml<br/>enabling npm repository: https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/><settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"<br/>          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<br/>          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0<br/>                      https://maven.apache.org/xsd/settings-1.0.0.xsd"><br/><br/>  <mirrors><br/>        <mirror>      <id>mirror.default</id>      <url>https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/</url>      <mirrorOf>external:*</mirrorOf>    </mirror><br/>  </mirrors><br/><br/>  <proxies><br/>    <!-- ### configured http proxy ### --><br/>  </proxies><br/><br/>  <profiles><br/>    <!-- ### extra maven repositories ### --><br/><profile>  <id>internal-npm-registry</id>  <properties>  <npmRegistryURL>https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/</npmRegistryURL>  <yarnDownloadRoot>http://download.devel.redhat.com/rcm-guest/staging/rhba/dist/yarn/</yarnDownloadRoot>  <nodeDownloadRoot>http://download.devel.redhat.com/rcm-guest/staging/rhba/dist/node/</nodeDownloadRoot>  <npmDownloadRoot>http://download.devel.redhat.com/rcm-guest/staging/rhba/dist/npm/</npmDownloadRoot>  </properties></profile><br/><br/>    <profile><br/>      <id>kogito-images</id><br/>      <repositories><br/>        <repository><br/>          <id>jboss-public-repository-group</id><br/>          <name>JBoss Public Repository Group</name><br/>          <url>https://repository.jboss.org/nexus/content/groups/public/</url><br/>          <layout>default</layout><br/>          <releases><br/>            <enabled>true</enabled><br/>            <updatePolicy>never</updatePolicy><br/>          </releases><br/>          <snapshots><br/>            <enabled>true</enabled><br/>            <updatePolicy>always</updatePolicy><br/>          </snapshots><br/>        </repository><br/>        <!-- ### configured repositories ### --><br/>      </repositories><br/><br/>      <pluginRepositories><br/>        <pluginRepository><br/>          <id>jboss-public-repository-group</id><br/>          <name>JBoss Public Repository Group</name><br/>          <url>https://repository.jboss.org/nexus/content/groups/public/</url><br/>          <layout>default</layout><br/>          <releases><br/>            <enabled>true</enabled><br/>            <updatePolicy>never</updatePolicy><br/>          </releases><br/>          <snapshots><br/>            <enabled>true</enabled><br/>            <updatePolicy>always</updatePolicy><br/>          </snapshots><br/>        </pluginRepository><br/>        <!-- ### configured plugin repositories ### --><br/>      </pluginRepositories><br/>    </profile><br/>  </profiles><br/>  <activeProfiles><br/>    <!-- ### extra maven profile ### --><br/><activeProfile>internal-npm-registry</activeProfile><br/>    <activeProfile>kogito-images</activeProfile><br/>  </activeProfiles><br/></settings><br/>Copy current maven repo to maven context local repo /tmp/temp_maven/jobs-service-postgresql-all-in-one<br/>[32m2023-02-21 05:26:47,159 docker_builder.py:104        INFO  Docker: Removing intermediate container fd063535c85c[0m<br/>[32m2023-02-21 05:26:47,160 docker_builder.py:104        INFO  Docker: ---> fdf1b00feb98[0m<br/>[32m2023-02-21 05:26:47,160 docker_builder.py:104        INFO  Docker: Step 18/45 : LABEL             com.redhat.component="jboss-openjdk11-rhel8-container"             org.jboss.product="openjdk"             org.jboss.product.openjdk.version="11"             org.jboss.product.version="11"[0m<br/>[32m2023-02-21 05:26:47,160 docker_builder.py:104        INFO  Docker: [0m<br/>Using branch/tag main, checking out. Temporary build dir is /tmp/jobs-service-postgresql-all-in-one and target dist is /tmp/build/jobs-service-postgresql-all-in-one<br/>cloning kogito-apps with the following git command: git clone --single-branch --branch main --depth 1 https://githu [...]

2023-02-21 11:25 UTC, radtriste commented
jenkins retest this

2023-02-21 12:22 UTC, kie-ci1 commented
**PR job** `#541` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Build failures on those images:
- kogito-trusty-ui


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/541/display/redirect

**Test results:**
- PASSED: 248
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>kogito-trusty-ui</b></summary>
[INFO] Job Http Recipient - Parent ........................ SUCCESS [  0.528 s]<br/>[INFO] Job Http Recipient - Runtime ....................... SUCCESS [ 11.463 s]<br/>[INFO] Kogito Apps :: Jobs Service :: Common .............. SUCCESS [01:38 min]<br/>[INFO] Kogito Apps :: Jobs Service :: Infinispan .......... SUCCESS [ 33.909 s]<br/>[INFO] ------------------------------------------------------------------------<br/>[INFO] BUILD SUCCESS<br/>[INFO] ------------------------------------------------------------------------<br/>[INFO] Total time:  03:59 min<br/>[INFO] Finished at: 2023-02-21T06:40:10-05:00<br/>[INFO] ------------------------------------------------------------------------<br/>  adding: quarkus-app/ (stored 0%)<br/>  adding: quarkus-app/lib/ (stored 0%)<br/>  adding: quarkus-app/lib/main/ (stored 0%)<br/>  adding: quarkus-app/lib/main/org.kie.kogito.jobs-service-common-2.0.0-SNAPSHOT.jar (deflated 13%)<br/>  adding: quarkus-app/lib/main/org.kie.kogito.jobs-service-api-2.0.0-SNAPSHOT.jar (deflated 21%)<br/>  adding: quarkus-app/lib/main/org.eclipse.microprofile.openapi.microprofile-openapi-api-2.0.1.jar (deflated 27%)<br/>  adding: quarkus-app/lib/main/org.kie.kogito.kogito-addons-jobs-api-2.0.0-SNAPSHOT.jar (deflated 15%)<br/>  adding: quarkus-app/lib/main/io.cloudevents.cloudevents-api-2.3.0.jar (deflated 20%)<br/>  adding: quarkus-app/lib/main/org.kie.kogito.kogito-events-api-2.0.0-SNAPSHOT.jar (deflated 15%)<br/>  adding: quarkus-app/lib/main/org.kie.kogito.jobs-service-internal-api-2.0.0-SNAPSHOT.jar (deflated 16%)<br/>  adding: quarkus-app/lib/main/io.smallrye.reactive.mutiny-1.8.0.jar (deflated 10%)<br/>  adding: quarkus-app/lib/main/org.reactivestreams.reactive-streams-1.0.3.jar (deflated 18%)<br/>  adding: quarkus-app/lib/main/org.kie.kogito.job-http-recipient-2.0.0-SNAPSHOT.jar (deflated 18%)<br/>  adding: quarkus-app/lib/main/io.quarkus.quarkus-jackson-2.16.0.Final.jar (deflated 21%)<br/>  adding: quarkus-app/lib/main/com.fasterxml.jackson.datatype.jackson-datatype-jdk8-2.14.1.jar (deflated 18%)<br/>  adding: quarkus-app/lib/main/com.fasterxml.jackson.module.jackson-module-parameter-names-2.14.1.jar (deflated 31%)<br/>  adding: quarkus-app/lib/main/org.jboss.spec.javax.ws.rs.jboss-jaxrs-api_2.1_spec-2.0.1.Final.jar (deflated 13%)<br/>  adding: quarkus-app/lib/main/io.quarkus.quarkus-resteasy-reactive-2.16.0.Final.jar (deflated 18%)<br/>  adding: quarkus-app/lib/main/io.quarkus.quarkus-resteasy-reactive-common-2.16.0.Final.jar (deflated 24%)<br/>  adding: quarkus-app/lib/main/io.quarkus.resteasy.reactive.resteasy-reactive-common-2.16.0.Final.jar (deflated 10%)<br/>  adding: quarkus-app/lib/main/io.quarkus.resteasy.reactive.resteasy-reactive-common-types-2.16.0.Final.jar (deflated 48%)<br/>  adding: quarkus-app/lib/main/io.quarkus.resteasy.reactive.resteasy-reactive-vertx-2.16.0.Final.jar (deflated 14%)<br/>  adding: quarkus-app/lib/main/io.quarkus.resteasy.reactive.resteasy-reactive-2.16.0.Final.jar (deflated 12%)<br/>  adding: quarkus-app/lib/main/org.jboss.spec.javax.xml.bind.jboss-jaxb-api_2.3_spec-2.0.0.Final.jar (deflated 14%)<br/>  adding: quarkus-app/lib/main/io.quarkus.quarkus-vertx-http-2.16.0.Final.jar (deflated 11%)<br/>  adding: quarkus-app/lib/main/io.quarkus.quarkus-security-runtime-spi-2.16.0.Final.jar (deflated 31%)<br/>  adding: quarkus-app/lib/main/io.quarkus.quarkus-credentials-2.16.0.Final.jar (deflated 35%)<br/>  adding: quarkus-app/lib/main/io.quarkus.quarkus-vertx-http-dev-console-runtime-spi-2.16.0.Final.jar (deflated 20%)<br/>  adding: quarkus-app/lib/main/io.smallrye.reactive.smallrye-mutiny-vertx-web-2.30.1.jar (deflated 7%)<br/>  adding: quarkus-app/lib/main/io.smallrye.reactive.smallrye-mutiny-vertx-bridge-common-2.30.1.jar (deflated 22%)<br/>  adding: quarkus-app/lib/main/io.quarkus.quarkus-reactive-routes-2.16.0.Final.jar (deflated 14%)<br/>  adding: quarkus-app/lib/main/io.quarkus.security.quarkus-security-1.1.4.Final.jar (deflated 31%)<br/>  adding: quarkus-app/lib/main/jakarta.enterprise.jakarta.enterprise.cdi-api-2.0.2.jar (deflated 20%)<br/>  adding: quarkus-app/lib/main/jakarta.el.jakarta.el-api-3.0.3.jar (deflated 7%)<br/>  adding: quarkus-app/lib/main/jakarta.interceptor.jakarta.interceptor-api-1.2.5.jar (deflated 10%)<br/>  adding: quarkus-app/lib/main/io.quarkus.quarkus-vertx-2.16.0.Final.jar (deflated 13%)<br/>  adding: quarkus-app/lib/main/io.netty.netty-codec-haproxy-4.1.86.Final.jar (deflated 14%)<br/>  adding: quarkus-app/lib/main/io.netty.netty-buffer-4.1.86.Final.jar (deflated 6%)<br/>  adding: quarkus-app/lib/main/io.netty.netty-transport-4.1.86.Final.jar (deflated 11%)<br/>  adding: quarkus-app/lib/main/io.smallrye.common.smallrye-common-vertx-context-1.13.2.jar (deflated 26%)<br/>  adding: quarkus-app/lib/main/io.smallrye.common.smallrye-common-constraint-1.13.2.jar (deflated 17%)<br/>  adding: quarkus-app/lib/main/io.smallrye.reactive.smallrye-mutiny-vertx-core-2.30.1.jar (deflated 4%)<br/>  adding: quarkus-app/lib/main/io.smallrye.reactive.smallrye-mutiny-vertx-runtime-2.30.1.jar (deflated 12%)<br/>  adding: quarkus-app/lib/main/io.smallrye.reactive.vertx-mutiny-generator-2.30.1.jar (deflated 9%)<br/>  adding: quarkus-app/lib/main/io.vertx.vertx-codegen-4.3.7.jar (deflated 6%)<br/>  adding: quarkus-app/lib/main/io.smallrye.smallrye-fault-tolerance-vertx-5.6.0.jar (deflated 34%)<br/>  adding: quarkus-app/lib/main/io.quarkus.quarkus-mutiny-2.16.0.Final.jar (deflated 19%)<br/>  adding: quarkus-app/lib/main/io.quarkus.quarkus-smallrye-context-propagation-2.16.0.Final.jar (deflated 26%)<br/>  adding: quarkus-app/lib/main/io.smallrye.smallrye-context-propagation-1.2.2.jar (deflated 14%)<br/>  adding: quarkus-app/lib/main/io.smallrye.smallrye-context-propagation-api-1.2.2.jar (deflated 28%)<br/>  adding: quarkus-app/lib/main/io.smallrye.smallrye-context-propagation-storage-1.2.2.jar (deflated 30%)<br/>  adding: quarkus-app/lib/main/io.smallrye.reactive.mutiny-smallrye-context-propagation-1.8.0.jar (deflated 23%)<br/>  adding: quarkus-app/lib/main/io.smallrye.reactive.smallrye-mutiny-vertx-web-client-2.30.1.jar (deflated 8%)<br/>  adding: quarkus-app/lib/main/io.vertx.vertx-web-client-4.3.7.jar (deflated 8%)<br/>  adding: quarkus-app/lib/main/io.vertx.vertx-uri-template-4.3.7.jar (deflated 15%)<br/>  adding: quarkus-app/lib/main/io.vertx.vertx-web-common-4.3.7.jar (deflated 19%)<br/>  adding: quarkus-app/lib/main/io.vertx.vertx-auth-common-4.3.7.jar (deflated 10%)<br/>  adding: quarkus-app/lib/main/io.smallrye.reactive.smallrye-mutiny-vertx-auth-common-2.30.1.jar (deflated 10%)<br/>  adding: quarkus-app/lib/main/io.smallrye.reactive.smallrye-mutiny-vertx-web-common-2.30.1.jar (deflated 14%)<br/>  adding: quarkus-app/lib/main/io.smallrye.reactive.smallrye-mutiny-vertx-uri-template-2.30.1.jar (deflated 19%)<br/>  adding: quarkus-app/lib/main/org.yaml.snakeyaml-1.33.jar (deflated 12%)<br/>  adding: quarkus-app/lib/main/io.quarkus.quarkus-resteasy-reactive-jackson-2.16.0.Final.jar (deflated 21%)<br/>  adding: quarkus-app/lib/main/io.quarkus.quarkus-resteasy-reactive-jackson-common-2.16.0.Final.jar (deflated 31%)<br/>  adding: quarkus-app/lib/main/io.quarkus.resteasy.reactive.resteasy-reactive-jackson-2.16.0.Final.jar (deflated 27%)<br/>  adding: quarkus-app/lib/main/com.fasterxml.jackson.datatype.jackson-datatype-jsr310-2.14.1.jar (deflated 12%)<br/>  adding: quarkus-app/lib/main/com.fasterxml.jackson.core.jackson-annotations-2.14.1.jar (deflated 18%)<br/>  adding: quarkus-app/lib/main/com.fasterxml.jackson.core.jack [...]

2023-02-21 15:06 UTC, radtriste commented
jenkins retest this

2023-02-21 15:59 UTC, kie-ci1 commented
**PR job** `#542` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Build failures on those images:
- kogito-trusty-ui


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/542/display/redirect

**Test results:**
- PASSED: 248
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>kogito-trusty-ui</b></summary>
Downloading from mirror.default: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/jboss/jboss-parent/10/jboss-parent-10.pom<br/>Progress (1): 4.1/30 kB
Progress (1): 8.2/30 kB
Progress (1): 12/30 kB 
Progress (1): 16/30 kB
Progress (1): 20/30 kB
Progress (1): 25/30 kB
Progress (1): 29/30 kB
Progress (1): 30 kB   
                   
Downloaded from mirror.default: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/jboss/jboss-parent/10/jboss-parent-10.pom (30 kB at 1.2 MB/s)<br/>Downloading from mirror.default: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/jboss/narayana/jts/narayana-jts-integration/5.13.1.Final/narayana-jts-integration-5.13.1.Final.pom<br/>Progress (1): 4.1/9.1 kB
Progress (1): 8.2/9.1 kB
Progress (1): 9.1 kB    
                    
Downloaded from mirror.default: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/jboss/narayana/jts/narayana-jts-integration/5.13.1.Final/narayana-jts-integration-5.13.1.Final.pom (9.1 kB at 186 kB/s)<br/>Downloading from mirror.default: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/jboss/narayana/jts/narayana-jts-all/5.13.1.Final/narayana-jts-all-5.13.1.Final.pom<br/>Progress (1): 4.1/4.3 kB
Progress (1): 4.3 kB    
[INFO] <br/>[INFO] --- maven-source-plugin:3.0.1:test-jar-no-fork (attach-test-sources) @ persistence-commons-api ---<br/>[INFO] No sources in project. Archive not created.<br/>[INFO] <br/>[INFO] -----------< org.kie.kogito:persistence-commons-infinispan >------------<br/>[INFO] Building Kogito Apps :: Persistence Commons Infinispan 2.0.0-SNAPSHOT [5/16]<br/>[INFO] --------------------------------[ jar ]---------------------------------<br/>[32m2023-02-21 10:14:57,471 docker_builder.py:104        INFO  Docker: Installing: java-11-openjdk;1:11.0.18.0.10-2.el8_7;x86_64;ubi-8-appstream-rpms[0m<br/>Downloading from mirror.default: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/jboss/spec/javax/resource/jboss-connector-api_1.7_spec/1.0.0.Final/jboss-connector-api_1.7_spec-1.0.0.Final.pom<br/>Progress (1): 4.1/4.8 kB
Progress (1): 4.8 kB    
                    
Downloaded from mirror.default: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/jboss/spec/javax/resource/jboss-connector-api_1.7_spec/1.0.0.Final/jboss-connector-api_1.7_spec-1.0.0.Final.pom (4.8 kB at 35 kB/s)<br/>Downloading from mirror.default: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/jboss/jboss-parent/10/jboss-parent-10.pom<br/>Progress (1): 4.1/30 kB
Progress (1): 8.2/30 kB
Progress (1): 12/30 kB 
Progress (1): 16/30 kB
Progress (1): 20/30 kB
Progress (1): 25/30 kB
Progress (1): 29/30 kB
Progress (1): 30 kB   
                   
Downloaded from mirror.default: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/jboss/jboss-parent/10/jboss-parent-10.pom (30 kB at 614 kB/s)<br/>Downloading from mirror.default: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/jboss/narayana/jts/narayana-jts-integration/5.13.1.Final/narayana-jts-integration-5.13.1.Final.pom<br/>Progress (1): 4.1/9.1 kB
Progress (1): 8.2/9.1 kB
Progress (1): 9.1 kB    
                    
Downloaded from mirror.default: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/jboss/narayana/jts/narayana-jts-integration/5.13.1.Final/narayana-jts-integration-5.13.1.Final.pom (9.1 kB at 571 kB/s)<br/>Downloading from mirror.default: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/jboss/narayana/jts/narayana-jts-all/5.13.1.Final/narayana-jts-all-5.13.1.Final.pom<br/>Downloading from mirror.default: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/io/quarkus/quarkus-junit5-mockito-config/2.16.0.Final/quarkus-junit5-mockito-config-2.16.0.Final.pom<br/>Progress (1): 997 B
                   
Downloaded from mirror.default: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/io/quarkus/quarkus-junit5-mockito-config/2.16.0.Final/quarkus-junit5-mockito-config-2.16.0.Final.pom (997 B at 45 kB/s)<br/>                   
Downloaded from mirror.default: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/io/quarkus/quarkus-transaction-annotations/2.16.0.Final/quarkus-transaction-annotations-2.16.0.Final.pom (784 B at 5.8 kB/s)<br/>Downloading from mirror.default: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/io/quarkus/quarkus-transaction-annotations-parent/2.16.0.Final/quarkus-transaction-annotations-parent-2.16.0.Final.pom<br/>Progress (1): 738 B
                   
Downloaded from mirror.default: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/io/quarkus/quarkus-transaction-annotations-parent/2.16.0.Final/quarkus-transaction-annotations-parent-2.16.0.Final.pom (738 B at 3.4 kB/s)<br/>Downloading from mirror.default: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/net/bytebuddy/byte-buddy-agent/1.12.19/byte-buddy-agent-1.12.19.pom<br/>Progress (1): 4.1/10 kB
Progress (1): 8.2/10 kB
Progress (1): 10 kB    
                   
Downloaded from mirror.default: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/net/bytebuddy/byte-buddy-agent/1.12.19/byte-buddy-agent-1.12.19.pom (10 kB at 454 kB/s)<br/>Downloading from mirror.default: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/net/bytebuddy/byte-buddy-parent/1.12.19/byte-buddy-parent-1.12.19.pom<br/>Progress (1): 4.1/58 kB
Progress (1): 8.2/58 kB
Progress (1): 12/58 kB 
Progress (1): 16/58 kB
Progress (1): 20/58 kB
Progress (1): 25/58 kB
Progress (1): 29/58 kB
Progress (1): 33/58 kB
Progress (1): 37/58 kB
Progress (1): 41/58 kB
Progress (1): 45/58 kB
Progress (1): 49/58 kB
Progress (1): 53/58 kB
Progress (1): 57/58 kB
Progress (1): 58 kB   
                   
Downloaded from mirror.default: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/net/bytebuddy/byte-buddy-parent/1.12.19/byte-buddy-parent-1.12.19.pom (58 kB at 1.1 MB/s)<br/>Progress (1): 4.1/4.3 kB
Progress (1): 4.3 kB    
                    
Downloaded from mirror.default: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/jboss/narayana/jts/narayana-jts-all/5.13.1.Final/narayana-jts-all-5.13.1.Final.pom (4.3 kB at 194 kB/s)<br/>Downloading from mirror.default: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/io/agroal/agroal-api/1.16/agroal-api-1.16.pom<br/>Progress (1): 2.1 kB
            [...]

2023-02-22 08:43 UTC, nmirasch commented
jenkins retest this

2023-02-23 10:43 UTC, nmirasch commented
@spolti could you take a look on this PR, please? Thanks!

2023-02-23 12:44 UTC, spolti approved these changes

2023-02-23 12:45 UTC, merged