[KOGITO-9225] - Disable continuous testing on dev images
apache/incubator-kie-kogito-images pull request #1549
Opened 2023-05-25 18:50 UTC by spolti

Many thanks for submitting your Pull Request :heart:! 
See: https://issues.redhat.com/browse/KOGITO-9225

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [x] Pull Request title is properly formatted: `[KOGITO|RHPAM-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a testcase that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster
- [x] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- <b>(Re)run Jenkins tests</b>  
  Please add comment: <b>Jenkins [test|retest] this</b>

- <b>Prod tests</b>  
  Please add comment: <b>Jenkins (re)run [prod|Prod|PROD]</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

2023-05-25 18:57 UTC, ricardozanini approved these changes

2023-05-26 07:49 UTC, radtriste requested changes

2023-05-26 07:49 UTC, radtriste commented on modules/kogito-swf/devmode/runtime/added/run-app-devmode.sh
> +  -Dquarkus.test.continuous-testing=${QUARKUS_CONTINUOUS_TESTING:-disabled} \
Why not setting up the default directly into the module descriptor ? (and also that way we document this ;)

2023-05-26 07:49 UTC, radtriste commented on tests/features/kogito-swf-devmode.feature
> +      | QUARKUS_CONTINUOUS_TESTING | enabled                                  |
Please setup a different scenario

2023-05-26 07:49 UTC, radtriste commented on RELEASE_NOTES.md
> +- [KOGITO-9079](https://issues.redhat.com/browse/KOGITO-9079): Build the Quarkus app and the Maven repo zips during the build (Multi Stage builds)
Thanks for that one

2023-05-26 09:23 UTC, ricardozanini commented on modules/kogito-swf/devmode/runtime/added/run-app-devmode.sh
> +  -Dquarkus.test.continuous-testing=${QUARKUS_CONTINUOUS_TESTING:-disabled} \
I think this module descriptor won't add the env. Or it won't override it. I can't remember, but I remember cekit being a problem with it.

2023-05-26 13:53 UTC, radtriste commented on modules/kogito-swf/devmode/runtime/added/run-app-devmode.sh
> +  -Dquarkus.test.continuous-testing=${QUARKUS_CONTINUOUS_TESTING:-disabled} \
it will if you set the `value` field

2023-05-26 14:19 UTC, spolti commented on tests/features/kogito-swf-devmode.feature
> +      | QUARKUS_CONTINUOUS_TESTING | enabled                                  |
isn't better to have together, I understand that, one scenario for each thing is better for identifying the issue, but, it costs a few seconds on the tests.

2023-05-26 14:25 UTC, spolti commented on modules/kogito-swf/devmode/runtime/added/run-app-devmode.sh
> +  -Dquarkus.test.continuous-testing=${QUARKUS_CONTINUOUS_TESTING:-disabled} \
there is no need to set the value there, 

> Why not setting up the default directly into the module descriptor ? (and also that way we document this ;)
for safety :D
we can have both set.

2023-05-26 14:28 UTC, radtriste commented on tests/features/kogito-swf-devmode.feature
> +      | QUARKUS_CONTINUOUS_TESTING | enabled                                  |
well the longest testing is s2i-builder. And I can assure you that the time for testing the swf-builder or swf-devmode is really small compared to the s2i-builder ^^

2023-05-26 16:16 UTC, spolti commented on modules/kogito-swf/devmode/runtime/added/run-app-devmode.sh
> +  -Dquarkus.test.continuous-testing=${QUARKUS_CONTINUOUS_TESTING:-disabled} \
oh, I thought I have added it in the moule.yaml, but it seems that I completely forget.

2023-05-26 16:19 UTC, spolti commented on tests/features/kogito-swf-devmode.feature
> +      | QUARKUS_CONTINUOUS_TESTING | enabled                                  |
updated.

2023-05-26 16:20 UTC, spolti commented on modules/kogito-swf/devmode/runtime/added/run-app-devmode.sh
> +  -Dquarkus.test.continuous-testing=${QUARKUS_CONTINUOUS_TESTING:-disabled} \
added in the module.yaml as well.

2023-05-26 17:14 UTC, kie-ci1 commented
**PR job** `#677` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Build failures on those images:
- kogito-trusty-ui


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/677/display/redirect

**Test results:**
- PASSED: 258
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>kogito-trusty-ui</b></summary>
  adding: quarkus-app/lib/main/org.jboss.logging.commons-logging-jboss-logging-1.0.0.Final.jar (deflated 17%)<br/>  adding: quarkus-app/lib/main/io.smallrye.smallrye-fault-tolerance-context-propagation-5.6.0.jar (deflated 43%)<br/>  adding: quarkus-app/lib/main/io.smallrye.smallrye-fault-tolerance-mutiny-5.6.0.jar (deflated 33%)<br/>  adding: quarkus-app/lib/main/io.quarkus.quarkus-oidc-2.16.7.Final.jar (deflated 8%)<br/>  adding: quarkus-app/lib/main/io.quarkus.quarkus-security-2.16.7.Final.jar (deflated 17%)<br/>  adding: quarkus-app/lib/main/io.quarkus.quarkus-oidc-common-2.16.7.Final.jar (deflated 12%)<br/>  adding: quarkus-app/lib/main/io.quarkus.quarkus-smallrye-jwt-build-2.16.7.Final.jar (deflated 36%)<br/>  adding: quarkus-app/lib/main/io.smallrye.smallrye-jwt-build-3.6.0.jar (deflated 11%)<br/>  adding: quarkus-app/lib/main/io.smallrye.smallrye-jwt-3.6.0.jar (deflated 8%)<br/>  adding: quarkus-app/lib/main/org.eclipse.microprofile.jwt.microprofile-jwt-auth-api-1.2.jar (deflated 21%)<br/>  adding: quarkus-app/lib/main/org.bitbucket.b_c.jose4j-0.9.2.jar (deflated 9%)<br/>  adding: quarkus-app/lib/main/io.smallrye.smallrye-jwt-common-3.6.0.jar (deflated 12%)<br/>  adding: quarkus-app/lib/main/org.kie.kogito.kogito-timer-2.0.0-SNAPSHOT.jar (deflated 11%)<br/>  adding: quarkus-app/lib/main/org.slf4j.slf4j-api-1.7.36.jar (deflated 12%)<br/>  adding: quarkus-app/lib/main/io.quarkus.quarkus-smallrye-reactive-messaging-2.16.7.Final.jar (deflated 17%)<br/>  adding: quarkus-app/lib/main/io.quarkus.quarkus-arc-2.16.7.Final.jar (deflated 16%)<br/>  adding: quarkus-app/lib/main/io.quarkus.arc.arc-2.16.7.Final.jar (deflated 9%)<br/>  adding: quarkus-app/lib/main/org.eclipse.microprofile.context-propagation.microprofile-context-propagation-api-1.2.jar (deflated 22%)<br/>  adding: quarkus-app/lib/main/io.quarkus.quarkus-mutiny-reactive-streams-operators-2.16.7.Final.jar (deflated 36%)<br/>  adding: quarkus-app/lib/main/org.eclipse.microprofile.reactive-streams-operators.microprofile-reactive-streams-operators-api-1.0.1.jar (deflated 32%)<br/>  adding: quarkus-app/lib/main/org.eclipse.microprofile.reactive-streams-operators.microprofile-reactive-streams-operators-core-1.0.1.jar (deflated 21%)<br/>  adding: quarkus-app/lib/main/io.smallrye.reactive.mutiny-reactive-streams-operators-1.9.0.jar (deflated 16%)<br/>  adding: quarkus-app/lib/main/io.quarkus.quarkus-smallrye-reactive-messaging-kotlin-2.16.7.Final.jar (deflated 22%)<br/>  adding: quarkus-app/lib/main/io.vertx.vertx-web-4.3.7.jar (deflated 7%)<br/>  adding: quarkus-app/lib/main/io.vertx.vertx-bridge-common-4.3.7.jar (deflated 18%)<br/>  adding: quarkus-app/lib/main/io.smallrye.reactive.smallrye-reactive-messaging-api-3.22.1.jar (deflated 19%)<br/>  adding: quarkus-app/lib/main/io.smallrye.reactive.smallrye-reactive-messaging-provider-3.22.1.jar (deflated 8%)<br/>  adding: quarkus-app/lib/main/io.smallrye.common.smallrye-common-annotation-1.13.2.jar (deflated 33%)<br/>  adding: quarkus-app/lib/main/io.smallrye.reactive.smallrye-reactive-messaging-health-3.22.1.jar (deflated 29%)<br/>  adding: quarkus-app/lib/main/org.eclipse.microprofile.health.microprofile-health-api-3.1.jar (deflated 20%)<br/>  adding: quarkus-app/lib/main/jakarta.annotation.jakarta.annotation-api-1.3.5.jar (deflated 12%)<br/>  adding: quarkus-app/lib/main/org.apache.commons.commons-lang3-3.12.0.jar (deflated 9%)<br/>  adding: quarkus-app/lib/main/io.quarkus.quarkus-infinispan-client-2.16.7.Final.jar (deflated 15%)<br/>  adding: quarkus-app/lib/main/io.quarkus.quarkus-core-2.16.7.Final.jar (deflated 12%)<br/>  adding: quarkus-app/lib/main/io.smallrye.config.smallrye-config-2.13.3.jar (deflated 10%)<br/>  adding: quarkus-app/lib/main/io.smallrye.config.smallrye-config-core-2.13.3.jar (deflated 8%)<br/>  adding: quarkus-app/lib/main/io.smallrye.common.smallrye-common-expression-1.13.2.jar (deflated 14%)<br/>  adding: quarkus-app/lib/main/io.smallrye.common.smallrye-common-function-1.13.2.jar (deflated 18%)<br/>  adding: quarkus-app/lib/main/io.smallrye.common.smallrye-common-classloader-1.13.2.jar (deflated 23%)<br/>  adding: quarkus-app/lib/main/io.smallrye.config.smallrye-config-common-2.13.3.jar (deflated 19%)<br/>  adding: quarkus-app/lib/main/org.jboss.logging.jboss-logging-annotations-2.2.1.Final.jar (deflated 24%)<br/>  adding: quarkus-app/lib/main/org.jboss.threads.jboss-threads-3.4.3.Final.jar (deflated 11%)<br/>  adding: quarkus-app/lib/main/io.quarkus.quarkus-fs-util-0.0.9.jar (deflated 14%)<br/>  adding: quarkus-app/lib/main/io.quarkus.quarkus-caffeine-2.16.7.Final.jar (deflated 26%)<br/>  adding: quarkus-app/lib/main/com.github.ben-manes.caffeine.caffeine-3.1.1.jar (deflated 25%)<br/>  adding: quarkus-app/lib/main/com.google.errorprone.error_prone_annotations-2.17.0.jar (deflated 32%)<br/>  adding: quarkus-app/lib/main/io.quarkus.quarkus-netty-2.16.7.Final.jar (deflated 18%)<br/>  adding: quarkus-app/lib/main/io.netty.netty-codec-4.1.86.Final.jar (deflated 10%)<br/>  adding: quarkus-app/lib/main/io.netty.netty-codec-http-4.1.86.Final.jar (deflated 10%)<br/>  adding: quarkus-app/lib/main/io.netty.netty-codec-http2-4.1.86.Final.jar (deflated 11%)<br/>  adding: quarkus-app/lib/main/io.netty.netty-handler-4.1.86.Final.jar (deflated 9%)<br/>  adding: quarkus-app/lib/main/io.netty.netty-transport-native-unix-common-4.1.86.Final.jar (deflated 13%)<br/>  adding: quarkus-app/lib/main/com.aayushatharva.brotli4j.brotli4j-1.8.0.jar (deflated 14%)<br/>  adding: quarkus-app/lib/main/com.aayushatharva.brotli4j.native-linux-x86_64-1.8.0.jar (deflated 1%)<br/>  adding: quarkus-app/lib/main/io.quarkus.quarkus-jsonp-2.16.7.Final.jar (deflated 31%)<br/>  adding: quarkus-app/lib/main/org.glassfish.jakarta.json-1.1.6.jar (deflated 9%)<br/>  adding: quarkus-app/lib/main/io.quarkus.quarkus-elytron-security-common-2.16.7.Final.jar (deflated 30%)<br/>  adding: quarkus-app/lib/main/org.wildfly.security.wildfly-elytron-credential-1.20.3.Final.jar (deflated 12%)<br/>  adding: quarkus-app/lib/main/org.wildfly.security.wildfly-elytron-asn1-1.20.3.Final.jar (deflated 10%)<br/>  adding: quarkus-app/lib/main/org.wildfly.security.wildfly-elytron-keystore-1.20.3.Final.jar (deflated 11%)<br/>  adding: quarkus-app/lib/main/org.wildfly.security.wildfly-elytron-x500-cert-1.20.3.Final.jar (deflated 12%)<br/>  adding: quarkus-app/lib/main/org.wildfly.security.wildfly-elytron-x500-cert-util-1.20.3.Final.jar (deflated 26%)<br/>  adding: quarkus-app/lib/main/org.apache.sshd.sshd-common-2.9.2.jar (deflated 9%)<br/>  adding: quarkus-app/lib/main/org.wildfly.security.wildfly-elytron-provider-util-1.20.3.Final.jar (deflated 18%)<br/>  adding: quarkus-app/lib/main/org.wildfly.security.wildfly-elytron-x500-1.20.3.Final.jar (deflated 15%)<br/>  adding: quarkus-app/lib/main/org.wildfly.security.wildfly-elytron-password-impl-1.20.3.Final.jar (deflated 7%)<br/>  adding: quarkus-app/lib/main/org.wildfly.security.wildfly-elytron-sasl-plain-1.20.3.Final.jar (deflated 21%)<br/>  adding: quarkus-app/lib/main/org.wildfly.security.wildfly-elytron-auth-server-1.20.3.Final.jar (deflated 11%)<br/>  adding: quarkus-app/lib/main/org.wildfly.security.wildfly-elytron-auth-1.20.3.Final.jar (deflated 20%)<br/>  adding: quarkus-app/lib/main/org.wildfly.security.wildfly-elytron-base-1.20.3.Final.jar (deflated 16%)<br/>  adding: quarkus-app/lib/main/org.wildfly.security.wildfly-elytron-permission-1.20.3.Final.jar (deflated 14%)<br/>  adding: quarkus-app/lib/main/org.wildfly.security.wildfly-elytron-sasl-1.20.3.Final.jar (d [...]

2023-05-26 18:24 UTC, spolti commented
Jenkmins retest this

2023-05-26 18:24 UTC, spolti commented
Jenkins retest this

2023-05-26 19:13 UTC, kie-ci1 commented
**PR job** `#678` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Build failures on those images:
- kogito-task-console


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/678/display/redirect

**Test results:**
- PASSED: 257
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>kogito-task-console</b></summary>
[32m2023-05-26 14:36:06,372 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/org/jboss/logging/jboss-logging-annotations/2.2.1.Final/jboss-logging-annotations-2.2.1.Final.jar[0m<br/>[32m2023-05-26 14:36:06,372 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/org/jboss/threads/jboss-threads/3.4.3.Final/jboss-threads-3.4.3.Final.jar[0m<br/>[32m2023-05-26 14:36:06,372 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar[0m<br/>[32m2023-05-26 14:36:06,372 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/org/jboss/slf4j/slf4j-jboss-logmanager/1.2.0.Final/slf4j-jboss-logmanager-1.2.0.Final.jar[0m<br/>[32m2023-05-26 14:36:06,372 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/org/graalvm/sdk/graal-sdk/22.3.0/graal-sdk-22.3.0.jar[0m<br/>[32m2023-05-26 14:36:06,372 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/org/wildfly/common/wildfly-common/1.5.4.Final-format-001/wildfly-common-1.5.4.Final-format-001.jar[0m<br/>[32m2023-05-26 14:36:06,372 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/io/quarkus/quarkus-bootstrap-runner/2.16.7.Final/quarkus-bootstrap-runner-2.16.7.Final.jar[0m<br/>[32m2023-05-26 14:36:06,372 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/io/quarkus/quarkus-fs-util/0.0.9/quarkus-fs-util-0.0.9.jar[0m<br/>[32m2023-05-26 14:36:06,372 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/io/quarkus/quarkus-vertx-http/2.16.7.Final/quarkus-vertx-http-2.16.7.Final.jar[0m<br/>[32m2023-05-26 14:36:06,372 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/io/quarkus/quarkus-security-runtime-spi/2.16.7.Final/quarkus-security-runtime-spi-2.16.7.Final.jar[0m<br/>[32m2023-05-26 14:36:06,372 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/io/quarkus/quarkus-credentials/2.16.7.Final/quarkus-credentials-2.16.7.Final.jar[0m<br/>[32m2023-05-26 14:36:06,372 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/io/quarkus/quarkus-vertx-http-dev-console-runtime-spi/2.16.7.Final/quarkus-vertx-http-dev-console-runtime-spi-2.16.7.Final.jar[0m<br/>[32m2023-05-26 14:36:06,373 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/io/smallrye/reactive/smallrye-mutiny-vertx-web/2.30.1/smallrye-mutiny-vertx-web-2.30.1.jar[0m<br/>[32m2023-05-26 14:36:06,373 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/io/smallrye/reactive/smallrye-mutiny-vertx-bridge-common/2.30.1/smallrye-mutiny-vertx-bridge-common-2.30.1.jar[0m<br/>[32m2023-05-26 14:36:06,373 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/io/vertx/vertx-web/4.3.7/vertx-web-4.3.7.jar[0m<br/>[32m2023-05-26 14:36:06,373 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/io/vertx/vertx-web-common/4.3.7/vertx-web-common-4.3.7.jar[0m<br/>[32m2023-05-26 14:36:06,373 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/io/vertx/vertx-auth-common/4.3.7/vertx-auth-common-4.3.7.jar[0m<br/>[32m2023-05-26 14:36:06,373 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/io/vertx/vertx-bridge-common/4.3.7/vertx-bridge-common-4.3.7.jar[0m<br/>[32m2023-05-26 14:36:06,373 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/io/github/crac/org-crac/0.1.3/org-crac-0.1.3.jar[0m<br/>[32m2023-05-26 14:36:06,373 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/io/quarkus/quarkus-jsonp/2.16.7.Final/quarkus-jsonp-2.16.7.Final.jar[0m<br/>[32m2023-05-26 14:36:06,373 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/org/glassfish/jakarta.json/1.1.6/jakarta.json-1.1.6.jar[0m<br/>[32m2023-05-26 14:36:06,373 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/org/kie/kogito/kogito-addons-quarkus-jobs-service-embedded/2.0.0-SNAPSHOT/kogito-addons-quarkus-jobs-service-embedded-2.0.0-SNAPSHOT.jar[0m<br/>[32m2023-05-26 14:36:06,373 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/io/quarkus/quarkus-resteasy-mutiny/2.16.7.Final/quarkus-resteasy-mutiny-2.16.7.Final.jar[0m<br/>[32m2023-05-26 14:36:06,373 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/io/quarkus/quarkus-resteasy-mutiny-common/2.16.7.Final/quarkus-resteasy-mutiny-common-2.16.7.Final.jar[0m<br/>[32m2023-05-26 14:36:06,374 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/io/quarkus/http/quarkus-http-core/4.2.1/quarkus-http-core-4.2.1.jar[0m<br/>[32m2023-05-26 14:36:06,374 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/io/quarkus/http/quarkus-http-http-core/4.2.1/quarkus-http-http-core-4.2.1.jar[0m<br/>[32m2023-05-26 14:36:06,374 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/io/netty/netty-buffer/4.1.86.Final/netty-buffer-4.1.86.Final.jar[0m<br/>[32m2023-05-26 14:36:06,374 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/io/netty/netty-codec-http/4.1.86.Final/netty-codec-http-4.1.86.Final.jar[0m<br/>[32m2023-05-26 14:36:06,374 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/io/netty/netty-common/4.1.86.Final/netty-common-4.1.86.Final.jar[0m<br/>[32m2023-05-26 14:36:06,374 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/io/netty/netty-transport/4.1.86.Final/netty-transport-4.1.86.Final.jar[0m<br/>[32m2023-05-26 14:36:06,374 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/io/netty/netty-codec/4.1.86.Final/netty-codec-4.1.86.Final.jar[0m<br/>[32m2023-05-26 14:36:06,374 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/io/netty/netty-handler/4.1.86.Final/netty-handler-4.1.86.Final.jar[0m<br/>[32m2023-05-26 14:36:06,374 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/io/netty/netty-transport-native-unix-common/4.1.86.Final/netty-transport-native-unix-common-4.1.86.Final.jar[0m<br/>[32m2023-05-26 14:36:06,375 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/org/kie/kogito/jobs-service-inmemory/2.0.0-SNAPSHOT/jobs-service-inmemory-2.0.0-SNAPSHOT.jar[0m<br/>[32m2023-05-26 14:36:06,375 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/org/kie/kogito/jobs-service-postgresql/2.0.0-SNAPSHOT/jobs-service-postgresql-2.0.0-SNAPSHOT.jar[0m<br/>[32m2023-05-26 14:36:06,375 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/org/kie/kogito/jobs-service-common/2.0.0-SNAPSHOT/jobs-service-common-2.0.0-SNAPSHOT.jar[0m<br/>[32m2023-05-26 14:36:06,375 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/org/kie/kogito/jobs-service-internal-api/2.0.0-SNAPSHOT/jobs-service-internal-api-2.0.0-SNAPSHOT.jar[0m<br/>[32m2023-05-26 14:36:06,375 docker_builder.py:104        INFO  Docker: [DEBUG]  /home/kogito/.m2/repository/org/kie/kogito/job-http-recipient/2.0.0-SNAPSHOT/job-http-recipient-2.0.0-SNAPSHOT.jar[0m<br/>[32m20 [...]

2023-05-26 19:19 UTC, spolti commented
Jenkins retest this

2023-05-26 21:34 UTC, radtriste commented on modules/kogito-swf/devmode/runtime/module.yaml
> +    example: "disabled"
Please set as default value here

2023-05-26 21:35 UTC, radtriste commented on tests/features/kogito-swf-devmode.feature
> +      | QUARKUS_CONTINUOUS_TESTING | enabled                                  |
Please remove that env var from that test

2023-05-26 23:16 UTC, kie-ci1 commented
**PR job** `#682` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/682/display/redirect

**Test results:**
- PASSED: 266
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/682/testReport/features.image.kogito-swf-devmode/Serverless Workflow devmode images/Verify_if_container_starts_correctly_when_QUARKUS_EXTENSIONS_env_is_used/">features.image.kogito-swf-devmode.Serverless Workflow devmode images.Verify if container starts correctly when QUARKUS_EXTENSIONS env is used</a></summary>
Message '-Dquarkus.test.continuous-testing=enabled' was not found in the logs
</details>

2023-05-27 16:16 UTC, ricardozanini commented on modules/kogito-swf/devmode/runtime/added/run-app-devmode.sh
> +  -Dquarkus.test.continuous-testing=${QUARKUS_CONTINUOUS_TESTING:-disabled} \
> it will if you set the value field

Never worked for me.

2023-05-29 15:08 UTC, kie-ci1 commented
**PR job** `#683` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/683/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Prepare offline kogito-examples)<br/>Stage "Prepare offline kogito-examples" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build & Test Images)<br/>Stage "Build & Test Images" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-images/workspaces<br/>[Pipeline] sh<br/>++ docker ps -a -q<br/>+ docker rm -f<br/>"docker rm" requires at least 1 argument.<br/>See 'docker rm --help'.<br/><br/>Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]<br/><br/>Remove one or more containers<br/>+ date<br/>Mon May 29 11:08:18 EDT 2023<br/>[Pipeline] sh<br/>++ docker images -q<br/>+ docker rmi -f<br/>"docker rmi" requires at least 1 argument.<br/>See 'docker rmi --help'.<br/><br/>Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]<br/><br/>Remove one or more images<br/>+ date<br/>Mon May 29 11:08:18 EDT 2023<br/>[Pipeline] sh<br/>+ rm -rf /home/jenkins/.cekit/cache<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>+ wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/683/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

2023-05-31 13:13 UTC, radtriste approved these changes

2023-05-31 20:58 UTC, kie-ci1 commented
**PR job** `#708` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/708/display/redirect

**Test results:**
- PASSED: 267
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-images/708/testReport/features.image.trusty.kogito-trusty-redis.Kogito-trusty redis feature//verify_if_all_parameters_are_correctly_set/">features.image.trusty.kogito-trusty-redis.Kogito-trusty redis feature..verify if all parameters are correctly set</a></summary>
500 Server Error for http+docker://localhost/v1.22/containers/5077f4683c43c7794c4efdfdb2bded28d77aa04a1ee19cccc41a372ca00d8b00/start: Internal Server Error ("b'failed to create task for container: failed to create shim task: failed to start io pipe copy: unable to copy pipes: containerd-shim: opening w/o fifo "/var/run/docker/containerd/5077f4683c43c7794c4efdfdb2bded28d77aa04a1ee19cccc41a372ca00d8b00/5077f4683c43c7794c4efdfdb2bded28d77aa04a1ee19cccc41a372ca00d8b00-stdout" failed: context deadline exceeded'")
</details>

2023-05-31 21:07 UTC, spolti commented
Jenkins retest this

2023-06-01 00:19 UTC, merged