[KOGITO-1919] - Allow user to specify the artifact and group id when …
apache/incubator-kie-kogito-images pull request #164
Opened 2020-05-19 07:53 UTC by vaibhavjainwiz

…doing builds from archetype
Jira Issue : https://issues.redhat.com/browse/KOGITO-1919

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

2020-05-19 08:14 UTC, sutaakar commented on modules/kogito-s2i-core/module.yaml
> +  - name: S2I_GROUP_ID
Wouldn't it have more sense to use technology neutral name, like `PROJECT_GROUP_ID`?
In the future we will most likely support other build mechanisms so this name could be misleading for users.

2020-05-19 08:14 UTC, sutaakar commented on modules/kogito-s2i-core/module.yaml
> +  - name: S2I_ARTIFACT_ID
Same as above

2020-05-19 08:23 UTC, sutaakar commented on modules/kogito-s2i-core/module.yaml
> +    description: ^  Indicates the unique base name of the primary artifact being generated.  This should not be overridden by end users.
"This should not be overridden by end users" - What do you mean by that note? It is not clear for me.

2020-05-19 08:25 UTC, sutaakar commented on modules/kogito-s2i-core/tests/bats/s2i-core.bats
> +    S2I_GROUP_ID="com.project"
Can you please remove the new properties from this test and check that default values are used in here?
You can specify custom values in another new test and check there that the new values are applied.

2020-05-19 08:26 UTC, sutaakar commented on tests/features/kogito-quarkus-ubi8-s2i.feature
> +    Given s2i build /tmp/kogito-examples from dmn-quarkus-example using master and runtime-image quay.io/kiegroup/kogito-quarkus-jvm-ubi8:latest --env MAVEN_MIRROR_URL=http://192.168.130.1:8080/repos
```suggestion
    Given s2i build /tmp/kogito-examples from dmn-quarkus-example using master and runtime-image quay.io/kiegroup/kogito-quarkus-jvm-ubi8:latest
```

2020-05-19 11:35 UTC, vaibhavjainwiz commented on modules/kogito-s2i-core/module.yaml
> +  - name: S2I_GROUP_ID
rename S2I_GROUP_ID to PROJECT_GROUP_ID

2020-05-19 11:35 UTC, vaibhavjainwiz commented on modules/kogito-s2i-core/module.yaml
> +  - name: S2I_ARTIFACT_ID
rename S2I_ARTIFACT_ID to PROJECT_ARTIFACT_ID

2020-05-19 11:36 UTC, vaibhavjainwiz commented on modules/kogito-s2i-core/module.yaml
> +    description: ^  Indicates the unique base name of the primary artifact being generated.  This should not be overridden by end users.
update description

2020-05-19 11:36 UTC, vaibhavjainwiz commented on tests/features/kogito-quarkus-ubi8-s2i.feature
> +    Given s2i build /tmp/kogito-examples from dmn-quarkus-example using master and runtime-image quay.io/kiegroup/kogito-quarkus-jvm-ubi8:latest --env MAVEN_MIRROR_URL=http://192.168.130.1:8080/repos
done

2020-05-19 11:37 UTC, vaibhavjainwiz commented on modules/kogito-s2i-core/tests/bats/s2i-core.bats
> +    S2I_GROUP_ID="com.project"
These variables are needed and are supplied in module.yaml when used in regular build

2020-05-19 12:35 UTC, sutaakar approved these changes

2020-05-19 14:51 UTC, spolti requested changes

2020-05-19 14:51 UTC, spolti commented on README.md
> +**PROJECT_ARTIFACT_ID**.
remove new line.

2020-05-19 14:51 UTC, spolti commented on modules/kogito-s2i-core/tests/bats/s2i-core.bats
> +    #PROJECT_GROUP_ID & PROJECT_ARTIFACT_ID are needed and are supplied in module.yaml when used in regular build
we might want to add some verification in the script that makes sure theese envs will nt be empty.
maybe remove its value from module and set a default value on the script and refer it on the env description.

2020-05-19 14:51 UTC, spolti commented on modules/kogito-s2i-core/module.yaml
> +
maybe it is useful also to set the version. just expose another env and default to 1.0-SNAPSHOT

2020-05-20 10:17 UTC, radtriste approved these changes
looks good after comments from Filippe are solved

2020-05-20 10:30 UTC, vaibhavjainwiz commented on README.md
> +**PROJECT_ARTIFACT_ID**.
done

2020-05-20 10:46 UTC, vaibhavjainwiz commented on modules/kogito-s2i-core/module.yaml
> +
added in env variable PROJECT_VERSION

2020-05-20 14:06 UTC, spolti requested changes

2020-05-20 14:06 UTC, spolti commented on README.md
> -Upon build, these assets will be copied to a generated maven project and built with Maven to produce a runnable binary. Default
why did you remove it from README?

2020-05-20 15:41 UTC, radtriste commented on tests/features/kogito-quarkus-ubi8-s2i.feature
> +      | PROJECT_ARTIFACT_ID | myproject      |
no `PROJECT_VERSION` here ?

2020-05-20 16:02 UTC, spolti commented on tests/features/kogito-quarkus-ubi8-s2i.feature
> +      | PROJECT_ARTIFACT_ID | myproject      |
+1

2020-05-21 04:52 UTC, vaibhavjainwiz commented on README.md
> -Upon build, these assets will be copied to a generated maven project and built with Maven to produce a runnable binary. Default
because in your previous commet you asked to **remove new line**.

2020-05-21 05:18 UTC, vaibhavjainwiz commented on tests/features/kogito-quarkus-ubi8-s2i.feature
> +      | PROJECT_ARTIFACT_ID | myproject      |
miss to update feature test with new version property. Update now

2020-05-21 05:26 UTC, spolti commented on README.md
> -Upon build, these assets will be copied to a generated maven project and built with Maven to produce a runnable binary. Default
Yeah, you have added a new line breaking a phrase in the middle. Like
This.
 I asked to remove that new line, not the information about your changes.

2020-05-21 11:18 UTC, vaibhavjainwiz commented on README.md
> -Upon build, these assets will be copied to a generated maven project and built with Maven to produce a runnable binary. Default
I had done the changes please verify

2020-05-22 14:33 UTC, spolti approved these changes

2020-05-22 14:35 UTC, merged