[KOGITO-2435] Migrate nightly pipelines to RHBA
apache/incubator-kie-kogito-images pull request #182
Opened 2020-06-15 16:41 UTC by radtriste

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

2020-06-19 15:26 UTC, radtriste commented on Jenkinsfile.deploy
>          string(name: 'BUILD_BRANCH_NAME', defaultValue: 'master', description: 'Which branch to build ? Set if you are not on a multibranch pipeline.')
Kept the old `BUILD_BRANCH_NAME` for backward compatiblity for already running pipeline on master

2020-06-19 15:26 UTC, radtriste commented on Jenkinsfile.deploy
> +                    checkout(githubscm.resolveRepository("kogito-images", params.GIT_AUTHOR, params.BUILD_BRANCH_NAME, false))
I removed the check for `BRANCH_NAME` env as this pipeline is not meant to be run on a multibranch pipeline

2020-06-19 15:26 UTC, radtriste commented on modules/kogito-epel/7/configure
> +rpm -i https://download.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
I corrected this because Fedora servers are currently having problems and `dl.fedoraproject.org` does not redirect whereas `download.fedoraproject.org` does ...

2020-06-19 18:22 UTC, sutaakar approved these changes

2020-06-22 12:07 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +
The images are built using docker and are available in docker's directory structure, don't you think we should clean images in deploy file in docker?.For promote we can use podman as only tagging and push is done,

2020-06-22 12:18 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +                    checkout(githubscm.resolveRepository("kogito-images", params.GIT_AUTHOR, params.BUILD_BRANCH_NAME, false))
Can't we use `githubscm.checkoutIfExists` method here?

2020-06-22 19:28 UTC, spolti commented
shouldn't the job be triggered?

2020-06-22 19:43 UTC, Kaitou786 commented
> shouldn't the job be triggered?

@spolti which job are you talking about?

2020-06-22 19:46 UTC, spolti commented
> > shouldn't the job be triggered?
> 
> @spolti which job are you talking about?

nevermind hahaha
it is the nightly job.

2020-06-24 17:38 UTC, spolti requested changes

2020-06-24 17:38 UTC, spolti commented on Jenkinsfile.deploy
> +
+1

2020-06-24 17:38 UTC, spolti commented on Jenkinsfile.deploy
> +    sh "set +x && docker login -u jenkins -p \$(oc whoami -t) --tls-verify=false ${OPENSHIFT_REGISTRY}"
use envs to hide the usernames

2020-06-24 17:38 UTC, spolti commented on Jenkinsfile.promote
> +    sh "podman rm -f \$(podman ps -a -q) || date"
docker

2020-06-24 17:38 UTC, spolti commented on Jenkinsfile.promote
> +        sh "podman pull ${getOldImageFullTag(imageName)}"
same for other occurrencies

2020-06-24 17:54 UTC, Kaitou786 commented on Jenkinsfile.promote
> +        sh "podman pull ${getOldImageFullTag(imageName)}"
I think we can use podman here, as images are available in the openshift registry, and in Jenkinsfile.promote we are just pulling, tagging and pushing the already built and tested images which can be done by podman

2020-06-30 13:08 UTC, vaibhavjainwiz commented
Jenkins, restest this please

2020-06-30 14:11 UTC, radtriste commented on Jenkinsfile.deploy
> +                    checkout(githubscm.resolveRepository("kogito-images", params.GIT_AUTHOR, params.BUILD_BRANCH_NAME, false))
we are not in a PR here, so no merge to perform. Just using the default behavior of `githubscm.checkoutIfExists` : https://github.com/kiegroup/jenkins-pipeline-shared-libraries/blob/7fd44e04c5d5c39f1d5cb752823f9cb2ab343cee/vars/githubscm.groovy#L30

2020-06-30 14:12 UTC, radtriste commented on Jenkinsfile.deploy
> +
ok will set back `docker`

2020-06-30 14:14 UTC, radtriste commented on Jenkinsfile.deploy
> +    sh "set +x && docker login -u jenkins -p \$(oc whoami -t) --tls-verify=false ${OPENSHIFT_REGISTRY}"
username is not important here, it could be anything, only the token is important
See https://docs.openshift.com/container-platform/4.4/registry/accessing-the-registry.html#registry-accessing-directly_accessing-the-registry

2020-06-30 14:15 UTC, radtriste commented on Jenkinsfile.promote
> +    sh "podman rm -f \$(podman ps -a -q) || date"
nope, here we are only using podman. no docker involved

2020-06-30 14:15 UTC, radtriste commented on Jenkinsfile.promote
> +        sh "podman pull ${getOldImageFullTag(imageName)}"
yep

2020-06-30 14:18 UTC, radtriste commented on Jenkinsfile.deploy
> +    sh "set +x && docker login -u jenkins -p \$(oc whoami -t) --tls-verify=false ${OPENSHIFT_REGISTRY}"
added a comment

2020-06-30 14:19 UTC, radtriste commented on Jenkinsfile.deploy
> +
updated

2020-06-30 18:21 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +    }
We can remove this, as 3.6.3 is default right now and after https://github.com/kiegroup/kie-jenkins-scripts/pull/766 Java 11 will also be default

2020-07-01 07:13 UTC, radtriste commented on Jenkinsfile.deploy
> +    }
removed

2020-07-01 11:54 UTC, Kaitou786 commented
Jenkins, retest this please

2020-07-01 11:59 UTC, Kaitou786 commented on Jenkinsfile.promote
>          }
We are using `withDockerRegistry` how it is going to authenticate with podman?, we can't have `podman-docker` or `symblink` of docker pointing at podman as in this image we have docker installed

2020-07-02 07:48 UTC, radtriste commented on Jenkinsfile.promote
>          }
Using now `loginContainerRegistry` before tagging/pushing

2020-07-02 14:21 UTC, radtriste commented
similar changes as for operator: https://github.com/kiegroup/kogito-cloud-operator/pull/386#issuecomment-653014349

2020-07-02 16:17 UTC, sutaakar commented on Jenkinsfile.deploy
> +    sh "set +x && docker login -u anything -p \$(oc whoami -t) ${env.OPENSHIFT_REGISTRY}"
Shouldn't be podman used here?

2020-07-02 16:20 UTC, sutaakar approved these changes

2020-07-02 16:25 UTC, radtriste commented on Jenkinsfile.deploy
> +    sh "set +x && docker login -u anything -p \$(oc whoami -t) ${env.OPENSHIFT_REGISTRY}"
not in the deploy. As Cekit is using docker, we should let the whole file using docker IMO

2020-07-02 16:54 UTC, sutaakar commented on Jenkinsfile.deploy
> +    sh "set +x && docker login -u anything -p \$(oc whoami -t) ${env.OPENSHIFT_REGISTRY}"
ok

2020-07-03 04:17 UTC, Kaitou786 approved these changes

2020-07-03 14:34 UTC, spolti approved these changes

2020-07-03 14:35 UTC, merged