Shpathak
apache/incubator-kie-kogito-images pull request #183
Opened 2020-06-16 16:07 UTC by shashankcuber

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

2020-06-17 07:25 UTC, radtriste requested changes

2020-06-17 07:25 UTC, radtriste commented on Jenkinsfile.deploy
> +   	string(name: 'version', defaultValue: '', description: 'To check version and update it')
please use uppercase for parameters

2020-06-17 07:25 UTC, radtriste commented on Jenkinsfile.deploy
> +	stage('update version')
Please change indentation

2020-06-17 07:25 UTC, radtriste commented on Jenkinsfile.deploy
> +	stage('update version')
```suggestion
	stage('Update version')
```

2020-06-17 07:25 UTC, radtriste commented on Jenkinsfile.deploy
> +	{
Use `when` functionality of pipelines to execute or not this stage

2020-06-17 07:25 UTC, radtriste commented on Jenkinsfile.deploy
> +					updateVersion(${params.version})
`updateVersion` is one command, so no need to create a method for that, just put the command directly here

2020-06-17 07:25 UTC, radtriste commented on Jenkinsfile.deploy
> +	stage('Release for PR(Shared Lib)')
`Create PR`

2020-06-17 07:25 UTC, radtriste commented on Jenkinsfile.deploy
> +				if(params.release!=false)
Same here use the `when` functionality from pipeline

2020-06-17 07:25 UTC, radtriste commented on Jenkinsfile.deploy
> +	string(name: 'branch_name', defaultValue: '', description: 'To specify the branch name')
Use `BUILD_BRANCH_NAME` parameter already existing

2020-06-17 07:25 UTC, radtriste commented on Jenkinsfile.deploy
> +	string(name: 'PR_message', defaultValue: '', description: 'To determine pull request message')
This we can construct it directly into the pipeline, no need as parameter

2020-06-17 07:25 UTC, radtriste commented on Jenkinsfile.deploy
> +				if(params.release!=false)
Version should be also available for this stage, we need to check that

2020-06-17 07:25 UTC, radtriste commented on Jenkinsfile.deploy
> +					githubscm.createBranch(${params.branch_name})
Create branch based on version instead of branch

2020-06-17 12:31 UTC, spolti requested changes

2020-06-17 12:31 UTC, spolti commented on Jenkinsfile.deploy
> +                return params.Version && params.VERSION != ''
indentation.

2020-06-17 12:31 UTC, spolti commented on Jenkinsfile.deploy
> +	          githubscm.createBranch(${params.BUILD_BRANCH_NAME})
same in this block.

2020-06-17 12:35 UTC, shashankcuber commented on Jenkinsfile.deploy
> +	          githubscm.createBranch(${params.BUILD_BRANCH_NAME})
I did the indendation change in my vscode and it seems fine there but when I push it to the repo it get distorted.  @spolti

2020-06-17 12:45 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +	          githubscm.createBranch(${params.BUILD_BRANCH_NAME})
Please use forkRepo and createBranch at the start of pipeline before any change is made

2020-06-17 12:50 UTC, shashankcuber commented on Jenkinsfile.deploy
> +	          githubscm.createBranch(${params.BUILD_BRANCH_NAME})
Okay I am figuring out the indendation

2020-06-17 16:12 UTC, Kaitou786 requested changes

2020-06-17 16:12 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +createBranch()
Methods over won't work, please move them inside pipeline{}, just keep them before  `stage('Update Version')`

2020-06-18 15:10 UTC, Kaitou786 requested changes

2020-06-18 15:10 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +        createBranch()
I'm not sure, but I don't think the functions will be able to run from here, they need to inside a stage and inside that in script{}, maybe you can create a new stage and call these function from there

2020-06-18 15:26 UTC, shashankcuber commented on Jenkinsfile.deploy
> +        createBranch()
Tell me what should I keep the name of stage and I will add it in the stage @Kaitou786

2020-06-18 15:30 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +        createBranch()
Maybe you can name it as `create branch`, also I think that createPR() method should be called at the end of the pipeline, if everything succeeded and all changes have been made

2020-06-18 15:36 UTC, shashankcuber commented on Jenkinsfile.deploy
> +        createBranch()
okay sure. And I will move the create PR stage to the end of pipeline no worries.

2020-06-19 07:52 UTC, radtriste requested changes

2020-06-19 07:52 UTC, radtriste commented on Jenkinsfile.deploy
> +    string(name: 'DISPLAY_NAME', defaultValue: '', description: 'Setup a specific build display name')
You need to do something for the formatting of Jenkinsfile on your IDE, this should not be changed ...

2020-06-19 07:52 UTC, radtriste commented on Jenkinsfile.deploy
> +        stage('Create Branch') {
Create branch only if release and version available, else we don't need it

2020-06-19 07:52 UTC, radtriste commented on Jenkinsfile.deploy
> +                    forkRepo()
Those are from `githubscm` shared library and should be called from it (`githubscm.forkRepo()`)

2020-06-19 07:52 UTC, radtriste commented on Jenkinsfile.deploy
> +                    githubscm.createBranch(${params.BUILD_BRANCH_NAME})
PLease remove those lines from here

2020-06-19 07:52 UTC, radtriste commented on Jenkinsfile.deploy
> +        stage('Create Branch') {
and call it `Prepare for PR`, I think it is more accurate

2020-06-19 07:57 UTC, shashankcuber commented on Jenkinsfile.deploy
> +                    githubscm.createBranch(${params.BUILD_BRANCH_NAME})
Okay sure. I am making the changes

2020-06-19 08:25 UTC, radtriste commented on Jenkinsfile.deploy
> +	agent { label 'jenkins-slave' }
please leave to 4 characters ...

2020-06-19 08:27 UTC, Kaitou786 commented
Can you also squash your commits?

2020-06-22 11:13 UTC, Kaitou786 requested changes

2020-06-22 11:13 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +					//githubscm.push()
The push function is available in shared library, please use that one

2020-06-22 11:13 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +					echo "$entry.key = $entry.value" > deploy.properties
Have you tested this for loop somewhere?

2020-06-22 11:13 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +
Please, don't use first character as upper case, you can use something like `pullRequestLink`

2020-06-22 11:13 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +
or the key can be more descriptive like `pr.link.kogito-images`

2020-06-22 11:13 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +					githubscm.forkRepo()
Please use different creds inside `forkRepo` as the default value is kie-ci which'll have no effect when running from this place

2020-06-22 11:13 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +		}
can you also check why the indentation is all shifted a bit towards the right ?

2020-06-22 11:36 UTC, shashankcuber commented on Jenkinsfile.deploy
> +					echo "$entry.key = $entry.value" > deploy.properties
wait instead of map it should be properties the name of hash map my bad.

2020-06-22 11:37 UTC, shashankcuber commented on Jenkinsfile.deploy
> +					githubscm.forkRepo()
which credentials then if not default?

2020-06-22 11:37 UTC, shashankcuber commented on Jenkinsfile.deploy
> +		}
I am still not able to figure it out even when I have pushed from my side the indentation is fine.

2020-06-22 11:40 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +					githubscm.forkRepo()
The default creds is for the kiegroup, we need some other org to send the PR from. IMO we can use https://github.com/bsig-gh-bot/. So you need to store the username password for this org and jenkins and pass the crendentialID in the func

2020-06-22 11:41 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +		}
The indentation is not only for the parts you added/changed. For most of the file the indentation is distorted, Try checking your IDE setting for indentation

2020-06-22 11:46 UTC, shashankcuber commented on Jenkinsfile.deploy
> +					githubscm.forkRepo()
I don't have the credentials for the given repo

2020-06-22 11:47 UTC, shashankcuber commented on Jenkinsfile.deploy
> +		}
I am always try to figure it out can you show once how it looks from your end as from my end every time it looks fine

2020-06-22 12:01 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +					githubscm.forkRepo()
I think Marek should be able to help you with that

2020-06-22 12:02 UTC, shashankcuber commented on Jenkinsfile.deploy
> +					githubscm.forkRepo()
Okay cool I will ask him about that and will let you know till then I will start off with the other kogito 2289 stuff

2020-06-29 16:57 UTC, radtriste commented on Jenkinsfile.deploy
> +
I would rather use `kogito-images.pr.link` to order by project :)

2020-06-29 16:57 UTC, radtriste commented on Jenkinsfile.deploy
> +					echo "$entry.key = $entry.value" > deploy.properties
please construct a string and then use [writeFile](https://www.jenkins.io/doc/pipeline/steps/workflow-basic-steps/#writefile-write-file-to-workspace)

2020-06-29 17:02 UTC, radtriste commented on Jenkinsfile.deploy
> +					githubscm.createBranch(${params.BUILD_BRANCH_NAME})
```suggestion
					githubscm.createBranch(params.BUILD_BRANCH_NAME)
```

2020-06-29 17:02 UTC, radtriste commented on Jenkinsfile.deploy
> +					sh "python manage-kogito-version.py bump to ${params.VERSION}"
`--bump-to` ?

2020-06-29 17:02 UTC, radtriste commented on Jenkinsfile.promote
> +        string(name : 'URL_DEPLOY_BUILD', defaultValue: '', description: 'URL to jenkins deploy build to retrieve the deployment.properties file')
`DEPLOY_BUILD_URL`

2020-06-29 17:02 UTC, radtriste commented on Jenkinsfile.promote
> +        string(name : 'Git tag' , defaultValue: '' , description : '')
`GIT_TAG`

2020-06-29 17:02 UTC, radtriste commented on Jenkinsfile.promote
> +                    githubscm.mergePR()
you need to pass the PRlink there, so you need to retrieve it from the `URL_DEPLOY_BUILD` artifact `deployment.properties`

2020-06-29 17:02 UTC, radtriste commented on Jenkinsfile.deploy
> +		}
it seems you are still using tabs for the formatting ...

2020-06-30 06:38 UTC, shashankcuber commented on Jenkinsfile.deploy
> +					sh "python manage-kogito-version.py bump to ${params.VERSION}"
It was a command mentioned in kogito-images/scripts/managing kogito images version

2020-06-30 06:50 UTC, shashankcuber commented on Jenkinsfile.promote
> +                    githubscm.mergePR()
For this I had an alternate idea which we can discuss in the meeting today

2020-06-30 09:44 UTC, radtriste commented on Jenkinsfile.promote
> +                    githubscm.tagRepository()
please do that in a separate stage.
And before tagging, please checkout the latest changes

2020-06-30 09:46 UTC, radtriste commented on Jenkinsfile.promote
> +                    githubscm.tagRepository()
please also the definition of the method https://github.com/kiegroup/jenkins-pipeline-shared-libraries/blob/760f283ce035e125d8d97647894b72ee5871d455/vars/githubscm.groovy#L130

2020-07-01 08:29 UTC, radtriste commented on Jenkinsfile.deploy
> +    string(name: 'DISPLAY_NAME', defaultValue: '', description: 'Setup a specific build display name')
The formatting is much better. Please set back the "parameters" to 8 spaces from beginning (as they are in `parameters` closure)

2020-07-01 08:29 UTC, radtriste commented on Jenkinsfile.deploy
> +                    githubscm.createBranch(params.BUILD_BRANCH_NAME)
the branch you create should not be based on the current built branch but on the `VERSION`. that will leave also a history on the forked repo.

2020-07-01 08:29 UTC, radtriste commented on Jenkinsfile.deploy
> +                    return params.VERSION != '' && params.RELEASE
In the `Initialization` stage, check that `VERSION` is set if `RELEASE` is enabled and error if that is not the case.
Then you just need to have `params.RELEASE` here and you will be sure that VERSION is set :)

2020-07-01 08:29 UTC, radtriste commented on Jenkinsfile.deploy
> +        {
please put that one at the end of the previous line

2020-07-01 08:29 UTC, radtriste commented on Jenkinsfile.deploy
> +                    PROPERTIES["VERSION"] = ${params.VERSION}
properties should be in lowercase

and this could be set at the end of the `Initialization` stage as it is a known parameter

2020-07-01 08:29 UTC, radtriste commented on Jenkinsfile.deploy
> +                    sh "python manage-kogito-version.py bump to ${params.VERSION}"
This will still not work, the command is 

```
sh "python manage-kogito-version.py --bump-to ${params.VERSION}"
```

You should also add the `--confirm` to avoid the confirm step in the step.

2020-07-01 08:29 UTC, radtriste commented on Jenkinsfile.deploy
> +                    return params.VERSION != '' && params.RELEASE
same here, check only `RELEASE` param, should be enough if check is done in `Initialization` stage

2020-07-01 08:29 UTC, radtriste commented on Jenkinsfile.deploy
> +                    githubscm.commitChanges()
missing some parameters here, please check https://github.com/kiegroup/jenkins-pipeline-shared-libraries/blob/7fd44e04c5d5c39f1d5cb752823f9cb2ab343cee/vars/githubscm.groovy#L102

2020-07-01 08:29 UTC, radtriste commented on Jenkinsfile.deploy
> +                    githubscm.push()
https://github.com/kiegroup/jenkins-pipeline-shared-libraries/blob/7fd44e04c5d5c39f1d5cb752823f9cb2ab343cee/vars/githubscm.groovy#L149

2020-07-01 12:29 UTC, shashankcuber commented on Jenkinsfile.deploy
> +                    return params.VERSION != '' && params.RELEASE
But like we can do this way also why to prior check it ?

2020-07-01 12:30 UTC, shashankcuber commented on Jenkinsfile.deploy
> +        {
What is 'that' over here ?

2020-07-01 12:30 UTC, shashankcuber commented on Jenkinsfile.deploy
> +                    PROPERTIES["VERSION"] = ${params.VERSION}
okay cool correcting it

2020-07-01 12:31 UTC, shashankcuber commented on Jenkinsfile.deploy
> +                    sh "python manage-kogito-version.py bump to ${params.VERSION}"
Where to add this --confirm at the end of this command?

2020-07-01 14:36 UTC, radtriste commented on Jenkinsfile.deploy
> +                    return params.VERSION != '' && params.RELEASE
because we should not accept the `RELEASE` true if no `VERSION` is set IMO

2020-07-01 14:36 UTC, radtriste commented on Jenkinsfile.deploy
> +        {
the `{`

2020-07-01 14:36 UTC, radtriste commented on Jenkinsfile.deploy
> +                    sh "python manage-kogito-version.py bump to ${params.VERSION}"
at the end of the command

2020-07-02 07:54 UTC, shashankcuber commented on Jenkinsfile.deploy
> +                    return params.VERSION != '' && params.RELEASE
So in this also its && so in case of && , x&&y so if x becomes false then it will not even check for version thing and move forward in the stage.

2020-07-02 07:54 UTC, shashankcuber commented on Jenkinsfile.deploy
> +        {
okay :)

2020-07-02 07:55 UTC, shashankcuber commented on Jenkinsfile.deploy
> +                    sh "python manage-kogito-version.py bump to ${params.VERSION}"
Thanks :)

2020-07-02 08:03 UTC, radtriste commented on Jenkinsfile.deploy
> +                    return params.VERSION != '' && params.RELEASE
We also want a fail fast in `Initialization` stage and then we don't need to check for both anymore ...

and no need to rewrite it many times as it is also the case here: https://github.com/kiegroup/kogito-images/pull/183/files#diff-4c6c57cd8094d1a0078f1cfa0e02fcf9R220

2020-07-02 08:12 UTC, shashankcuber commented on Jenkinsfile.deploy
> +                    return params.VERSION != '' && params.RELEASE
Okay cool I am getting it so just shifting the release thing in Initialization stage. :)

2020-07-02 21:04 UTC, shashankcuber commented on Jenkinsfile.deploy
> +                    githubscm.createBranch(params.BUILD_BRANCH_NAME)
Done

2020-07-03 14:01 UTC, Kevin-Mok requested changes

2020-07-03 14:01 UTC, Kevin-Mok commented on Jenkinsfile.promote
>  }
This looks mighty useful for [my snapshot task](https://issues.redhat.com/browse/KOGITO-2377) for the runtimes promote pipeline. Could this be extracted to [the shared libraries](https://github.com/kiegroup/jenkins-pipeline-shared-libraries) so I could use this function in my task as well? https://issues.redhat.com/browse/KOGITO-2648

2020-07-06 11:55 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +                    githubscm.forkRepo()
please use the credentialId `bsig-gh-bot`  in this function

2020-07-06 11:56 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +
Please fix indent here as well

2020-07-06 11:56 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +                }
IIRC the option is `--bump-to`

2020-07-06 11:57 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +                    //store it in the properties map
Pass the credentialID here as well

2020-07-06 11:58 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +
Need to pass other parameters in the createPR method as well Please see https://github.com/kiegroup/jenkins-pipeline-shared-libraries/blob/7fd44e04c5d5c39f1d5cb752823f9cb2ab343cee/vars/githubscm.groovy#L102 also use the bsig-gh-bot credential id here

2020-07-06 11:59 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +                {
Can we have a better name over here, other than each?

2020-07-07 10:30 UTC, shashankcuber commented on Jenkinsfile.promote
>  }
I will add it to shared libraries one

2020-07-07 10:31 UTC, shashankcuber commented on Jenkinsfile.deploy
> +                    //store it in the properties map
In pushObject right?

2020-07-07 10:31 UTC, shashankcuber commented on Jenkinsfile.deploy
> +                {
It's just like an auto iterator

2020-07-07 10:34 UTC, shashankcuber commented on Jenkinsfile.deploy
> +                }
yep right !!

2020-07-07 10:40 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +                    //store it in the properties map
Yes

2020-07-07 10:41 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +                {
Yes, but IMO it can be more descriptive

2020-07-07 10:44 UTC, shashankcuber commented on Jenkinsfile.deploy
> +                {
IMO ? I didn't get you (International Mathematics Olympiad ):p

2020-07-07 10:53 UTC, radtriste commented on Jenkinsfile.deploy
> +            when {
There is no `when` condition to do here ...
See https://github.com/kiegroup/kogito-runtimes/pull/570/files#diff-30e5521dd56f46e99634f276685d8e7eR45 for what should be done in `Initialization`

2020-07-07 10:53 UTC, radtriste commented on Jenkinsfile.deploy
> +        stage('Prepare for PR') {
I was thinking those 2 steps (forkRepo and createBranch) could be done directly into the `Create PR` stage

2020-07-07 10:53 UTC, radtriste commented on Jenkinsfile.deploy
> +def properties = [ : ]
Global variable should be defined without `def`
See https://github.com/kiegroup/kogito-cloud-operator/pull/420/files#r450517728

2020-07-07 10:53 UTC, radtriste commented on Jenkinsfile.deploy
> +                {
IMO = In My Opinion

You could as well do something like that: https://github.com/kiegroup/kogito-cloud-operator/pull/420/files#diff-4c6c57cd8094d1a0078f1cfa0e02fcf9R229

2020-07-07 10:53 UTC, radtriste commented on Jenkinsfile.deploy
> +                    githubscm.forkRepo( "bsig-gh-bot" )
we will need this cred as well for the push, so it could be defined as env var

2020-07-07 11:00 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +                    githubscm.forkRepo( "bsig-gh-bot" )
Yes, fork, push and PR will use this creds and only merge one will use kie-ci.

2020-07-07 12:08 UTC, shashankcuber commented on Jenkinsfile.deploy
> +                {
Isn't the way I did is fine?

2020-07-07 12:09 UTC, shashankcuber commented on Jenkinsfile.deploy
> +            when {
okay will change it earlier I did it without when but before doing PR I thought you told to use when instead of if so I changed it

2020-07-07 12:10 UTC, shashankcuber commented on Jenkinsfile.deploy
> +        stage('Prepare for PR') {
Should I change it then into CREATE PR and remove this stage?

2020-07-07 12:10 UTC, shashankcuber commented on Jenkinsfile.deploy
> +def properties = [ : ]
okay making it :)

2020-07-07 12:38 UTC, shashankcuber commented on Jenkinsfile.deploy
> +            when {
But you said to check for VERSION condition in Initialisation stage so that it can be removed from other later stages ?

2020-07-07 12:40 UTC, shashankcuber commented on Jenkinsfile.deploy
> +                    githubscm.forkRepo( "bsig-gh-bot" )
PR is createPR function?

2020-07-07 12:41 UTC, shashankcuber commented on Jenkinsfile.deploy
> +                    githubscm.forkRepo( "bsig-gh-bot" )
I have used the new cred of bsig-gh-bot in fork,push and Create PR functions of shared lib

2020-07-07 12:43 UTC, radtriste commented on Jenkinsfile.deploy
> +            when {
earlier I asked about checking that `VERSION` is set when `RELEASE` is set

2020-07-07 12:43 UTC, radtriste commented on Jenkinsfile.deploy
> +        stage('Prepare for PR') {
on a second thought, that can stay here

2020-07-07 12:44 UTC, radtriste commented on Jenkinsfile.deploy
> +                {
it is but the one-liner is clearer.
btw, the `writeFile` should not be in the `for` loop

2020-07-07 12:46 UTC, shashankcuber commented on Jenkinsfile.deploy
> +                {
Why can't the writeFile come in loop it will be very helpful to do this way in order to get the string in new line in the properties file

2020-07-07 12:47 UTC, shashankcuber commented on Jenkinsfile.deploy
> +            when {
I still didn't get you on this

2020-07-07 12:47 UTC, shashankcuber commented on Jenkinsfile.deploy
> +        stage('Prepare for PR') {
okay :)

2020-07-07 12:47 UTC, radtriste commented on Jenkinsfile.deploy
> +            when {
I did not say that this stage is optional and should be executed only if VERSION is set ...

2020-07-07 12:48 UTC, radtriste commented on Jenkinsfile.deploy
> +                {
`writeFile` will just overwrite the content when you call it.
you build first the string in the loop and after that you write into the file

2020-07-07 12:49 UTC, radtriste commented on Jenkinsfile.deploy
> +            when {
I meant this: https://github.com/kiegroup/kogito-cloud-operator/pull/420/files#diff-4c6c57cd8094d1a0078f1cfa0e02fcf9R84-R86

2020-07-07 12:50 UTC, shashankcuber commented on Jenkinsfile.deploy
> +                {
okay cool, then I will do it as done in Kevin PR :)

2020-07-08 09:09 UTC, shashankcuber commented on Jenkinsfile.deploy
> +            when {
I have set the version in the map here by checking the condition if version is set.

if(params.VERSION != '')
                    {
                        properties['VERSION'] = params.VERSION
                    }
I hope this looks fine

2020-07-08 17:43 UTC, radtriste commented on Jenkinsfile.deploy
> +def to_key_value = ""
no need to define that here as it is used in only one stage. keep it local

2020-07-08 17:43 UTC, radtriste commented on Jenkinsfile.deploy
> +properties = [ : ]
Please call it `deploy_properties`

2020-07-08 17:43 UTC, radtriste commented on Jenkinsfile.deploy
> +    string(name: 'VERSION', defaultValue: '', description: 'To check version and update it')
Can you update this param to `PROJECT_VERSION` which is more meaningful

2020-07-08 17:43 UTC, radtriste commented on Jenkinsfile.deploy
> +
please correct indentation here

2020-07-08 17:43 UTC, radtriste commented on Jenkinsfile.deploy
> +                        properties['VERSION'] = params.VERSION
```suggestion
                        properties['project.version'] = params.VERSION
```

2020-07-08 17:43 UTC, radtriste commented on Jenkinsfile.deploy
> +                }
please also store the `RELEASE` and `BUILD_BRANCH_NAME` information
example: https://github.com/kiegroup/kogito-runtimes/pull/570/files#diff-30e5521dd56f46e99634f276685d8e7eR42-R44

2020-07-08 17:43 UTC, radtriste commented on Jenkinsfile.deploy
> +            }
You should also check that the version is set when release is enabled
example: https://github.com/kiegroup/kogito-runtimes/pull/570/files#diff-30e5521dd56f46e99634f276685d8e7eR39-R41

2020-07-08 17:43 UTC, radtriste commented on Jenkinsfile.deploy
> +                    sh "python manage-kogito-version.py --bump-to ${params.VERSION} --confirm"
here we should add the option `--apps-branch` if `BUILD_BRANCH_NAME != master`
See https://github.com/kiegroup/kogito-images/blob/d3f70ba3d372da3216f8f021c1f12584de5207b9/scripts/manage-kogito-version.py#L71

2020-07-08 17:43 UTC, radtriste commented on Jenkinsfile.deploy
> +        }
This should not be there anymore

2020-07-08 17:43 UTC, radtriste commented on Jenkinsfile.deploy
> +                    githubscm.commitChanges(GIT_USER , GIT_USER_EMAIL, COMMIT_MSG, "pom.xml")
Please use `env.GIT_COMMITTER_NAME` and `env.GIT_COMMITTER_EMAIL` instead of `GIT_USER` and `GIT_USER_EMAIL`

And `COMMIT_MSG` should be defined somewhere

Also, there is no pom here to add. you should just add all the modifications.

Finally, specific to kogito-images repository, the commitChanges should happen just before the `Setup tests repository` stage as we don't want to commit modifications from `Setup tests repository` ...
`pushObject` stays here in this stage.

2020-07-08 17:43 UTC, radtriste commented on Jenkinsfile.deploy
> +                    properties["kogito-images.pr.link"]=githubscm.createPR(${params.VERSION}, "bsig-gh-bot")
```suggestion
                    properties["kogito-images.pr.link"]=githubscm.createPR(params.VERSION, "bsig-gh-bot")
```

2020-07-08 17:43 UTC, radtriste commented on Jenkinsfile.deploy
> +        //write to properties file
remove this line

2020-07-08 17:43 UTC, radtriste commented on Jenkinsfile.deploy
> +                cleanWorkspaces()
```suggestion
                clean()
```

2020-07-08 17:43 UTC, radtriste commented on Jenkinsfile.deploy
> +                to_key_value = properties.collect{ entry -> "${entry.key}=${entry.value}" }.join("\n")
```suggestion
                def propertiesStr = properties.collect{ entry -> "${entry.key}=${entry.value}" }.join("\n")
```

2020-07-08 17:43 UTC, radtriste commented on Jenkinsfile.deploy
> +                writeFile( file : 'Deployment.properties' , text : to_key_value)
```suggestion
                writeFile( file : 'deployment.properties' , text : propertiesStr)
```

2020-07-08 17:43 UTC, radtriste commented on Jenkinsfile.deploy
> +                archiveArtifacts artifacts: 'deploy.properties', allowEmptyArchive:true
```suggestion
                archiveArtifacts artifacts: 'deployment.properties', allowEmptyArchive:true
```

2020-07-08 17:43 UTC, radtriste commented on Jenkinsfile.promote
> +def readProp;
```suggestion
deployProperties = [:]
```

2020-07-08 17:43 UTC, radtriste commented on Jenkinsfile.promote
> +def version;
to remove

2020-07-08 17:43 UTC, radtriste commented on Jenkinsfile.promote
> +                    readProp = readProperties file : 'Deployment.properties'
Read properties file into the `Initialization` stage and store it into `deployProperties`

For example, in this built job, https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/tradisso/job/writeFile/4/
there is an artifact called `deployment.properties`
URL to get it is https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/tradisso/job/writeFile/4/artifact/deployment.properties
so you need to build the url from given param `DEPLOY_BUILD_URL` and `deployment.properties` name
then, you can use `wget` command to download the file.
finally you can use `readProperties` to read the file and get the properties
example: https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/tradisso/job/writeFile/6/replay/

2020-07-08 17:43 UTC, radtriste commented on Jenkinsfile.promote
> +                    githubscm.mergePR(${readProp['kogito-images.pr.link']})
```suggestion
                    githubscm.mergePR(readProp['kogito-images.pr.link'])
```

2020-07-08 17:43 UTC, radtriste commented on Jenkinsfile.promote
> +                        checkout(githubscm,resolveRepository("kogito-runtimes", "kiegroup", env.BRANCH_NAME, false))
```suggestion
                         checkout(githubscm.resolveRepository("kogito-images", params.GIT_AUTHOR, params.BUILD_BRANCH_NAME, false))
```

2020-07-08 17:43 UTC, radtriste commented on Jenkinsfile.promote
> +                        githubscm.tagRepository("Kogito-images" , "user@kogito-images")
use `GIT_COMMITTER_EMAIL`

2020-07-08 17:43 UTC, radtriste commented on Jenkinsfile.promote
> +    sh "python manage-kogito-version.py --bump-to v"
once you exported the method to shared lib as `def getNextSnapshot(String version)`, set this command directly into the stage as `h "python manage-kogito-version.py --bump-to ${utils.getNextSnapshot(params.VERSION)}"`

2020-07-08 17:43 UTC, radtriste commented on Jenkinsfile.promote
> +        booleanParam(name: 'RELEASE', defaultValue: false, description: 'To specify that deployment is done for release process')
Configuration can be done via the deploy file or via params.
check https://github.com/kiegroup/kogito-cloud-operator/pull/420/files?file-filters%5B%5D=.promote#diff-55fc28b547fad1a92acc0c1a451670a5R15-R21 and https://github.com/kiegroup/kogito-cloud-operator/pull/420/files?file-filters%5B%5D=.promote#diff-55fc28b547fad1a92acc0c1a451670a5R284-R301

2020-07-08 18:07 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +
can this extra line be removed?

2020-07-08 18:07 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +
+1

2020-07-08 18:07 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +    string(name: 'VERSION', defaultValue: '', description: 'To check version and update it')
+1

2020-07-08 18:14 UTC, Kaitou786 commented on Jenkinsfile.promote
> +                }
remove extra new lines

2020-07-08 18:14 UTC, Kaitou786 commented on Jenkinsfile.promote
>              }
is this needed here?

2020-07-09 08:36 UTC, shashankcuber commented on Jenkinsfile.deploy
> +
Indentation of new lines? As I don't think tabs and spaces conflict is there ?

2020-07-09 08:40 UTC, shashankcuber commented on Jenkinsfile.promote
> +def readProp;
Why to take a map in promote file?

2020-07-09 08:41 UTC, shashankcuber commented on Jenkinsfile.promote
>              }
This not added by me

2020-07-09 08:45 UTC, shashankcuber commented on Jenkinsfile.deploy
> +def to_key_value = ""
string is local to one stage but map should be global I think

2020-07-09 08:51 UTC, radtriste commented on Jenkinsfile.deploy
> +def to_key_value = ""
the final map `to_key_value` does not need to be global ... you only use it to write into the file then

2020-07-09 08:52 UTC, radtriste commented on Jenkinsfile.deploy
> +
old indentation was 8 spaces which is normal after the `{`, your refactoring is putting 4 spaces only. Please put back those lines to 8 spaces.

2020-07-09 08:52 UTC, radtriste commented on Jenkinsfile.promote
> +def readProp;
yeah sorry, it will be properties. but we should still define as global var

2020-07-09 08:55 UTC, radtriste commented on Jenkinsfile.promote
>              }
this is a leftover of your rebase, this stage should be deleted.
it does not exist on master ... https://github.com/kiegroup/kogito-images/blob/d3f70ba3d372da3216f8f021c1f12584de5207b9/Jenkinsfile.promote#L86

2020-07-09 08:56 UTC, shashankcuber commented on Jenkinsfile.deploy
> +                }
I have to store them in deploy_properties map? And if yes then please let me know the key name which you want else later again there will be conflicts on naming

2020-07-09 08:58 UTC, shashankcuber commented on Jenkinsfile.deploy
> +def to_key_value = ""
Yeah right I changed it to propertiesStr and locally defined in post of pipeline where I am doing writeFile

2020-07-09 09:01 UTC, shashankcuber commented on Jenkinsfile.deploy
> +
I always do it with 8 spaces even locally it's 8 space, okay will look into it.I have never faced such issue of indentation conflicts.

2020-07-09 09:02 UTC, shashankcuber commented on Jenkinsfile.promote
>              }
okay I will delete this stage.

2020-07-09 09:13 UTC, radtriste commented on Jenkinsfile.deploy
> +                }
everything is already mentioned in the example PR ... there will be no conflict as this is not the same pipeline

2020-07-09 09:17 UTC, shashankcuber commented on Jenkinsfile.deploy
> +                }
I saw the example PR does not have anything related to storing these and I was saying about conflicts not related to git but like I always name things and then later you don't find it appropriate

2020-07-09 09:29 UTC, radtriste commented on Jenkinsfile.deploy
> +                }
- `git.branch`
- `project.version`
- `release`

Those are the properties to set (if needed, which means if value is not null)

2020-07-09 09:40 UTC, shashankcuber commented on Jenkinsfile.promote
> +def version;
Just above you said to keep def properties by changing readProp and version yes I can use locally as it's only used in setNextSnapshot() function

2020-07-09 12:25 UTC, radtriste commented on Jenkinsfile.promote
> +def version;
indeed, `properties` need to be kept as global and `version` can be removed and used as local variable

2020-07-09 15:29 UTC, shashankcuber commented on Jenkinsfile.promote
>  }
I have added it but still test is to be written.

2020-07-09 16:58 UTC, shashankcuber commented on Jenkinsfile.promote
> +    sh "python manage-kogito-version.py --bump-to v"
It is in promote file so here I have to extract version from deployment.properties and then pass it as argument to function this will be a correct way I think so !!

2020-07-10 06:03 UTC, Kevin-Mok requested changes

2020-07-10 06:03 UTC, Kevin-Mok commented on Jenkinsfile.deploy
> +                    githubscm.commitChanges(env.GIT_COMMITTER_NAME , env.GIT_COMMITTER_EMAIL, COMMIT_MSG)
```suggestion
                    githubscm.commitChanges(COMMIT_MSG)
```

I'm updating `commitChanges()` to not take Git committer parameters. See: https://issues.redhat.com/browse/KOGITO-2724

2020-07-10 06:03 UTC, Kevin-Mok commented on Jenkinsfile.promote
> +                    githubscm.tagRepository("Kogito-images" , "env.GIT_COMMITTER_EMAIL")
I'm updating the `tagRepository()` signature to `(String tagName, String buildTag = '')`. See: https://issues.redhat.com/browse/KOGITO-2724

For `tagName`, I would suggest implementing @radtriste's [`getGitTag()` helper function](https://github.com/radtriste/kogito-cloud-operator/blob/173ab39abe357420354e5ba45bd5c17b13ff1f8c/Jenkinsfile.promote#L296-L298) along with all its dependent helper functions.  For `buildTag`, you should pass in `env.BUILD_TAG`.

2020-07-10 08:15 UTC, radtriste commented on Jenkinsfile.deploy
> +               steps {
indentation ;)

2020-07-10 08:15 UTC, radtriste commented on Jenkinsfile.deploy
> +    clean()
```suggestion
    cleanWorkspaces()
```

2020-07-10 08:15 UTC, radtriste commented on Jenkinsfile.deploy
> +                cleanWorkspaces()
```suggestion
                clean()
```

2020-07-10 08:15 UTC, radtriste commented on Jenkinsfile.deploy
> +
Please remove the useless empty lines

2020-07-10 08:15 UTC, radtriste commented on Jenkinsfile.deploy
> +                        sh "python manage-kogito-version.py --bump-to ${params.PROJECT_VERSION} --confirm --apps-branch"
```suggestion
                        sh "python manage-kogito-version.py --bump-to ${params.PROJECT_VERSION} --confirm --apps-branch ${params.BUILD_BRANCH_NAME}"
```

2020-07-10 08:15 UTC, radtriste commented on Jenkinsfile.promote
> +def deployProperties
We need to have `deployProperties` as global, so the `def` needs to be removed
```suggestion
deployProperties
```

2020-07-10 08:15 UTC, radtriste commented on Jenkinsfile.promote
> +                        params.RELEASE = getRelease("release")
This should not be done in this `if` block

2020-07-10 08:15 UTC, radtriste commented on Jenkinsfile.promote
> +                        params.RELEASE = getRelease("release")
also we do not override the parameter (you won't be able to do so anyway)
https://github.com/kiegroup/kogito-runtimes/pull/570/files#diff-55fc28b547fad1a92acc0c1a451670a5R122

2020-07-10 08:15 UTC, radtriste commented on Jenkinsfile.promote
> +                    return params.RELEASE && params.DEPLOY_BUILD_URL != ''
Please use `utils` method to retrieve the `release`, `project version` information that could come either from parameter or from the `deployProperties`

See https://github.com/kiegroup/kogito-runtimes/pull/570/files#diff-55fc28b547fad1a92acc0c1a451670a5R122

2020-07-10 08:15 UTC, radtriste commented on Jenkinsfile.promote
> +                    githubscm.tagRepository("Kogito-images" , "env.GIT_COMMITTER_EMAIL")
@Kevin-Mok you mean `env.BUILD_TAG` => `env.GIT_TAG`

2020-07-10 08:15 UTC, radtriste commented on Jenkinsfile.promote
> +        booleanParam(name: 'RELEASE', defaultValue: false, description: 'Override `deployment.properties`')
Add also `BUILD_BRANCH_NAME` and `PROJECT_VERSION`
See https://github.com/kiegroup/kogito-runtimes/pull/570/files#diff-55fc28b547fad1a92acc0c1a451670a5R15-R17

2020-07-10 08:15 UTC, radtriste commented on Jenkinsfile.promote
> +                    checkout(githubscm,resolveRepository("kogito-images", params.GIT_AUTHOR, params.BUILD_BRANCH_NAME, false))
```suggestion
                    checkout(githubscm.resolveRepository("kogito-images", params.GIT_AUTHOR, params.BUILD_BRANCH_NAME, false))
```

2020-07-10 08:15 UTC, radtriste commented on Jenkinsfile.promote
> +                    githubscm.tagRepository( , env.BUILD_TAG)
```suggestion
                    githubscm.tagRepository( ???, env.BUILD_TAG)
```

2020-07-10 08:15 UTC, radtriste commented on Jenkinsfile.promote
> +                   def verison = getVersion("project.version")
```suggestion
                   def version = getVersion("project.version")
```

2020-07-10 08:15 UTC, radtriste commented on Jenkinsfile.promote
> +    }
please also `echo` the properties so we have them in the pipeline log
https://github.com/kiegroup/kogito-runtimes/pull/570/files?file-filters%5B%5D=.promote#diff-55fc28b547fad1a92acc0c1a451670a5R95-R96

2020-07-10 08:59 UTC, Kevin-Mok commented on Jenkinsfile.promote
> +                    githubscm.tagRepository("Kogito-images" , "env.GIT_COMMITTER_EMAIL")
@radtriste The optional `buildTag` parameter in `tagRepository` is just for the commit message so that it has a reference to the build it came from.

For example, in [this build](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/kmok/job/KOGITO-2724/14/console), `githubscm.tagRepository("$BUILD_TAG", "$BUILD_TAG")` produces the command `git tag -a jenkins-custom-kmok-KOGITO-2724-14 -m 'Tagged by Jenkins in build "jenkins-custom-kmok-KOGITO-2724-14".'`.

2020-07-10 12:45 UTC, radtriste reviewed
Some minor changes to be done (I tried to explain why)
Also the set next snapshot needs to be slightly improve to commit changes.
Sorry for those late changes ...
@Kevin-Mok might be able to help as well when I am off

2020-07-10 12:45 UTC, radtriste commented on Jenkinsfile.deploy
> +                    githubscm.pushObject("origin", NEW_BRANCH , "bsig-gh-bot")
`NEW_BRANCH` does not exist in the pipeline. It might be a leftover from earlier.

```suggestion
                    githubscm.pushObject("origin", params.PROJECT_VERSION , "bsig-gh-bot")
```

2020-07-10 12:45 UTC, radtriste commented on Jenkinsfile.deploy
> +                    githubscm.createBranch(params.VERSION)
Leftover from renaming :)

```suggestion
                    githubscm.createBranch(params.PROJECT_VERSION)
```

2020-07-10 12:45 UTC, radtriste commented on Jenkinsfile.deploy
> +                    githubscm.commitChanges(COMMIT_MSG)
No need to create a variable here

```suggestion
                    githubscm.commitChanges("Update project version to ${params.PROJECT_VERSION}")    
```

2020-07-10 12:45 UTC, radtriste commented on Jenkinsfile.promote
> +        string(name: 'PROJECT_VERSION', defaultValue: '', description: 'To check version and update it')
Just a small reorganization of the parameters, which makes more sense:

- `DEPLOY_BUILD_URL` should be first in those
- `GIT_AUTHOR` is needed to be sure we are on the right repository
- `GIT_TAG` needs a bit of description

```suggestion
        string(name: 'DEPLOY_BUILD_URL', defaultValue: '', description: 'URL to jenkins deploy build to retrieve the `deployment.properties` file. If base parameters are defined, they will override the `deployment.properties` information')
        string(name: 'GIT_AUTHOR', defaultValue: 'kiegroup', description: 'Override `deployment.properties`. Which Git author repository ?')
        string(name: 'BUILD_BRANCH_NAME', defaultValue: 'master', description: 'Override `deployment.properties`. Which branch to build? Set if you are not on a multibranch pipeline.')
        booleanParam(name: 'RELEASE', defaultValue: false, description: 'Override `deployment.properties`. Is this build for a release?')
        string(name: 'PROJECT_VERSION', defaultValue: '', description: 'Override `deployment.properties`. Optional if not RELEASE. If RELEASE, cannot be empty.')
        string(name: 'GIT_TAG', defaultValue: '', description: 'Git tag to set, if different from PROJECT_VERSION')
```

2020-07-10 12:45 UTC, radtriste commented on Jenkinsfile.promote
>                  }
Please assert that if isRelease() then getProjectVersion() is not empty:

https://github.com/kiegroup/kogito-runtimes/pull/570/files#diff-55fc28b547fad1a92acc0c1a451670a5R31-R33

2020-07-10 12:45 UTC, radtriste commented on Jenkinsfile.promote
> +                    return isRelease() && params.DEPLOY_BUILD_URL != ''
Once we read the deploy properties, we do not care anymore about `DEPLOY_BUILD_URL`. 
Instead, we should check the pr link is existing.

This should be:

```suggestion
                    return isRelease() && getDeployProperty('kogito-images.pr.link') != ''
```

2020-07-10 12:45 UTC, radtriste commented on Jenkinsfile.deploy
> +                    setDeployPropertyIfneeded('git.branch', params.BUILD_BRANCH_NAME)
Forgot that we also need to store the git author

```suggestion
                    setDeployPropertyIfneeded('git.branch', params.BUILD_BRANCH_NAME)
                    setDeployPropertyIfneeded('git.author', params.GIT_AUTHOR)
```

2020-07-10 12:45 UTC, radtriste commented on Jenkinsfile.promote
> +}
Just add the `getGitAuthor` util method

```suggestion
String getBuildBranch() {
    return getParamOrDeployProperty("BUILD_BRANCH_NAME", "git.branch")
}

String getGitAuthor() {
    return getParamOrDeployProperty("GIT_AUTHOR", "git.author")
}
```

2020-07-10 12:45 UTC, radtriste commented on Jenkinsfile.promote
> +                    checkout(githubscm.resolveRepository("kogito-images", params.GIT_AUTHOR, params.BUILD_BRANCH_NAME, false))
Small adjustment to use utils method

```suggestion
                    checkout(githubscm.resolveRepository("kogito-images", getGitAuthor(), getBuildBranchName(), false))
```

2020-07-10 12:45 UTC, radtriste commented on Jenkinsfile.promote
> +                    githubscm.tagRepository( tagName, env.BUILD_TAG)
No need for a variable here:

```suggestion
                    githubscm.tagRepository( getGitTag(), env.BUILD_TAG)
```

2020-07-10 12:45 UTC, radtriste commented on Jenkinsfile.promote
> +        sh "wget --auth-no-challenge --user=${JENKINS_USER} --password=${JENKINS_TOKEN} ${params.DEPLOY_BUILD_URL}artifact/deployment.properties"
Leftover from the PR of Kevin, we don't need the user and password

```suggestion
        sh "wget ${params.DEPLOY_BUILD_URL}artifact/deployment.properties"
```

2020-07-10 12:45 UTC, radtriste commented on Jenkinsfile.promote
> +                return isRelease() && params.DEPLOY_BUILD_URL != ''
Once we read the deploy properties, we do not care anymore about DEPLOY_BUILD_URL.
Instead, we should check the git tag is existing.

```suggestion
                return isRelease() && getGitTag() != ''
```

2020-07-10 12:45 UTC, radtriste commented on Jenkinsfile.deploy
> -        booleanParam(name: 'IMAGE_USE_OPENSHIFT_REGISTRY', defaultValue: false, description: 'Set to true if image should be deployed in Openshift registry.In this case, IMAGE_REGISTRY_CREDENTIALS, I
I think those one have been removed during the rebase. You should set them back.

2020-07-10 12:45 UTC, radtriste commented on Jenkinsfile.promote
> +                    checkout(githubscm.resolveRepository("kogito-images", params.GIT_AUTHOR, params.BUILD_BRANCH_NAME, false))
btw, I think we should checkout before doing the `githubscm.mergePR`.
it makes also more sense to checkout before doing any modification into the repository.
Can you move that checkout to `Merge PR` stage ?

2020-07-10 12:45 UTC, radtriste commented on Jenkinsfile.promote
> +                   sh "python manage-kogito-version.py --bump-to ${utils.getnextSnapshot(version)}"
I started a discussion with Kevin (see https://github.com/kiegroup/kogito-runtimes/pull/570#discussion_r452760513)
we should 
- fork the repo
- set next snapshot
- commitChanges
- create PR
- merge PR

As stated in the comment (link above), this can be done in a single stage.

2020-07-10 15:05 UTC, radtriste commented on Jenkinsfile.deploy
> +                    deploy_properties["kogito-images.pr.link"]=githubscm.createPR(params.PROJECT_VERSION, "bsig-gh-bot")
```suggestion
                    deploy_properties["kogito-images.pr.link"]=githubscm.createPR("Update project version to ${params.PROJECT_VERSION}", "Generated by build ${BUILD_TAG}: ${BUILD_URL}", params.BUILD_BRANCH_NAME, "bsig-gh-bot")
```

2020-07-10 16:07 UTC, shashankcuber commented on Jenkinsfile.promote
> +                   sh "python manage-kogito-version.py --bump-to ${utils.getnextSnapshot(version)}"
So what should I do shall I merge all the 5 tasks in one stage and merging all their when conditions in that stage only is that finalized step or still are we thinking on it? @radtriste

2020-07-11 04:25 UTC, Kaitou786 commented on Jenkinsfile.promote
> +                    checkout(githubscm.resolveRepository("kogito-images", getGitAuthor(), getBuildBranchname(), false))
Why are we checking out the repo here?

2020-07-11 04:25 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +
remove these extra lines

2020-07-11 07:10 UTC, shashankcuber commented on Jenkinsfile.promote
> +                    checkout(githubscm.resolveRepository("kogito-images", params.GIT_AUTHOR, params.BUILD_BRANCH_NAME, false))
@Kaitou786  see this thread

2020-07-13 11:29 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +        }
IMO, We embed this stage in the `Create PR` stage

2020-07-14 17:37 UTC, spolti commented
can be merged after https://github.com/kiegroup/kogito-images/pull/191

2020-07-14 17:44 UTC, shashankcuber commented on Jenkinsfile.promote
> +                    checkout(githubscm.resolveRepository("kogito-images", getGitAuthor(), getBuildBranchname(), false))
I mentioned about it in thread

2020-07-14 17:44 UTC, shashankcuber commented on Jenkinsfile.deploy
> +
okay I have removed

2020-07-15 06:38 UTC, shashankcuber commented on Jenkinsfile.deploy
> +        }
@radtriste Please have a look into this

2020-07-15 06:44 UTC, Kaitou786 commented on Jenkinsfile.promote
> +                    checkout(githubscm.resolveRepository("kogito-images", getGitAuthor(), getBuildBranchname(), false))
Which thread are you talking about?

2020-07-15 06:53 UTC, shashankcuber commented on Jenkinsfile.deploy
> -        booleanParam(name: 'IMAGE_USE_OPENSHIFT_REGISTRY', defaultValue: false, description: 'Set to true if image should be deployed in Openshift registry.In this case, IMAGE_REGISTRY_CREDENTIALS, I
Yeah I have set it . R 33 was removed

2020-07-15 06:53 UTC, shashankcuber commented on Jenkinsfile.promote
> +                    checkout(githubscm.resolveRepository("kogito-images", getGitAuthor(), getBuildBranchname(), false))
Like for this thing why it has been checked here , I tagged you in the thread where it was discussed.

2020-07-15 10:41 UTC, radtriste commented on Jenkinsfile.deploy
> +        }
@Kaitou786 We should not embed it in `Create PR`, because the `Setup tests repository` is updating some information we don't want to commit. So we should commit the changes before.
But we could include the `commitChanges` in `Update Maven information` stage.

2020-07-15 10:41 UTC, radtriste commented on Jenkinsfile.deploy
>          stage('Update Maven information') {
This stage should be updated to 
```
        stage('Update Maven information') {
            steps {
                script {
                    // Update artifacts
                    updateArtifactCmd = "python3 scripts/update-maven-information.py"
                    if(params.MAVEN_ARTIFACT_REPOSITORY != ''){
                        updateArtifactCmd += " --repo-url ${params.MAVEN_ARTIFACT_REPOSITORY}"
                    }
                    if(params.PROJECT_VERSION != ''){
                        updateArtifactCmd += " --version ${params.PROJECT_VERSION}"
                    }
                    sh updateArtifactCmd
                    // Debug purpose in case of issue
                    sh "cat modules/kogito-data-index/module.yaml"
                    sh "cat modules/kogito-jobs-service/module.yaml"
                    sh "cat modules/kogito-management-console/module.yaml"
                }
            }
        }
```
to take the version into account

2020-07-15 10:41 UTC, radtriste commented on Jenkinsfile.deploy
> -        string(name: 'GIT_AUTHOR', defaultValue: 'kiegroup', description: 'Which Git author repository ?')
this one should be also not removed

2020-07-15 10:41 UTC, radtriste commented on Jenkinsfile.deploy
> +                }
```suggestion
                script{
                    versionCmd = "python manage-kogito-version.py --bump-to ${params.PROJECT_VERSION} --confirm"
                    if(params.BUILD_BRANCH_NAME != 'master'){
                        versionCmd += " --apps-branch ${params.BUILD_BRANCH_NAME}"
                    }
                    sh versionCmd
                }
```

2020-07-15 10:41 UTC, radtriste commented on Jenkinsfile.promote
> +                return isRelease() && getDeployProperty('kogito-images.pr.link') != ''
```suggestion
                return isRelease() && getGitTag() != ''
```

2020-07-15 10:41 UTC, radtriste commented on Jenkinsfile.promote
> +        stage('Snapshot')
```suggestion
        stage('Set next snapshot version')
```

2020-07-15 10:41 UTC, radtriste commented on Jenkinsfile.promote
> +                   sh "python manage-kogito-version.py --bump-to ${utils.getnextSnapshot(version)}"
all those 5 tasks should be indeed into only one stage.
See update from Kevin: https://github.com/kiegroup/kogito-runtimes/pull/570/files#diff-55fc28b547fad1a92acc0c1a451670a5R101

2020-07-15 10:41 UTC, radtriste commented on Jenkinsfile.promote
> +                   sh "python manage-kogito-version.py --bump-to ${utils.getnextSnapshot(version)}"
```suggestion
                    versionCmd = "python manage-kogito-version.py --bump-to ${params.PROJECT_VERSION} --confirm"
                    if(params.BUILD_BRANCH_NAME != 'master'){
                        versionCmd += " --apps-branch ${params.BUILD_BRANCH_NAME}"
                    }
                    sh versionCmd
```

2020-07-17 12:20 UTC, radtriste commented on Jenkinsfile.promote
> +                    checkout(githubscm.resolveRepository("kogito-images", getGitAuthor(), getBuildBranchname(), false))
rebase problem ?

2020-07-17 12:28 UTC, shashankcuber commented on Jenkinsfile.promote
> +                    checkout(githubscm.resolveRepository("kogito-images", getGitAuthor(), getBuildBranchname(), false))
yeah let me check it again :/

2020-08-10 15:25 UTC, spolti commented on Jenkinsfile.promote
> +@Library('jenkins-pipeline-shared-libraries')_
what the underscore at the end does mean?

2020-08-10 15:26 UTC, spolti requested changes

2020-08-10 15:26 UTC, spolti commented on Jenkinsfile.promote
> +                        withCredentials([string(credentialsId: 'KOGITO_CI_EMAIL_TO', variable: 'ZULIP_EMAIL')]) {
what is this ZULIP_EMAIL?

2020-08-10 15:26 UTC, radtriste commented on Jenkinsfile.promote
> +@Library('jenkins-pipeline-shared-libraries')_
not sure, but as it was in all other pipelines, it was just copied ;)

2020-08-10 15:28 UTC, radtriste commented on Jenkinsfile.promote
> +                        withCredentials([string(credentialsId: 'KOGITO_CI_EMAIL_TO', variable: 'ZULIP_EMAIL')]) {
the variable's name to be used that will store the test contained into the credentials `KOGITO_CI_EMAIL_TO`

2020-08-10 15:29 UTC, Kevin-Mok commented on Jenkinsfile.promote
> +@Library('jenkins-pipeline-shared-libraries')_
> For Shared Libraries which only define Global Variables (`vars/`), or a Jenkinsfile which only needs a Global Variable, the annotation pattern `@Library('my-shared-library') _` may be useful for keeping code concise. In essence, instead of annotating an unnecessary import statement, the symbol `_` is annotated.
> It is not recommended to import a global variable/function, since this will force the compiler to interpret fields and methods as static even if they were intended to be instance. The Groovy compiler in this case can produce confusing error messages.

[Source](https://www.jenkins.io/doc/book/pipeline/shared-libraries/#using-libraries)

2020-08-10 15:30 UTC, spolti commented on Jenkinsfile.promote
> +@Library('jenkins-pipeline-shared-libraries')_
ok, thanks.

2020-08-10 15:31 UTC, spolti commented on Jenkinsfile.promote
> +                        withCredentials([string(credentialsId: 'KOGITO_CI_EMAIL_TO', variable: 'ZULIP_EMAIL')]) {
ZULIP_EMAIL led me to think that a notification will be sent to zulip chat.

2020-08-10 15:32 UTC, spolti commented
is there a way to test it before merge?

2020-08-10 15:33 UTC, Kevin-Mok commented on Jenkinsfile.promote
> +                        withCredentials([string(credentialsId: 'KOGITO_CI_EMAIL_TO', variable: 'ZULIP_EMAIL')]) {
I just used it as the variable name for the `KOGITO_CI_EMAIL_TO` credential value; it's the email which sends messages to the [kogito-ci stream in Zulip](https://kie.zulipchat.com/#narrow/stream/236603-kogito-ci). I thought it was more descriptive than `KOGITO_CI_EMAIL_TO`.

2020-08-10 15:35 UTC, spolti commented on Jenkinsfile.promote
> +                        withCredentials([string(credentialsId: 'KOGITO_CI_EMAIL_TO', variable: 'ZULIP_EMAIL')]) {
ok then :)

2020-08-10 15:36 UTC, Kevin-Mok commented
@spolti I believe @radtriste has been testing all the release pipeline PR's with the nightly [here](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/kogito/job/release-testing/).

2020-08-10 15:37 UTC, spolti commented
Awesome, thanks.

2020-08-10 15:41 UTC, radtriste commented
yeah original version was tested on 0.13.0. then I tested on my own group for the rest. Now it is being executed for 0.13.1 ;)

2020-08-10 16:29 UTC, spolti commented
ok, let's merge when it gets finished :)

2020-08-10 20:20 UTC, Kevin-Mok approved these changes

2020-08-11 06:50 UTC, radtriste requested changes

2020-08-11 06:50 UTC, radtriste commented on Jenkinsfile.deploy
>                  }
@shashankcuber there was a problem in the rebase, those lines should deleted (just apply the suiggestion)

```suggestion
                script {
                    launchParallelForEachImage("Test", {img -> testImage(img)})
                }
```

2020-08-11 06:52 UTC, Kaitou786 commented on Jenkinsfile.deploy
> +                                    sh "make ${image} ignore_test=${shouldSkipTests()} cekit_option='--work-dir .'"
is this correct?

2020-08-11 06:56 UTC, Kaitou786 commented on Jenkinsfile.promote
> +    sh "git checkout ${getBuildBranch()}"
Should we use `-B` option here?

2020-08-11 07:00 UTC, shashankcuber commented on Jenkinsfile.promote
> +    sh "git checkout ${getBuildBranch()}"
We can if we want to create a branch and then switch our branch to it.

2020-08-11 07:01 UTC, shashankcuber commented on Jenkinsfile.deploy
> +                                    sh "make ${image} ignore_test=${shouldSkipTests()} cekit_option='--work-dir .'"
@Kaitou786  these lines will be removed they should not be there during rebase it was added , refer to just above comment of Tristan

2020-08-11 07:04 UTC, Kaitou786 commented on Jenkinsfile.promote
> +    sh "git checkout ${getBuildBranch()}"
I meant if the branch already exists the `-B` will sync it with the detached head. which was checked out by above command.

2020-08-11 07:05 UTC, radtriste commented on Jenkinsfile.promote
> +    sh "git checkout ${getBuildBranch()}"
We don't need to create the branch, it will be automatically done

2020-08-11 07:05 UTC, radtriste commented on Jenkinsfile.promote
> +    sh "git checkout ${getBuildBranch()}"
it will take automatic the branch from origin

2020-08-11 07:08 UTC, Kaitou786 commented on Jenkinsfile.promote
> +    sh "git checkout ${getBuildBranch()}"
Ah okay, I suggested cause I thought if there is any difference between the branch and the detached head we are checking out the `-B` will solve that.

2020-08-11 07:17 UTC, radtriste commented on Jenkinsfile.promote
> +    sh "git checkout ${getBuildBranch()}"
yeah but as the repository has been checked out just before, it wont create any problem ;)

2020-08-11 07:22 UTC, Kaitou786 commented on Jenkinsfile.promote
> +    sh "git checkout ${getBuildBranch()}"
oki

2020-08-11 07:25 UTC, radtriste commented on Jenkinsfile.deploy
> +                                    sh "make ${image} ignore_test=${shouldSkipTests()} cekit_option='--work-dir .'"
lines are still there :S

2020-08-11 07:36 UTC, radtriste commented
@shashankcuber your last changes just completely removed my earlier changes ...

2020-08-12 07:57 UTC, radtriste approved these changes
Tested on release 0.13.1 on works like a charm !

2020-08-12 12:34 UTC, Kaitou786 approved these changes

2020-08-12 12:34 UTC, cristianonicolai approved these changes

2020-08-12 14:07 UTC, spolti approved these changes

2020-08-12 14:08 UTC, merged