[KOGITO-2046] - Remove "infinispan properties module" from Data Index…
apache/incubator-kie-kogito-images pull request #189
Opened 2020-07-10 11:34 UTC by vaibhavjainwiz

… and Jobs Service images

Jira issue : https://issues.redhat.com/browse/KOGITO-2046

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

2020-07-10 13:57 UTC, sutaakar approved these changes

2020-07-10 14:34 UTC, radtriste approved these changes

2020-07-10 14:48 UTC, Kaitou786 commented
Jenkins, retest this please

2020-07-10 14:52 UTC, ricardozanini requested changes
Many thanks for the PR! It would be possible to have the tests? Since we still have the feature in the platform.

2020-07-10 14:52 UTC, ricardozanini commented on tests/features/kogito-data-index.feature
> +    Then container log should contain + exec java -XshowSettings:properties -Dquarkus.http.port=8080 -Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -jar /home/kogito/bin/kogito-data
Although we removed the module, we still have the feature. Could you please add back this test inserting the Quarkus variables like you stated in the comment of this JIRA?

2020-07-10 14:52 UTC, ricardozanini commented on tests/features/kogito-jobs-service.feature
> +    Then container log should contain + exec java -XshowSettings:properties -Dquarkus.http.port=8080 -jar /home/kogito/bin/kogito-jobs-service-runner.jar
Same thing here regarding the tests.

2020-07-10 16:20 UTC, Kaitou786 commented
@vaibhavjainwiz can you check why the tests are failing?

2020-07-14 17:37 UTC, spolti commented
can be merged after https://github.com/kiegroup/kogito-images/pull/191

2020-07-15 09:43 UTC, radtriste commented
@vaibhavjainwiz could you rebase ?

2020-07-16 04:34 UTC, vaibhavjainwiz commented on tests/features/kogito-data-index.feature
> +    Then container log should contain + exec java -XshowSettings:properties -Dquarkus.http.port=8080 -Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -jar /home/kogito/bin/kogito-data
@ricardozanini How we could you pass kafka properties in data-index service. I tried with below cmd
```docker run -it -e QUARKUS_INFINISPAN_CLIENT_SERVER_LIST=172.18.0.1:11222 -e KAFKA_BOOTSTRAP_SERVERS=172.18.0.1:9092 quay.io/kiegroup/kogito-data-index:latest
```

But data-index service still trying to connect localhost
```2020-07-16 04:23:16,241 WARN  [org.apa.kaf.cli.NetworkClient] (vert.x-kafka-consumer-thread-4) [Consumer clientId=consumer-kogito-data-index-usertaskinstances-4, groupId=kogito-data-index-usertaskinstances] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
2020-07-16 04:23:16,242 WARN  [org.apa.kaf.cli.NetworkClient] (vert.x-kafka-consumer-thread-4) [Consumer clientId=consumer-kogito-data-index-usertaskinstances-4, groupId=kogito-data-index-usertaskinstances] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected
```

2020-07-16 04:42 UTC, vaibhavjainwiz commented
> @vaibhavjainwiz could you rebase ?

done

2020-07-16 09:19 UTC, ricardozanini commented
CI stills failing, do we know why? (I'm not in the VPN right now).

2020-07-16 09:42 UTC, sutaakar commented
@ricardozanini There are test failures, seems that built images return HTTP 500 for some reason

2020-07-16 10:03 UTC, radtriste commented
I am getting similar errors on master: https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/KIE%2Fkogito%2Fkogito-images-deploy/detail/kogito-images-deploy/74/pipeline

2020-07-16 10:28 UTC, radtriste commented
FYI https://kie.zulipchat.com/#narrow/stream/232676-kogito/topic/Failing.20examples.20on.20master

2020-07-17 14:00 UTC, radtriste commented
Jenkins, retest this please

2020-07-17 15:37 UTC, radtriste commented
Problem has been corrected.

@ricardozanini CI is ok

2020-07-17 19:56 UTC, ricardozanini commented on tests/features/kogito-data-index.feature
> +    Then container log should contain + exec java -XshowSettings:properties -Dquarkus.http.port=8080 -Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -jar /home/kogito/bin/kogito-data
> @ricardozanini How we could I pass kafka properties in data-index service. I tried with below cmd
> 
> `docker run -it -e QUARKUS_INFINISPAN_CLIENT_SERVER_LIST=172.18.0.1:11222 -e KAFKA_BOOTSTRAP_SERVERS=172.18.0.1:9092 quay.io/kiegroup/kogito-data-index:latest`
> 
> But data-index service still trying to connect localhost
> 
> `2020-07-16 04:23:16,241 WARN [org.apa.kaf.cli.NetworkClient] (vert.x-kafka-consumer-thread-4) [Consumer clientId=consumer-kogito-data-index-usertaskinstances-4, groupId=kogito-data-index-usertaskinstances] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available. 2020-07-16 04:23:16,242 WARN [org.apa.kaf.cli.NetworkClient] (vert.x-kafka-consumer-thread-4) [Consumer clientId=consumer-kogito-data-index-usertaskinstances-4, groupId=kogito-data-index-usertaskinstances] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected `

You need to pass all the boostrap messages see: https://github.com/quarkusio/quarkus/issues/7791

Once we migrate to Quarkus 1.6, only `KAFKA_BOOTSTRAP_SERVERS` will do.

2020-07-18 07:38 UTC, vaibhavjainwiz commented on tests/features/kogito-data-index.feature
> +    Then container log should contain + exec java -XshowSettings:properties -Dquarkus.http.port=8080 -Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -jar /home/kogito/bin/kogito-data
I had tried with below cmd but still its connecting with localhost
```docker run -it \
--env QUARKUS_INFINISPAN_CLIENT_SERVER_LIST=172.18.0.1:11222 \
--env MP_MESSAGING_OUTGOING_KOGITO_PROCESSINSTANCES_EVENTS_BOOTSTRAP_SERVERS=172.18.0.1:9092 \
--env MP_MESSAGING_OUTGOING_KOGITO_USERTASKINSTANCES_EVENTS_BOOTSTRAP_SERVERS=172.18.0.1:9092 \
quay.io/kiegroup/kogito-data-index:latest```

2020-07-19 13:41 UTC, Kaitou786 approved these changes

2020-07-20 06:10 UTC, radtriste commented on tests/features/kogito-data-index.feature
> +    Then container log should contain + exec java -XshowSettings:properties -Dquarkus.http.port=8080 -Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -jar /home/kogito/bin/kogito-data
@ricardozanini FYI, kogito-apps have been migrated to Quarkus 1.6.0 => https://github.com/kiegroup/kogito-apps/blob/e628f89c9755eb583c65eab8f2eb9e56592e56e7/pom.xml#L19 \o/

@vaibhavjainwiz If you try to set the `bootstrap servers` for all incoming queues, then you have some others as well to set as env variable: https://github.com/kiegroup/kogito-apps/blob/master/data-index/data-index-service/src/main/resources/application.properties#L24
you should try to update the data-index snapshot url in data-index module with `scripts/update-maven-information.sh` script and use the `KAFKA_BOOTSTRAP_SERVERS`. as it is not migrated to Quarkus 1.6.0, it should work

2020-07-20 10:02 UTC, ricardozanini commented
> Problem has been corrected.
> 
> @ricardozanini CI is ok

Thanks, I'm waiting for the Infinispan cekit tests to be back. :)

2020-07-20 12:12 UTC, r00ta commented on tests/features/kogito-data-index.feature
> +    Then container log should contain + exec java -XshowSettings:properties -Dquarkus.http.port=8080 -Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -jar /home/kogito/bin/kogito-data
Naive question: why do we need to remove `-Dquarkus.infinispan-client.use-auth=false`? Even if we don't need to specify it in the image definition, the jar will keep using it as well as kafka. It might be good to keep it as double check that the artifact is properly using infinispan

2020-07-20 12:29 UTC, r00ta commented
@vaibhavjainwiz Could you update also the README? It still contain some references to the deleted module

2020-07-20 13:16 UTC, r00ta commented on tests/features/kogito-data-index.feature
> +    Then container log should contain + exec java -XshowSettings:properties -Dquarkus.http.port=8080 -Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -jar /home/kogito/bin/kogito-data
Is it possible to inject the username and the password with enviroment variables as well?

2020-07-20 14:45 UTC, ricardozanini commented on tests/features/kogito-data-index.feature
> +    Then container log should contain + exec java -XshowSettings:properties -Dquarkus.http.port=8080 -Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -jar /home/kogito/bin/kogito-data
Yes, it's you have to define them as HotRod properties.

2020-07-21 13:53 UTC, r00ta commented on tests/features/kogito-data-index.feature
> +    Then container log should contain + exec java -XshowSettings:properties -Dquarkus.http.port=8080 -Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -jar /home/kogito/bin/kogito-data
Any update on this in general? I've quickly tried but as far as I can see Infinispan is not even logging a single message in both cases (with and without the property setted). I don't find how to check that infinispan is trying to connect to the correct host if it does not log anything :/

2020-07-21 14:47 UTC, vaibhavjainwiz commented on tests/features/kogito-data-index.feature
> +    Then container log should contain + exec java -XshowSettings:properties -Dquarkus.http.port=8080 -Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -jar /home/kogito/bin/kogito-data
When data-index-service is not able to connect with infinispan/kafka server when it start give error logs
for ex. 
```
2020-07-16 04:23:16,241 WARN [org.apa.kaf.cli.NetworkClient] (vert.x-kafka-consumer-thread-4) [Consumer clientId=consumer-kogito-data-index-usertaskinstances-4, groupId=kogito-data-index-usertaskinstances] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available. 2020-07-16 04:23:16,242 WARN [org.apa.kaf.cli.NetworkClient] (vert.x-kafka-consumer-thread-4) [Consumer clientId=consumer-kogito-data-index-usertaskinstances-4, groupId=kogito-data-index-usertaskinstances] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected
```

2020-07-21 14:52 UTC, vaibhavjainwiz commented on tests/features/kogito-data-index.feature
> +    Then container log should contain + exec java -XshowSettings:properties -Dquarkus.http.port=8080 -Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -jar /home/kogito/bin/kogito-data
@radtriste 
I had tried by changing data-index jar version to latest data-index-service-8.0.0-20200720.111834-374-runner.jar
but still data-index service is trying to connect with localhost for kafka
```
docker run -it -e QUARKUS_INFINISPAN_CLIENT_SERVER_LIST=172.18.0.1:11222 -e KAFKA_BOOTSTRAP_SERVERS=172.18.0.1:9092 quay.io/kiegroup/kogito-data-index:latest
```

I had also tried by defining all topic name but still same result
```
docker run -it -e QUARKUS_INFINISPAN_CLIENT_SERVER_LIST=172.18.0.1:11222 \
-e kafka.bootstrap.servers=172.18.0.1:9092 \
-e mp.messaging.incoming.kogito-processinstances-events.bootstrap.servers=172.18.0.1:9092 \
-e mp.messaging.incoming.kogito-usertaskinstances-events.bootstrap.servers=172.18.0.1:9092 \
-e mp.messaging.incoming.kogito-processdomain-events.bootstrap.servers=172.18.0.1:9092 \
-e mp.messaging.incoming.kogito-usertaskdomain-events.bootstrap.servers=172.18.0.1:9092 \
-e mp.messaging.incoming.kogito-jobs-events.bootstrap.servers=172.18.0.1:9092 \
quay.io/kiegroup/kogito-data-index:latest
```

2020-07-21 15:55 UTC, r00ta commented on tests/features/kogito-data-index.feature
> +    Then container log should contain + exec java -XshowSettings:properties -Dquarkus.http.port=8080 -Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -jar /home/kogito/bin/kogito-data
@vaibhavjainwiz I've just tried on kogito-apps master and it works 
![Screenshot from 2020-07-21 17-54-15](https://user-images.githubusercontent.com/18282531/88077209-4bb83200-cb7b-11ea-8582-9420909471da.png)
I'll try also with the image but it should be the same

2020-07-24 04:41 UTC, vaibhavjainwiz commented on tests/features/kogito-jobs-service.feature
> +    Then container log should contain + exec java -XshowSettings:properties -Dquarkus.http.port=8080 -jar /home/kogito/bin/kogito-jobs-service-runner.jar
done

2020-07-24 04:42 UTC, vaibhavjainwiz commented on tests/features/kogito-data-index.feature
> +    Then container log should contain + exec java -XshowSettings:properties -Dquarkus.http.port=8080 -Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -jar /home/kogito/bin/kogito-data
done

2020-07-24 04:47 UTC, vaibhavjainwiz commented
> @vaibhavjainwiz Could you update also the README? It still contain some references to the deleted module

done

2020-07-24 06:36 UTC, radtriste commented on modules/kogito-data-index/added/kogito-app-launch.sh
> +printenv
do we need this ?

2020-07-24 06:36 UTC, radtriste approved these changes

2020-07-24 08:08 UTC, vaibhavjainwiz commented on modules/kogito-data-index/added/kogito-app-launch.sh
> +printenv
I am printing all env variables because in feature test we are verifing value of these env var using `container log should contain` check. 
Previously we don't need to print env var because infinispan related variable are set at image level which are printed by default but now we are setting them in container env var which don't print by default.

2020-07-24 10:16 UTC, ricardozanini approved these changes
LGTM. One small thing only. @vaibhavjainwiz can you please quickly adjust this so we can cut for 0.13. Thanks!

2020-07-24 10:16 UTC, ricardozanini commented on tests/features/kogito-jobs-service.feature
> +      | quarkus.infinispan-client.use-auth        | true              |
```suggestion
      | QUARKUS_INFINISPAN_CLIENT_USE_AUTH        | true              |
```
Please keep the environment names on uppercase and underscores: https://stackoverflow.com/questions/2821043/allowed-characters-in-linux-environment-variable-names

2020-07-24 10:58 UTC, vaibhavjainwiz commented on tests/features/kogito-jobs-service.feature
> +      | quarkus.infinispan-client.use-auth        | true              |
I took reference for these properties from kogito-cloud-operator. In operator these properties are define in lower case. 
Now I changed them to uppercase.

done

2020-07-24 11:05 UTC, radtriste approved these changes

2020-07-24 12:00 UTC, r00ta approved these changes
Thanks!

2020-07-24 12:20 UTC, ricardozanini commented on tests/features/kogito-jobs-service.feature
> +      | quarkus.infinispan-client.use-auth        | true              |
Thanks, so It's wrong there also, could you please send a PR to fix it and to also remove those old properties that this module was expecting? You can open a new JIRA following up this one to remove the deprecated vars there and to fix this naming:
https://github.com/kiegroup/kogito-cloud-operator/blob/master/pkg/infrastructure/services/infinispan.go#L49-L54

2020-07-24 13:03 UTC, vaibhavjainwiz commented on tests/features/kogito-jobs-service.feature
> +      | quarkus.infinispan-client.use-auth        | true              |
I had created below Jira to incorporate this review comment:
https://issues.redhat.com/browse/KOGITO-2871

2020-07-24 13:51 UTC, merged