KOGITO-3013 - add monitoring dashboards scripts and tests
apache/incubator-kie-kogito-images pull request #209
Opened 2020-08-10 10:09 UTC by r00ta

STILL A DRAFT, description to be done

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

2020-08-12 09:06 UTC, r00ta commented
Jenkins test this

2020-08-12 12:59 UTC, r00ta commented on modules/kogito-monitoring/added/kogito-monitoring.sh
> +    local config_map=$(cat $KOGITO_HOME/podinfo/monitoringcm)
Dumb question: who should create the config maps in `podinfo`? I see that for the persistence the file is called `protobufcm`, is it something provided by kubernetes or what?

2020-08-12 13:24 UTC, ricardozanini requested changes
Hi! 
Many thanks for this PR, would be really nice to have dashboards provided by the Operator. I have a couple questions, tho:

1. Have you tested this script on an actual Kube cluster? I ask because I'm curious to see how this configMap gets updated with the dashboard and how the files are structured in there. 
2. These functions are almost the same we implemented in the protobuf use case. Do you mind refactoring to a common module and reuse them across both use cases: protobuf and dashboards? Will be easier to maintain.
3. You should also send a PR to the Operator to create the CM for you as we create the protobuf CM. Should be the CMs and not only one (like `myservice-files`) since the protobuf one needs to be mounted in the DataIndex as well, it's a different approach. What are you going to do with the information inside this CM? You will mount it in a Grafana resource provided by their operator? Would you give the CM for them to create the dashboard? What's the outcome of having this CM in the namespace?

Thanks, sorry for begin a PITA. :(

2020-08-12 13:24 UTC, ricardozanini commented on modules/kogito-monitoring/added/kogito-monitoring.sh
> +    local config_map=$(cat $KOGITO_HOME/podinfo/monitoringcm)
You need to have the operator to  create the configMap for you. This approach won't work if it's not there. See: https://docs.google.com/presentation/d/1Ji-Ob4KGU4j7rcxUMD_rp3l5xBfJAqmood4yZchEnFk/edit#slide=id.g8f45d2793a_0_45 Slide 6

And also have the Deployment to mount the podinfo for you as well.

2020-08-12 14:52 UTC, spolti commented on modules/kogito-monitoring/added/kogito-monitoring.sh
> +    printf "%s" "${body}" >$KOGITO_HOME/data/dashboards/configmap_patched.json
we could mock these requests using a little python server + bats tests.
here is an example:
https://github.com/jboss-container-images/jboss-kie-modules/blob/master/jboss-kie-kieserver/tests/bats/jboss-kie-kieserver-hooks.bats
You just need to have a real request to copy body and response to mock it.


@ricardozanini @radtriste 
we could move this mock server to a common repo and reuse, wdyt?

2020-08-12 14:53 UTC, spolti commented on modules/kogito-monitoring/added/kogito-monitoring.sh
> +    printf "%s" "${body}" >$KOGITO_HOME/data/dashboards/configmap_patched.json
PLus, instead duplicating code we could have a shared module and reuse it for protobuff and this new stuff.

2020-08-12 20:08 UTC, ricardozanini commented on modules/kogito-monitoring/added/kogito-monitoring.sh
> +    printf "%s" "${body}" >$KOGITO_HOME/data/dashboards/configmap_patched.json
^ READ MY COMMENTS! :laughing:

2020-10-06 15:53 UTC, spolti commented
@r00ta Hi, what is the status of this issue?

2020-10-29 15:26 UTC, spolti commented
@r00ta what is the status of this?

2020-10-29 15:27 UTC, spolti commented
the jira is closed, can we close it as well?

2020-11-24 16:09 UTC, closed without merging