KOGITO-3010 - Add kie-github-ci-bot to kogito-images repository
apache/incubator-kie-kogito-images pull request #211
Opened 2020-08-10 14:00 UTC by Kaitou786

Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

2020-08-10 14:06 UTC, spolti approved these changes

2020-08-10 14:39 UTC, Kaitou786 commented
Jenkins test this

2020-08-11 06:48 UTC, Kaitou786 commented
Jenkins test this

2020-08-11 09:08 UTC, Kaitou786 commented
Jenkins test this

2020-08-11 12:26 UTC, Kaitou786 commented
@spolti can be merged?

2020-08-11 18:44 UTC, spolti requested changes

2020-08-11 18:44 UTC, spolti commented on .github/bot-files/comments.yml
> +prCiTrigger: Jenkins test this
can we use /jenkins test like operator?

2020-08-11 18:55 UTC, Kaitou786 commented on .github/bot-files/comments.yml
> +prCiTrigger: Jenkins test this
Updated in the file, will update it in the pipeline as well

2020-08-11 19:03 UTC, Kaitou786 commented on .github/bot-files/comments.yml
> +prCiTrigger: Jenkins test this
Updated in the pipeline settings.

2020-08-11 19:04 UTC, Kaitou786 commented
@radtriste @sutaakar here also, we are following the same method as  operator so for triggering the pipeline for retest (in case of failure) use `/jenkins test`

2020-08-11 19:10 UTC, spolti commented
cool thanks.

2020-08-11 19:10 UTC, spolti approved these changes

2020-08-11 21:03 UTC, merged