[KOGITO-3467] Script to retrieve list of images
apache/incubator-kie-kogito-images pull request #249
Opened 2020-10-01 15:19 UTC by radtriste

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

2020-10-01 15:22 UTC, radtriste commented on tests/test-apps/clone-repo.sh
> +    cat ${HOME}/.m2/settings.xml
this will be corrected by https://github.com/kiegroup/kogito-images/pull/247

2020-10-02 06:54 UTC, radtriste commented
/jenkins test

2020-10-02 07:56 UTC, radtriste commented
/jenkins retest

2020-10-02 15:04 UTC, radtriste commented
/jenkins retest

2020-10-06 08:16 UTC, radtriste commented
/jenkins retest

2020-10-06 08:44 UTC, radtriste commented
/jenkins retest

2020-10-06 09:02 UTC, radtriste commented
/jenkins retest

2020-10-07 18:23 UTC, radtriste commented
/jenkins retest

2020-10-08 10:18 UTC, sutaakar approved these changes

2020-10-08 14:03 UTC, spolti requested changes

2020-10-08 14:03 UTC, spolti commented on Makefile
> +image_name=
the make auto complete will not work in this case, is it a good idea remove it and pass image name for single builds?

2020-10-08 14:03 UTC, spolti commented on Makefile
> +image_name=
we could maybe, add a option lile, make list-images.

2020-10-08 14:03 UTC, spolti commented
needs rebase.

2020-10-08 14:06 UTC, radtriste commented on Makefile
> +image_name=
you mean that one ? 
https://github.com/kiegroup/kogito-images/pull/249/files#diff-b67911656ef5d18c4ae36cb6741b7965R13

2020-10-08 14:07 UTC, spolti approved these changes

2020-10-08 14:07 UTC, spolti commented on Makefile
> +image_name=
yep, didn't see :)

2020-10-08 14:25 UTC, Kaitou786 approved these changes

2020-10-09 13:16 UTC, merged