[KOGITO-3553] - Ingnore Self signed certificates from maven while bui…
apache/incubator-kie-kogito-images pull request #253
Opened 2020-10-06 08:13 UTC by Kaitou786

…lding images

See: https://issues.redhat.com/browse/KOGITO-3553

Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

2020-10-06 11:46 UTC, vaibhavjainwiz approved these changes
LGTM

2020-10-06 12:22 UTC, Kaitou786 commented
/jenkins retest

2020-10-06 14:34 UTC, radtriste commented on modules/kogito-maven/3.6.x/added/configure-maven.sh
> +    unset IGNORE_SELF_SIGNED_CERTIFICATE
thinking that we should maybe prefix it with `MAVEN` as this is maven particularity.
wdyt ?

2020-10-06 14:35 UTC, radtriste commented on modules/kogito-maven/3.6.x/module.yaml
> +    value: "true"
`Default value is false` and then `value: "true"` :)
just put an example and not a value

2020-10-06 14:37 UTC, Kaitou786 commented on modules/kogito-maven/3.6.x/module.yaml
> +    value: "true"
Ah yes, :p, missed this, will change it

2020-10-06 14:38 UTC, Kaitou786 commented on modules/kogito-maven/3.6.x/added/configure-maven.sh
> +    unset IGNORE_SELF_SIGNED_CERTIFICATE
It is part of, maven module but I think as other vars have that as a prefix I'll add it to this one :)

2020-10-06 14:47 UTC, radtriste commented on modules/kogito-maven/3.6.x/added/configure-maven.sh
> +    configure_self_signed_certificates
```suggestion
    configure_maven_self_signed_certificates
```

2020-10-06 14:47 UTC, radtriste commented on modules/kogito-maven/3.6.x/added/configure-maven.sh
> +function configure_self_signed_certificates() {
```suggestion
function configure_maven_self_signed_certificates() {
```

2020-10-06 14:47 UTC, spolti requested changes

2020-10-06 14:47 UTC, spolti commented on modules/kogito-maven/3.6.x/added/configure-maven.sh
> +    unset MAVEN_IGNORE_SELF_SIGNED_CERTIFICATE
please keep in alphabetical order.

2020-10-06 14:47 UTC, spolti commented on modules/kogito-maven/3.6.x/added/configure-maven.sh
> +    configure_self_signed_certificates
I would change this function to ignore_self

2020-10-06 15:41 UTC, Kaitou786 commented
/jenkins retest

2020-10-06 15:51 UTC, spolti approved these changes

2020-10-07 04:39 UTC, Kaitou786 commented
/jenkins test

2020-10-07 10:42 UTC, radtriste commented
For the pipeline, I think we would need a new possibility in `scripts/update-tests.py` to disable certificate verification and that would add `| MAVEN_IGNORE_SELF_SIGNED_CERTIFICATE | true |` into the env of feature tests (see how it is done with MAVEN_REPO_URL for example).
And then in pipeline, before launching the tests, if `env.MAVEN_MIRROR_URL` is defined, then we should update the tests with the certificate disabled.

2020-10-07 10:57 UTC, Kaitou786 commented
> For the pipeline, I think we would need a new possibility in `scripts/update-tests.py` to disable certificate verification and that would add `| MAVEN_IGNORE_SELF_SIGNED_CERTIFICATE | true |` into the env of feature tests (see how it is done with MAVEN_REPO_URL for example).

Okay, will add the function, this should be part of this PR or another small JIRA?

2020-10-07 12:05 UTC, radtriste commented
I guess you can implement as part of this PR as it is related

2020-10-07 14:51 UTC, radtriste commented on Jenkinsfile
> +                    if(env.MAVEN_MIRROR_URL != ""){
please use single-quote

2020-10-07 14:51 UTC, radtriste commented on Jenkinsfile
> +                        sh "python3 scripts/update-tests.py --ignore-self-signed-cert=True"
you should not need to have `=True`. if option is there, then it is true

2020-10-07 14:51 UTC, radtriste commented on scripts/common.py
> +    Sets the enviornment variable to ignore the self-signed certificates in maven
```suggestion
    Sets the environment variable to ignore the self-signed certificates in maven
```

2020-10-07 14:51 UTC, radtriste commented on scripts/update-tests.py
> +    parser.add_argument('--ignore-self-signed-cert', dest='ignore_self_signed_cert', help='If set to true will relax the SSL for user-generated self-signed certificates', default=False)
see `--replace-jboss-repo` option to have similar behavior

2020-10-07 16:28 UTC, radtriste requested changes
gonna test this tomorrow

2020-10-07 16:28 UTC, radtriste commented on Jenkinsfile
> +                        sh "python3 scripts/update-tests.py --ignore-self-signed-cert"
as long as you are making usage of gstring (which means include a variable of a string with `${VAR}`), you should use single-quote ;)
```suggestion
                        sh 'python3 scripts/update-tests.py --ignore-self-signed-cert'
```

2020-10-07 16:28 UTC, radtriste commented on Jenkinsfile.deploy
> +                        updateTestsCommand += " --ignore-self-signed-cert"
```suggestion
                        updateTestsCommand += ' --ignore-self-signed-cert'
```

2020-10-07 16:42 UTC, Kaitou786 commented on Jenkinsfile
> +                        sh "python3 scripts/update-tests.py --ignore-self-signed-cert"
Ah okay, thanks, will keep in mind from next time :)

2020-10-08 09:53 UTC, radtriste approved these changes

2020-10-08 10:05 UTC, radtriste commented
Tested ok with a specific MAVEN_MIRROR_URL with self signed certificate

2020-10-08 13:41 UTC, merged