[KOGITO-3766] - Integrate Shellcheck for all shell scripts
apache/incubator-kie-kogito-images pull request #274
Opened 2020-11-05 06:19 UTC by Kaitou786

See: https://issues.redhat.com/browse/KOGITO-3766

Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

2020-11-05 11:05 UTC, Kaitou786 commented on modules/kogito-data-index-infinispan/added/kogito-app-launch.sh
>  exec java ${SHOW_JVM_SETTINGS} ${JAVA_OPTIONS} ${KOGITO_DATA_INDEX_PROPS} \
Shellcheck was disabled in this and similar line because it was creating `java -XshowSettings:properties '' '' -Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080 -jar /home/kogito/bin/data-index-service-infinispan.jar` when no options were passed. Also when there were option they were getting enclosed in `'` which was not working properly: `exec java -XshowSettings:properties -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080 -jar /home/kogito/bin/kogito-management-console-runner.jar ' -Dkogito.dataindex.http.url=http://localhost:8180' ''`

2020-11-05 14:40 UTC, spolti commented on modules/kogito-data-index-infinispan/added/kogito-app-launch.sh
>  exec java ${SHOW_JVM_SETTINGS} ${JAVA_OPTIONS} ${KOGITO_DATA_INDEX_PROPS} \
isn't there a way to mock these values on the shellcheck?

2020-11-05 15:10 UTC, Kaitou786 commented on modules/kogito-data-index-infinispan/added/kogito-app-launch.sh
>  exec java ${SHOW_JVM_SETTINGS} ${JAVA_OPTIONS} ${KOGITO_DATA_INDEX_PROPS} \
Wdym, mock what exactly?

2020-11-05 15:33 UTC, spolti commented on modules/kogito-data-index-infinispan/added/kogito-app-launch.sh
>  exec java ${SHOW_JVM_SETTINGS} ${JAVA_OPTIONS} ${KOGITO_DATA_INDEX_PROPS} \
thees envs ${SHOW_JVM_SETTINGS} ${JAVA_OPTIONS} ${KOGITO_DATA_INDEX_PROPS}

2020-11-23 17:12 UTC, radtriste commented on modules/kogito-data-index-common/configure
> +ADDED_DIR="${SCRIPT_DIR}"/added
```suggestion
ADDED_DIR="${SCRIPT_DIR}/added"
```

2020-11-23 17:12 UTC, radtriste commented on modules/kogito-data-index-common/configure
> +ADDED_DIR="${SCRIPT_DIR}"/added
is that accepted by shellcheck ?
If yes, then please proceed with other changes. I think it is more readable to have the whole string within the quote with placeholder ;)

2020-11-24 07:06 UTC, Kaitou786 commented on modules/kogito-data-index-common/configure
> +ADDED_DIR="${SCRIPT_DIR}"/added
Done

2020-11-24 16:18 UTC, spolti requested changes

2020-11-24 16:18 UTC, spolti commented on modules/kogito-data-index-infinispan/configure
> +ADDED_DIR="${SCRIPT_DIR}/added"
here, to keep a pattern, what shellcheck recommend? double qoute everything or just the env?

2020-11-24 16:18 UTC, spolti commented on modules/kogito-data-index-infinispan/configure
> +ADDED_DIR="${SCRIPT_DIR}/added"
asking because on each file we can find different usages, double quotes only on the env or on the entire line.
do you mind to check what is the correct way and apply in all places?

2020-11-24 16:24 UTC, Kaitou786 commented on modules/kogito-data-index-infinispan/configure
> +ADDED_DIR="${SCRIPT_DIR}/added"
Well both are considered good as seen [here](https://github.com/koalaman/shellcheck/wiki/SC2086#rationale) So after @radtriste I quoted everything, but the quotation of everything produced weird behavior on the shell commands. So I reverted them on shell commands. I think if we want the same pattern all over we would have to go with "Minimal Quoting"(only the envs). wdyt?

2020-11-24 16:29 UTC, radtriste commented on modules/kogito-data-index-infinispan/configure
> +ADDED_DIR="${SCRIPT_DIR}/added"
ok good then. For me it was more readable but if it does create conflicts, then set back to original

2020-11-24 16:30 UTC, spolti commented on modules/kogito-data-index-infinispan/configure
> +ADDED_DIR="${SCRIPT_DIR}/added"
minimal quoting sounds good to me.

2020-11-25 06:51 UTC, Kaitou786 commented on modules/kogito-data-index-infinispan/configure
> +ADDED_DIR="${SCRIPT_DIR}/added"
reverted back

2020-11-25 08:38 UTC, radtriste approved these changes

2020-11-25 14:06 UTC, spolti requested changes

2020-11-25 14:06 UTC, spolti commented on modules/kogito-launch-scripts/added/configure.sh
> +#!/bin/bash
do you mind to change all to "#!/usr/bin/env bash" ?

2020-11-25 15:04 UTC, Kaitou786 commented on modules/kogito-launch-scripts/added/configure.sh
> +#!/bin/bash
Changed

2020-11-25 15:49 UTC, Kaitou786 commented
Failing due to outage on quay :(

2020-11-25 18:01 UTC, Kaitou786 commented
/jenkins test

2020-11-26 18:39 UTC, spolti requested changes
great work!
just one last thing.

2020-11-26 18:39 UTC, spolti commented on modules/kogito-maven/3.6.x/added/configure-maven.sh
> +  # prefer old http_proxy_ format for username/password, but
why only this file had the indentation changed?

2020-11-27 04:36 UTC, Kaitou786 commented on modules/kogito-maven/3.6.x/added/configure-maven.sh
> +  # prefer old http_proxy_ format for username/password, but
Ah sorry, some misconfig in my IDE, should be okay now

2020-11-27 04:37 UTC, Kaitou786 commented on modules/kogito-maven/3.6.x/added/configure-maven.sh
> +  # prefer old http_proxy_ format for username/password, but
On second thoughts I'll see if there is anything like `go fmt ./...` for shell so we don't have this problem anymore and have standard formated code :)

2020-11-27 16:43 UTC, spolti requested changes

2020-11-27 16:43 UTC, spolti commented on modules/kogito-maven/3.6.x/added/configure-maven.sh
> +      single_repo_id=$(_maven_find_env "MAVEN_REPO_ID" "repo-$(_generate_random_id)")
indentation has changed here as well.
can't shellcheck verify if the indentation is correct as well?

2020-11-27 16:43 UTC, spolti commented on modules/kogito-maven/3.6.x/added/configure-maven.sh
> +      multi_repo_url=$(_maven_find_prefixed_env "${multi_repo_prefix}" "MAVEN_REPO_URL")
here too.

2020-11-30 04:20 UTC, Kaitou786 commented on modules/kogito-maven/3.6.x/added/configure-maven.sh
> +      single_repo_id=$(_maven_find_env "MAVEN_REPO_ID" "repo-$(_generate_random_id)")
I believe all the indentation should be okay for now. and no, shellcheck doesn't have that, I'll try to find a alternate tool which takes care of formatting for us :)

2020-11-30 16:35 UTC, spolti approved these changes

2020-11-30 16:36 UTC, merged