[KOGITO-186] - https://issues.jboss.org/browse/KOGITO-186
apache/incubator-kie-kogito-images pull request #38
Opened 2019-09-10 20:28 UTC by spolti

Signed-off-by: Filippe Spolti <fspolti@redhat.com>

2019-09-10 20:47 UTC, spolti commented
split the images into two different will be better to keep the native image smaller.

2019-09-11 21:13 UTC, ricardozanini requested changes
Looks good! Many thanks for helping with this! Now I can safely test on my side with Operators and CLI

2019-09-11 21:13 UTC, ricardozanini commented on s2i/kogito-quarkus-ubi8-s2i-overrides.yaml
> +- name: NONNATIVE
Shouldn't be `NATIVE`?

2019-09-11 21:13 UTC, ricardozanini commented on s2i/modules/kogito-data-index/module.yaml
>    md5: 12126dee53783fe09279f46f299611a1
I guess this build won't work unless we have the jar file in the repo. Let's wait until 0.4.0 release to change this line.

2019-09-11 21:13 UTC, ricardozanini commented on s2i/modules/kogito-quarkus-ubi8-s2i/README.md
> +To perform non native builds set the env **NONNATIVE** to **true**.
`NATIVE`?

2019-09-11 21:13 UTC, ricardozanini commented on s2i/tests/features/kogito-quarkus-index.feature
> +    Then run sh -c 'ls /home/kogito/bin/data-index-service-*-runner.jar' in container and immediately check its output for /home/kogito/bin/data-index-service-0.4.0-runner.jar
I guess this scenario will fail also. Can't we just look for a file starting with `/home/kogito/bin/data-index-service`?

2019-09-11 21:15 UTC, spolti commented on s2i/modules/kogito-data-index/module.yaml
>    md5: 12126dee53783fe09279f46f299611a1
good catch, I replaced everything from 0.3.0 to 0.4.0, will undo this.

2019-09-11 21:28 UTC, spolti commented on s2i/kogito-quarkus-ubi8-s2i-overrides.yaml
> +- name: NONNATIVE
correct.

2019-09-11 21:30 UTC, spolti commented on s2i/modules/kogito-quarkus-ubi8-s2i/README.md
> +To perform non native builds set the env **NONNATIVE** to **true**.
yes.

2019-09-11 21:32 UTC, spolti commented on s2i/tests/features/kogito-quarkus-index.feature
> +    Then run sh -c 'ls /home/kogito/bin/data-index-service-*-runner.jar' in container and immediately check its output for /home/kogito/bin/data-index-service-0.4.0-runner.jar
the module is copying the jar file as  data-index-service-0.3.0-runner.jar

2019-09-11 21:40 UTC, ricardozanini approved these changes

2019-09-11 21:55 UTC, merged