[KOGITO-3507] Introducing new module for custom Java Truststore confi…
apache/incubator-kie-kogito-images pull request #404
Opened 2021-03-19 21:40 UTC by ricardozanini

…guration

See: https://issues.redhat.com/browse/KOGITO-3507

In this PR we introduce the ability to start the Kogito runtime JVM process with a custom JKS, mounted as a volume in the current container.

TODO:
- [ ] Integration tests with the Operator
- [ ] Documentation

Signed-off-by: Ricardo Zanini <zanini@redhat.com>

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

2021-03-25 16:52 UTC, sutaakar commented on modules/kogito-custom-truststore/added/configure-custom-truststore.sh
> +    unset CUSTOM_TRUSTSTORE_PATH
Should it be here also `CUSTOM_TRUSTSTORE` (and below too)?

2021-03-25 16:56 UTC, sutaakar commented on modules/kogito-custom-truststore/added/configure-custom-truststore.sh
> +function prepareEnv() {
Should this function be used just for env variables which are supplied by user?
At least that is how I understand it based on other modules (like https://github.com/kiegroup/kogito-images/blob/7056d6185711d603e1a32cc326feaa163ba91d8e/modules/kogito-trusty-common/added/launch/kogito-trusty.sh or https://github.com/kiegroup/kogito-images/blob/7ecaaf705b380ad3d6012307712a5d5bfc9b8d9b/modules/kogito-explainability/added/launch/kogito-explainability.sh)
Though I may be wrong.

2021-03-25 17:14 UTC, sutaakar commented on modules/kogito-runtime-native/added/kogito-app-launch.sh
> +    CUSTOM_TRUSTSTORE_ARGS="-Djavax.net.ssl.trustStore=${KOGITO_HOME}/cacerts"
I am not sure if the configuration will work for native images.
Based on https://quarkus.io/guides/native-and-ssl#the-truststore-path it seems that the truststore has to be provided for native build, during runtime the properties are ignored.

2021-03-25 18:56 UTC, radtriste approved these changes
ok by me once Karel comments are handled

2021-03-25 19:42 UTC, ricardozanini commented on modules/kogito-runtime-native/added/kogito-app-launch.sh
> +    CUSTOM_TRUSTSTORE_ARGS="-Djavax.net.ssl.trustStore=${KOGITO_HOME}/cacerts"
It never worked then (see that we already were passing the property).

I opened [KOGITO-4795](https://issues.redhat.com/browse/KOGITO-4795) to track this down in another JIRA, since this won't work despite the approach we take.
For this one, I'll revert the changes and add a note to the docs that we don't support TrustStore customizations due to the nature of native compilation.

2021-03-25 19:44 UTC, ricardozanini commented on modules/kogito-custom-truststore/added/configure-custom-truststore.sh
> +function prepareEnv() {
I didn't get it either. @spolti, can you shed light? It's working, but if it's like @sutaakar is saying, I can easily make this change.

2021-03-25 21:09 UTC, spolti commented on modules/kogito-custom-truststore/added/configure-custom-truststore.sh
> +function prepareEnv() {
@sutaakar is correct.

2021-03-25 21:24 UTC, spolti requested changes
thanks very much.
made just a few observations.

2021-03-25 21:24 UTC, spolti commented on modules/kogito-custom-truststore/README.md
> +[Keystore Explorer](https://keystore-explorer.org/) is a great tool to manipulate JKS
as we're talking about java isn't better refer to keytool?

2021-03-25 21:24 UTC, spolti commented on modules/kogito-custom-truststore/added/configure-custom-truststore.sh
> +    unset CUSTOM_TRUSTSTORE_PATH
-e CUSTOM_TRUSTSTORE=cacerts \
    -e CUSTOM_TRUSTSTORE_PASSWORD=changeit \

these should be here

2021-03-25 21:24 UTC, spolti commented on modules/kogito-custom-truststore/module.yaml
> +    - name: org.kie.kogito.logging
all images should be installing it. can be removed. from here

2021-03-25 21:24 UTC, spolti commented on modules/kogito-custom-truststore/module.yaml
> +    value: ""
can be removed.

2021-03-25 21:24 UTC, spolti commented on modules/kogito-custom-truststore/module.yaml
> +    value: ""
same

2021-03-25 21:24 UTC, spolti commented on modules/kogito-custom-truststore/tests/bats/kogito-custom-truststore.bats
> +    prepareEnv
isn't better just run configure_custom_truststore instead of executing these three functions?

2021-03-25 21:24 UTC, spolti commented on modules/kogito-data-index-common/module.yaml
> +modules:
I'd prefer to keep it on image-override yaml for the target image that will need it, easier to keep track of what is being installed.

2021-03-25 21:24 UTC, spolti commented on modules/kogito-explainability/module.yaml
> +modules:
same here and the others

2021-03-25 21:24 UTC, spolti commented on tests/features/trusty/kogito-trusty-common.feature
> +    Then container log should contain ERROR ---> A custom truststore was specified
use full msg?

2021-03-25 21:24 UTC, spolti commented on modules/kogito-custom-truststore/added/configure-custom-truststore.sh
> +    export CUSTOM_TRUSTSTORE_ARGS=""
I would need to test to make sure, but I guess this function and the export be removed, the envs defined here, even without exporting it will be available on kogito-launch script.

2021-03-25 21:28 UTC, ricardozanini commented on modules/kogito-custom-truststore/README.md
> +[Keystore Explorer](https://keystore-explorer.org/) is a great tool to manipulate JKS
KeyStore Explorer has a nice UI, that's why.

2021-03-26 09:57 UTC, Kaitou786 approved these changes
lgtm. once comments are addressed :)

2021-03-26 10:29 UTC, sutaakar approved these changes
Looks good to me when comments are addressed

2021-03-26 13:11 UTC, ricardozanini commented on modules/kogito-custom-truststore/tests/bats/kogito-custom-truststore.bats
> +    prepareEnv
This way we replicate the same behavior of the `CONFIGURE_SCRIPTS`.

2021-03-26 13:17 UTC, ricardozanini commented on modules/kogito-custom-truststore/added/configure-custom-truststore.sh
> +    export CUSTOM_TRUSTSTORE_ARGS=""
Let's keep the way it's now since it's working and the env **is not available** in the container. That's a good thing.

2021-03-26 13:19 UTC, ricardozanini commented on tests/features/trusty/kogito-trusty-common.feature
> +    Then container log should contain ERROR ---> A custom truststore was specified
I'll use the full path only for the first message. The second is too long and has a line break. The first one already includes everything we need to know, like the path and the file name.

2021-03-26 14:57 UTC, ricardozanini commented
@spolti can you take a look, please?

2021-03-26 16:47 UTC, spolti requested changes
nice work, just a very small thing :)

2021-03-26 16:47 UTC, spolti commented on tests/features/common-custom-truststore.feature
> +@wip
letfover?

2021-03-26 17:13 UTC, ricardozanini commented on tests/features/common-custom-truststore.feature
> +@wip
GAAAAAAAAAAAAAAAAAAAA

2021-03-26 17:19 UTC, spolti approved these changes

2021-03-26 18:08 UTC, merged