[KOGITO-4721] - Create Image distribution for Job Service MongoDB
apache/incubator-kie-kogito-images pull request #472
Opened 2021-05-17 22:03 UTC by spolti

Signed-off-by: spolti <fspolti@redhat.com>
See: https://issues.redhat.com/browse/KOGITO-4721

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

2021-05-18 07:52 UTC, vaibhavjainwiz approved these changes

2021-05-18 13:22 UTC, radtriste requested changes
we need to keep the `kogito-jobs-service` in-memory as well (using `jobs-service-common` runner jar)

2021-05-18 16:03 UTC, sutaakar approved these changes

2021-05-18 18:11 UTC, radtriste approved these changes
lgtm
one minor thing

2021-05-18 18:11 UTC, radtriste commented on README.md
> +is not set to *true* it will use the default implementation (in-memory).
leftover ?

2021-05-18 18:16 UTC, radtriste commented on modules/kogito-jobs-service-ephemeral/module.yaml
> +    url: https://repository.jboss.org/nexus/content/groups/public/org/kie/kogito/jobs-service-common/2.0.0-SNAPSHOT/jobs-service-common-2.0.0-20210429.061304-7-runner.jar
`20210429` is pretty old. can't we have something newer ?

2021-05-18 20:49 UTC, spolti commented on README.md
> +is not set to *true* it will use the default implementation (in-memory).
yes, thanks for spotting it.

2021-05-18 20:50 UTC, spolti commented
@ricardozanini have spotted a issue that is preventing the images to get built, PR is in place waiting for CI to pass:
https://github.com/kiegroup/kogito-images/pull/474

2021-05-19 04:39 UTC, cristianonicolai approved these changes

2021-05-20 13:33 UTC, merged