[KOGITO-5710] - Add support for Kogito Quarkus runtime native image
apache/incubator-kie-kogito-images pull request #671
Opened 2021-08-18 19:51 UTC by spolti

Signed-off-by: spolti <fspolti@redhat.com>
See: https://issues.redhat.com/browse/KOGITO-5710

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a testcase that verifies it
- [] You've tested the new feature/bug fix in an actual OpenShift cluster

2021-08-18 19:58 UTC, spolti commented
@radtriste  do you know why the examples is failing to get built?

2021-08-19 07:10 UTC, radtriste commented on rhpam-kogito-imagestream.yaml
> +            tags: rhpam-kogito,runtime,kogito,quarkus
```suggestion
            tags: rhpam-kogito,runtime,kogito,quarkus,native
```
?

2021-08-19 07:10 UTC, radtriste commented on rhpam-kogito-runtime-native-rhel8-overrides.yaml
> +    value: "RHPAM Kogito based on Quarkus native image"
```suggestion
    value: "Red Hat build of Kogito runtime based on Quarkus native image"
```

2021-08-19 07:10 UTC, radtriste commented on rhpam-kogito-runtime-native-rhel8-overrides.yaml
> +    value: "builder,runtime,kogito,quarkus,native"
```suggestion
    value: "rhpam-kogito,runtime,kogito,quarkus,native"
```

2021-08-19 07:10 UTC, radtriste commented on rhpam-kogito-runtime-native-rhel8-overrides.yaml
> +  - name: BINARY_BUILD
I guess `BINARY_BUILD` should always be `true` for now ?

2021-08-19 07:10 UTC, radtriste commented on rhpam-kogito-runtime-native-rhel8-overrides.yaml
> +  extra_dir: osbs-extra/rhpam-kogito-runtime-jvm-rhel8
```suggestion
  extra_dir: osbs-extra/rhpam-kogito-runtime-native-rhel8
```

2021-08-19 07:10 UTC, radtriste commented on tests/features/kogito-common-runtime-native.feature
> +  Scenario: Verify if the binary build is finished as expected and if it is listening on the expected port with quarkus native
Could you also delete this scenario from `tests/features/kogito-runtime-native.feature` file ?

2021-08-19 07:26 UTC, radtriste commented
Seems that the `nightly-main` branch has not been updated in the past days due to test failures on examples with onboarding.
It should be solved today with https://github.com/kiegroup/kogito-examples/pull/849

2021-08-19 09:42 UTC, radtriste commented
Jenkins retest this

2021-08-19 09:46 UTC, radtriste commented
Jenkins retest this

2021-08-19 11:45 UTC, radtriste commented
Could the error be related to https://kie.zulipchat.com/#narrow/stream/232676-kogito/topic/jobs.20service.20pg.20exits.20with.20no.20error ?

2021-08-19 12:46 UTC, spolti commented on rhpam-kogito-runtime-native-rhel8-overrides.yaml
> +  extra_dir: osbs-extra/rhpam-kogito-runtime-jvm-rhel8
oops, too many copy and paste :)

2021-08-19 13:47 UTC, spolti commented on rhpam-kogito-runtime-native-rhel8-overrides.yaml
> +  - name: BINARY_BUILD
it makes sense.

2021-08-20 08:43 UTC, radtriste requested changes

2021-08-20 08:43 UTC, radtriste commented on tests/features/kogito-common-runtime-native.feature
> +  Scenario: Verify if the binary build is finished as expected and if it is listening on the expected port with quarkus native
Forgot that one ?

2021-08-20 08:43 UTC, radtriste commented on osbs-extra/rhpam-kogito-runtime-native-rhel8/gating.yaml
> +id: "cvp-rhpam-kogito-runtime-jvm"
```suggestion
id: "cvp-rhpam-kogito-runtime-native"
```

2021-08-20 12:43 UTC, sutaakar approved these changes

2021-08-20 17:58 UTC, spolti commented on tests/features/kogito-common-runtime-native.feature
> +  Scenario: Verify if the binary build is finished as expected and if it is listening on the expected port with quarkus native
what do you mean?
This test is valid for both images.

2021-08-23 07:03 UTC, radtriste commented on tests/features/kogito-common-runtime-native.feature
> +  Scenario: Verify if the binary build is finished as expected and if it is listening on the expected port with quarkus native
yes it is.
But now you have 2 scenarios with same name and content: `Verify if the binary build is finished as expected and if it is listening on the expected port with quarkus native`
As you moved that one to common file, can you remove the scenario from the original file, aka `tests/features/kogito-runtime-native.feature` as it makes no sense to test it twice ?

2021-08-23 07:16 UTC, radtriste commented on tests/features/kogito-common-runtime-native.feature
> +  Scenario: Verify if the binary build is finished as expected and if it is listening on the expected port with quarkus native
See https://github.com/kiegroup/kogito-images/pull/671/commits/9a46bd8daeb34cb417441d91050155a8e6fafff2 that I added to PR

2021-08-23 07:16 UTC, radtriste approved these changes
you can merge if https://github.com/kiegroup/kogito-images/pull/671/commits/9a46bd8daeb34cb417441d91050155a8e6fafff2 is ok for you

2021-08-23 13:13 UTC, merged