[KOGITO-676] - Create image and image stream for Kogito Job Service
apache/incubator-kie-kogito-images pull request #70
Opened 2019-12-05 21:56 UTC by spolti

Signed-off-by: Filippe Spolti <fspolti@redhat.com>

2019-12-05 21:58 UTC, spolti commented
Just for review, please do not merge yet, still need to update the README files.

2019-12-05 23:02 UTC, ricardozanini requested changes
Looks good to me, minor comments.

2019-12-05 23:02 UTC, ricardozanini commented on s2i/modules/kogito-jobs-service/added/kogito-app-launch.sh
> +exec java ${SHOW_JVM_SETTINGS} ${KOGITO_JOBS_PROPS} -jar $KOGITO_HOME/bin/kogito-jobs-service-runner.jar
We might need support for `JAVA_OPTIONS` like we have in Data Index and the runtimes to keep cohesion between the images.

2019-12-05 23:02 UTC, ricardozanini commented on s2i/modules/kogito-jobs-service/added/launch/kogito-jobs-service.sh
> +        KOGITO_JOBS_PROPS="${KOGITO_JOBS_PROPS} -Dkogito.job-service.persistence=infinispan"
Maybe changing this property name to `JAVA_OPTIONS`.

2019-12-05 23:02 UTC, ricardozanini commented on s2i/modules/kogito-jobs-service/module.yaml
> +  md5: ad2e7347564bdc031db92f6e1f6762e4
I guess the 0.6.0 artefact is available.

2019-12-06 11:20 UTC, mswiderski reviewed
is this already available in quay.io to try it out?

2019-12-06 11:20 UTC, mswiderski commented on s2i/modules/kogito-jobs-service/module.yaml
> +  md5: ad2e7347564bdc031db92f6e1f6762e4
the problem is we don't, it was not storing the -runner.jar in maven repo, was fixed after 0.6.0

2019-12-06 11:20 UTC, mswiderski commented on s2i/modules/kogito-jobs-service/added/launch/kogito-jobs-service.sh
> +        KOGITO_JOBS_PROPS="${KOGITO_JOBS_PROPS} -Dkogito.job-service.persistence=infinispan"
and how about location and auth info for Infinispan? and maybe more generic question, do we prefer to set them via system proper or environment variables?

2019-12-06 11:52 UTC, tiagodolphine reviewed
I inserted some comments mainly regarding the config property to enable infinispan.

2019-12-06 11:52 UTC, tiagodolphine commented on s2i/kogito-jobs-service-overrides.yaml
> +  description: "By default the Jobs services runs on memory only, if persistence is needed then set it to true. (Sets the property kogito.job-service.persistence=infinispan)"
The config property was changed `kogito.job-service.*` to **`kogito.jobs-service.*`**

2019-12-06 11:52 UTC, tiagodolphine commented on s2i/modules/kogito-jobs-service/added/launch/kogito-jobs-service.sh
> +        KOGITO_JOBS_PROPS="${KOGITO_JOBS_PROPS} -Dkogito.job-service.persistence=infinispan"
The config property was changed `kogito.job-service.*` to **`kogito.jobs-service.*`**

2019-12-06 11:52 UTC, tiagodolphine commented on s2i/modules/kogito-jobs-service/tests/bats/kogito-jobs-service.bats
> +    expected=" -Dkogito.job-service.persistence=infinispan"
The config property was changed `kogito.job-service.*` to **`kogito.jobs-service.*`**

2019-12-06 11:52 UTC, tiagodolphine commented on s2i/modules/kogito-jobs-service/module.yaml
> +  md5: ad2e7347564bdc031db92f6e1f6762e4
yeah, indeed... it is only available on the current snapshots and after 0.6.0 since we fixed to generate the runner artifact after the 0.6.0 release.

2019-12-06 12:51 UTC, ricardozanini commented on s2i/modules/kogito-jobs-service/added/launch/kogito-jobs-service.sh
> +        KOGITO_JOBS_PROPS="${KOGITO_JOBS_PROPS} -Dkogito.job-service.persistence=infinispan"
@mswiderski I've already talked about Infinispan with @spolti offline. He will add the system properties injected via environment variables by the operator like we're doing on Data Index to keep cohesion. It's a "auth-infinispan-module" in the images.

2019-12-06 12:52 UTC, ricardozanini commented on s2i/modules/kogito-jobs-service/module.yaml
> +  md5: ad2e7347564bdc031db92f6e1f6762e4
We can't have a 0.6.0 runner? I'm not a fan of adding a SNAPSHOT version in the final 0.6.0 image.

2019-12-06 12:53 UTC, ricardozanini commented
@spolti also the Jenkins job is failing. :-(

2019-12-06 13:58 UTC, spolti commented on s2i/modules/kogito-jobs-service/module.yaml
> +  md5: ad2e7347564bdc031db92f6e1f6762e4
this URL does n ot exist yet, I just add it there to be able to build the image, I built the jobs service manually and add to my local cekit cache until there the jar is not available on the maven repo.

2019-12-06 13:58 UTC, spolti commented on s2i/kogito-jobs-service-overrides.yaml
> +  description: "By default the Jobs services runs on memory only, if persistence is needed then set it to true. (Sets the property kogito.job-service.persistence=infinispan)"
I copied the prop from jira, thanks for point it out.

2019-12-06 13:59 UTC, spolti commented
@ricardozanini Jenkins is probably failing because there is no jobs-services artifact available on maven.

2019-12-06 14:01 UTC, spolti commented on s2i/modules/kogito-jobs-service/added/kogito-app-launch.sh
> +exec java ${SHOW_JVM_SETTINGS} ${KOGITO_JOBS_PROPS} -jar $KOGITO_HOME/bin/kogito-jobs-service-runner.jar
> is this already available in quay.io to try it out?

Yes, but I'll have to update it to fix the persistence props as Tiago pointed out.

quay.io/kiegroup/kogito-jobs-service:0.6.0-rc3

2019-12-06 14:04 UTC, spolti commented on s2i/modules/kogito-jobs-service/added/launch/kogito-jobs-service.sh
> +        KOGITO_JOBS_PROPS="${KOGITO_JOBS_PROPS} -Dkogito.job-service.persistence=infinispan"
Not really, I don't want to mix java properties and app properties. probably I'll add a script to the java module to take care only of java options and import it when needed.

about the infinispan, yes, will create a common module and/or configuration script after the data-index re-factoring is done.

2019-12-06 14:06 UTC, spolti commented
@mswiderski Yes, the image is available already.
But I'll have to update it to fix the persistence props as Tiago pointed out.

quay.io/kiegroup/kogito-jobs-service:0.6.0-rc3

2019-12-06 14:06 UTC, spolti commented on s2i/modules/kogito-jobs-service/added/launch/kogito-jobs-service.sh
> +        KOGITO_JOBS_PROPS="${KOGITO_JOBS_PROPS} -Dkogito.job-service.persistence=infinispan"
Not really, I don't want to mix java properties and app properties. probably I'll add a script to the java module to take care only of java options and import it when needed.

about the infinispan, yes, will create a common module and/or configuration script after the data-index re-factoring is done.

2019-12-06 14:07 UTC, spolti commented on s2i/modules/kogito-jobs-service/added/kogito-app-launch.sh
> +exec java ${SHOW_JVM_SETTINGS} ${KOGITO_JOBS_PROPS} -jar $KOGITO_HOME/bin/kogito-jobs-service-runner.jar
will add later.

2019-12-06 21:22 UTC, ricardozanini approved these changes
LGTM

2019-12-09 14:06 UTC, merged