FAI-606: trusty-storage: Create image for trusty-storage-postgreSQL
apache/incubator-kie-kogito-images pull request #758
Opened 2021-09-29 14:15 UTC by manstis

See https://issues.redhat.com/browse/FAI-606

This is a case of "Monkey see, Monkey do".... 

This entire PR is based simply on copying and pasting the good work done by others.

I don't know how to run it, check it or fix it (if broken) so please be gentle with me.

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a testcase that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster

2021-09-29 14:16 UTC, manstis commented on modules/kogito-trusty-postgresql/module.yaml
> +    md5: d2f3ab56132e85140d5a9ec11a96fe1b
I assume I can get the concrete Maven `version` and md5 once the underlying JARs have been published.

This depends on https://github.com/kiegroup/kogito-apps/pull/1032 being merged and a release completed.

2021-09-29 14:17 UTC, manstis commented
@r00ta IDK who else should review this.. hopefully somebody who knows more then me :-)

2021-09-29 14:29 UTC, spolti requested changes

2021-09-29 14:29 UTC, spolti commented on README.md
> +The Trusty Service depends on a running Infinispan, Redis Server or PostgreSQL RDBMS.
what RDBMS means?

2021-09-29 14:29 UTC, spolti commented on tests/features/trusty/kogito-trusty-common.feature
> +@quay.io/kiegroup/kogito-trusty-postgresql
please, remove the "Scenario: Verify if a custom certificate is correctly handled" from this Feature as it is already executed as part of the Common tests for Custom TrustStore configuration feature.

2021-09-29 14:50 UTC, manstis commented on README.md
> +The Trusty Service depends on a running Infinispan, Redis Server or PostgreSQL RDBMS.
**R**elational **D**ata**B**ase **M**anagemnet **S**ystem

2021-09-29 14:52 UTC, manstis commented on tests/features/trusty/kogito-trusty-common.feature
> +@quay.io/kiegroup/kogito-trusty-postgresql
Done (in new commit). Thank-you.

2021-09-30 06:44 UTC, radtriste commented on modules/kogito-trusty-postgresql/module.yaml
> +    md5: d2f3ab56132e85140d5a9ec11a96fe1b
Can you please mention it in the description as a dependent PR ?

2021-09-30 11:57 UTC, manstis commented
Build fails (to be expected) due to:
```
DEBUG Downloading from 'https://repository.jboss.org/nexus/content/groups/public/org/kie/kogito/trusty-service-postgresql/2.0.0-SNAPSHOT/trusty-service-postgresql-2.0.0-20210927.055328-168-runner.jar' as ./cache/8379e495-e922-4b24-bd66-df681ad3956b
...
ERROR ("Error copying resource: 'trusty-service-postgresql-runner.jar'. See logs for more info.", <HTTPError 404: 'Not Found'>)
```
See [here](https://github.com/kiegroup/kogito-images/pull/758#discussion_r718562384).

2021-09-30 13:16 UTC, sutaakar approved these changes

2021-10-05 06:29 UTC, radtriste commented
artifact should be available in the next hour(s). See nightly: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/nightly/job/kogito-nightly/

2021-10-05 06:40 UTC, radtriste approved these changes
good when artifact set and PR check green

2021-10-05 08:10 UTC, manstis commented
@spolti @sutaakar @radtriste I've now also incorporated the changes in #759 (since this PR contains a new module).

I still have to update the Nexus artifact snapshot version and MD5 after the dependency is published to Nexus.

I'll update the status of this PR when complete.

2021-10-05 12:04 UTC, radtriste commented
> @spolti @sutaakar @radtriste I've now also incorporated the changes in #759 (since this PR contains a new module).
> 
> I still have to update the Nexus artifact snapshot version and MD5 after the dependency is published to Nexus.
> 
> I'll update the status of this PR when complete.

@manstis artifact is now available: https://origin-repository.jboss.org/nexus/content/groups/public/org/kie/kogito/trusty-service-postgresql/2.0.0-SNAPSHOT/ ;)

2021-10-06 07:46 UTC, radtriste commented on modules/kogito-trusty-postgresql/module.yaml
> +    url: https://repository.jboss.org/nexus/service/local/repositories/snapshots/content/org/kie/kogito/trusty-service-postgresql/2.0.0-SNAPSHOT/trusty-service-postgresql-2.0.0-20211005.110152-1.jar
Please use same url as other modules

```suggestion
    url: https://repository.jboss.org/nexus/content/groups/public/org/kie/kogito/trusty-service-postgresql/2.0.0-SNAPSHOT/trusty-service-postgresql-2.0.0-20211005.110152-1.jar
```

2021-10-06 08:59 UTC, manstis commented
Jenkins retest this

2021-10-06 09:05 UTC, manstis commented
@radtriste Thank-you for fixing the URL.

2021-10-06 09:49 UTC, radtriste commented on tests/features/trusty/kogito-trusty-postgresql.feature
> +    Then container log should contain -Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080 -jar /home/trusty-service-postgresql-runner.jar
```suggestion
    Then container log should contain -Dtrusty.explainability.enabled=true -Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080 -jar /home/trusty-service-postgresql-runner.jar
```
?

2021-10-06 09:49 UTC, radtriste commented on tests/features/trusty/kogito-trusty-postgresql.feature
> +    Then container log should contain -Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080 -jar /home/trusty-service-postgresql-runner.jar
See https://github.com/kiegroup/kogito-images/pull/758/files#diff-8b9434e3eb01de8ae3d8b7e019728fd29769613d8dbcaafb0cd8afc8f2671e1bR9

2021-10-06 10:05 UTC, manstis commented on tests/features/trusty/kogito-trusty-postgresql.feature
> +    Then container log should contain -Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080 -jar /home/trusty-service-postgresql-runner.jar
@radtriste I really appreciate you keeping an eye on this. Thank-you.

IDK if we need to duplicate the check for `-Dtrusty.explainability.enabled=true` since it's in the common test you link?

I was asked to remove a similar [duplication](https://github.com/kiegroup/kogito-images/pull/758#discussion_r718578199) from this PR.

BTW I don't get any (email) notifications for this PR. I just pass by every now and again to check.

Do I need to be added to a list somewhere for this repo?

2021-10-06 10:28 UTC, radtriste commented on tests/features/trusty/kogito-trusty-postgresql.feature
> +    Then container log should contain -Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080 -jar /home/trusty-service-postgresql-runner.jar
@manstis I guess this is a GH configuration for your account on this repo as when fail comment is written, you should receive a mail (I do)

2021-10-06 10:32 UTC, radtriste commented on modules/kogito-trusty-postgresql/module.yaml
> +    md5: c9310c2fbdd0a20e6a14afea2acb6415
Just noticed it should be the runner jar ...

```suggestion
    url: https://repository.jboss.org/nexus/content/groups/public/org/kie/kogito/trusty-service-postgresql/2.0.0-SNAPSHOT/trusty-service-postgresql-2.0.0-20211005.110152-1-runner.jar
    md5: 40991d7f2a95cf313bb973b7ccbe85c8
```

2021-10-06 12:20 UTC, spolti commented on tests/features/trusty/kogito-trusty-postgresql.feature
> +    Then container log should contain -Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080 -jar /home/trusty-service-postgresql-runner.jar
Also please add this image on the comom jvm test feature.

2021-10-06 19:00 UTC, manstis commented
Jenkins retest this

2021-10-07 07:10 UTC, manstis commented on tests/features/trusty/kogito-trusty-postgresql.feature
> +    Then container log should contain -Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080 -jar /home/trusty-service-postgresql-runner.jar
Sorry @spolti, could you please be a little more specific? I am not overly familiar with this repository.

2021-10-07 07:11 UTC, manstis commented
Jenkins retest this

2021-10-07 07:11 UTC, manstis commented
I couldn't see anything meaningful in the log (that appeared truncated, even when viewing the complete log).. trying again,

2021-10-07 07:31 UTC, radtriste commented
JBoss repository was out ...

Jenkins retest this

2021-10-07 08:24 UTC, manstis commented
OK.. I'm getting somewhere...
```
postgresql.feature:18

    When container is started with env                                                                                                                                          # steps/container_steps.py:71

      | variable                    | value                                    |

      | SCRIPT_DEBUG                | true                                     |

      | QUARKUS_DATASOURCE_JDBC_URL | jdbc:postgresql://10.1.1.10:5432/quarkus |

      | QUARKUS_DATASOURCE_USERNAME | kogito                                   |

      | QUARKUS_DATASOURCE_PASSWORD | s3cr3t                                   |

    Then container log should contain -Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080 -jar /home/trusty-service-postgresql-runner.jar # steps/container_steps.py:30

      Traceback (most recent call last):

        File "/usr/local/lib/python3.6/site-packages/behave/model.py", line 1329, in run

          match.run(runner.context)

        File "/usr/local/lib/python3.6/site-packages/behave/matchers.py", line 98, in run

          self.func(context, *args, **kwargs)

        File "steps/container_steps.py", line 33, in log_contains_msg

          raise Exception("Message '%s' was not found in the logs" % message)

      Exception: Message '-Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080 -jar /home/trusty-service-postgresql-runner.jar' was not found in the logs
```

2021-10-07 09:34 UTC, radtriste commented
builder failure is not related and should be solved once https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/nightly/view/Nightly/job/kogito-examples-deploy/16/ is finished

2021-10-07 10:49 UTC, radtriste commented
Jenkins retest this

2021-10-07 11:50 UTC, manstis commented
@spolti PR is green.

I just need your advice on [this](https://github.com/kiegroup/kogito-images/pull/758#discussion_r723905082) please.

2021-10-07 12:11 UTC, radtriste commented on tests/features/trusty/kogito-trusty-postgresql.feature
> +    Then container log should contain -Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080 -jar /home/trusty-service-postgresql-runner.jar
I guess it is that one: https://github.com/kiegroup/kogito-images/blob/main/tests/features/common-dynamic-resources.feature

2021-10-07 12:45 UTC, manstis commented on tests/features/trusty/kogito-trusty-postgresql.feature
> +    Then container log should contain -Djava.library.path=/home/kogito/lib -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8080 -jar /home/trusty-service-postgresql-runner.jar
OK, done in new commit. Thank-you @radtriste.

2021-10-08 06:27 UTC, radtriste commented
@manstis do we want that in 1.12 ?

2021-10-08 06:42 UTC, manstis commented
Hi @radtriste to be honest I don't know your versioning. I'm used to being on 7.x.

It'd be great if this is in the next release; but I'm less worried about backporting it anywhere.

Does that answer your question?

2021-10-08 06:43 UTC, manstis commented
@radtriste I was just about to chase up @r00ta @spolti and @vaibhavjainwiz for review....

Guys, if needed, can you please review and approve so this can be merged?

2021-10-08 07:01 UTC, r00ta approved these changes
thank you @manstis :)

2021-10-08 07:28 UTC, vaibhavjainwiz approved these changes

2021-10-08 12:29 UTC, radtriste commented
@spolti feel free to merge this :)

2021-10-08 15:52 UTC, spolti approved these changes

2021-10-08 15:52 UTC, merged