[KOGITO-6231] Adding OpenJ9 support for IBM Z and Power support
apache/incubator-kie-kogito-images pull request #829
Opened 2021-10-29 13:31 UTC by levivic

This is to add rhpam Kogito bulilder and runtime images with OpenJ9 (IBM Semeru jdk 11), to support IBM Z and Power ocp. It also introduces the IBM Semeru JDK module. 

See: https://issues.redhat.com/browse/KOGITO-6231

- [x] You have read the [contributors guide](README.md#contributing-to-kogito-images-repository)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a testcase that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster

2021-10-29 13:37 UTC, levivic commented
Additional note to the openj9 version of images is that graalvm support has been removed from these images, because graal and graalvm isn't supported on IBM Z and Power for now.

2021-11-09 09:36 UTC, radtriste commented on rhpam-kogito-builder-openj9-11-rhel8-overrides.yaml
> +    value: "rhpam-kogito,builder,kogito,quarkus,springboot"
maybe add the `openj9` as tag ?

2021-11-09 09:36 UTC, radtriste commented on rhpam-kogito-builder-openj9-11-rhel8-overrides.yaml
> +    description: If set to true, perform a native build. Only supported for RUNTIME_TYPE is 'quarkus'.
if no GraalVM, then there is no native build or ?

2021-11-09 09:36 UTC, radtriste commented on rhpam-kogito-builder-openj9-11-rhel8-overrides.yaml
> +    - zlib-devel
do we still need those ? I thought they were for native compilation or ? @spolti can you confirm ?

2021-11-09 09:36 UTC, radtriste commented on modules/kogito-openjdk/semeru-11-open/module.yaml
> +  value: "openjdk"
openjdk-openj9 ?

2021-11-09 11:15 UTC, mareknovotny commented on rhpam-kogito-builder-openj9-11-rhel8-overrides.yaml
> +    description: If set to true, perform a native build. Only supported for RUNTIME_TYPE is 'quarkus'.
isn't the only supported native on mandrel anyway? @radtriste 
why do we support here graalvm?

2021-11-09 11:28 UTC, AntStephenson commented on rhpam-kogito-runtime-jvm-openj9-11-rhel8-overrides.yaml
> +    branch: rhba-7-openj9-11-rhel-8
To be consistent, this repo name should be unique to the image for example `rhpam-kogito-runtime-jvm-openj9-11`, and the branch should be `rhba-7-rhel-8`

2021-11-09 12:55 UTC, levivic commented on modules/kogito-openjdk/semeru-11-open/module.yaml
> +  value: "openjdk"
hi @radtriste, this is pretty standard as IBM semeru runtime is mostly based on openjdk. This `semeru-11-open` module is also used in cct_module repos https://github.com/jboss-openshift/cct_module/commit/984f6f6e9bb4fe81eedacfd02463f90293061c2a, which is used by other RH products.  So I would worry about this.

2021-11-09 13:03 UTC, levivic commented on rhpam-kogito-runtime-jvm-openj9-11-rhel8-overrides.yaml
> +    branch: rhba-7-openj9-11-rhel-8
hi @AntStephenson, i had this conversation with @mareknovotny in the past, and he had no preference on either unique repo name or unique branch name. Therefore i had https://issues.redhat.com/browse/RCMAUTO-5028 created. Tbh, in other Rh products we work with, either of the two cases happened. And there isn't any issues yet, so i think this would also work. Hope it doesn't cause a big concern, WDYT?

2021-11-09 20:05 UTC, spolti requested changes
Nice work @levivic 
just a few additions

2021-11-09 20:05 UTC, spolti commented on modules/kogito-openjdk/semeru-11-open/configure.sh
> +#chown -R jboss:root $SCRIPT_DIR
it is not needed.

2021-11-09 20:05 UTC, spolti commented on rhpam-kogito-builder-openj9-11-rhel8-overrides.yaml
> +description: "RHPAM Platform with Eclipse OpenJ9 for building Kogito based on Quarkus or SpringBoot"
Is it pure Eclipse J9 or IBM build of Eclipse J9?

2021-11-09 20:05 UTC, spolti commented on rhpam-kogito-builder-openj9-11-rhel8-overrides.yaml
> +    value: "rhpam-kogito,builder,kogito,quarkus,springboot"
+1

2021-11-09 20:05 UTC, spolti commented on rhpam-kogito-builder-openj9-11-rhel8-overrides.yaml
> +  - name: NATIVE
can be removed.

2021-11-09 20:08 UTC, spolti commented
@AntStephenson @radtriste is there a way to add some behave tests to these images?

2021-11-12 19:34 UTC, spolti commented on rhpam-kogito-builder-openj9-11-rhel8-overrides.yaml
> +    - zlib-devel
these are dependencies for GraalVM.

2021-11-12 19:35 UTC, spolti commented on rhpam-kogito-builder-openj9-11-rhel8-overrides.yaml
> +    - zlib-devel
I think we can remove these ones.

2021-11-12 19:36 UTC, spolti commented on rhpam-kogito-runtime-jvm-openj9-11-rhel8-overrides.yaml
> +    branch: rhba-7-openj9-11-rhel-8
all other images are on the same branch `rhba-7-rhel-8`
imho, we should keep it as @AntStephenson have suggested.

2021-11-12 19:37 UTC, spolti commented
> @AntStephenson @radtriste is there a way to add some behave tests to these images?

@AntStephenson @radtriste do you guys know?

2021-11-12 19:38 UTC, spolti commented
@levivic seems that you pushed some new changes but didn't apply some other requested changes, can you please take a look on it?

2021-11-15 15:20 UTC, AntStephenson commented
> > @AntStephenson @radtriste is there a way to add some behave tests to these images?
> 
> @AntStephenson @radtriste do you guys know?

We don't execute these in CPaaS so they would need to be executed in a pipeline somewhere or locally before a build on a developers machine

2021-11-16 17:25 UTC, spolti commented
> > > @AntStephenson @radtriste is there a way to add some behave tests to these images?
> > 
> > 
> > @AntStephenson @radtriste do you guys know?
> 
> We don't execute these in CPaaS so they would need to be executed in a pipeline somewhere or locally before a build on a developers machine

@radtriste @levivic any idea on how can we get this?
At least to have something to run before the release as I suppose it will require a ocp cluster running on Z.

2021-11-16 17:32 UTC, levivic commented
> > > > @AntStephenson @radtriste is there a way to add some behave tests to these images?
> > > 
> > > 
> > > @AntStephenson @radtriste do you guys know?
> > 
> > 
> > We don't execute these in CPaaS so they would need to be executed in a pipeline somewhere or locally before a build on a developers machine
> 
> @radtriste @levivic any idea on how can we get this? At least to have something to run before the release as I suppose it will require a ocp cluster running on Z.

Hi @spolti, IBM PEs are working with DM QE team as well, so whatever QE process is needed for x86 images, the similar tests will be performed on these j9 based images as well before they can be released. QW infrastructures like ocp clusters on z/p are already in place, we are just waiting to finalize the image build and start testing.

2021-11-17 13:41 UTC, spolti commented
@levivic thanks.

2021-11-18 08:46 UTC, mareknovotny commented on rhpam-kogito-runtime-jvm-openj9-11-rhel8-overrides.yaml
> +    branch: rhba-7-openj9-11-rhel-8
@levivic please do what @AntStephenson and @spolti asked for. Ivo also in email suggested the repository names to be clear and agreed on.

2021-11-19 16:35 UTC, spolti approved these changes

2021-11-19 16:36 UTC, spolti commented
@ibek we need to understand it and how we are going to handle this case when we deprecate the builder and runtime images.

2021-11-19 16:50 UTC, ibek commented
@spolti  ye, I was thinking the same when I saw the requests and when we were aligning on the naming of repos, etc... Do you have any ideas already?

2021-11-22 17:34 UTC, spolti commented
@ibek not yet.
Was wondering, as we will not remove this images until 7.14, we might want to keep it?

@levivic is there any plans to port the  Quarkus official images to Z?

2021-11-22 18:16 UTC, levivic commented
> @levivic is there any plans to port the Quarkus official images to Z?

The only RH quarkus **image** i know is quarkus mandrel https://catalog.redhat.com/software/containers/quarkus/mandrel-21-rhel8/60fab204411f224f8bc3c246, which is not supported on z and power. However, RH Build of Quarkus itself is supported on z and p.

2021-11-23 09:54 UTC, AntStephenson approved these changes

2021-11-23 09:54 UTC, antncl commented on rhpam-kogito-builder-openj9-11-rhel8-overrides.yaml
> +    branch: rhba-7-openj9-11-rhel-8
Same as other comment re. name & branch :)

2021-11-23 09:54 UTC, antncl commented on rhpam-kogito-runtime-jvm-openj9-11-rhel8-overrides.yaml
> +    branch: rhba-7-openj9-11-rhel-8
You're right it won't cause issues, it was very much just about the consistency as all of our images follow the same consistent name and branching. Anyone browsing cgit will obviously not find it there and will have to look it up on here. If this is more urgent I would say we can fix this later, since changes in distgit are just derived from the content here anyway.

2021-11-23 09:59 UTC, mareknovotny commented on rhpam-kogito-builder-openj9-11-rhel8-overrides.yaml
> +version: "7.11.0"
```suggestion
version: "7.12.0"
```

2021-11-23 09:59 UTC, mareknovotny commented on rhpam-kogito-runtime-jvm-openj9-11-rhel8-overrides.yaml
> +version: "7.11.0"
maybe we need here 7.12.0, 
```suggestion
version: "7.12.0"
```

2021-11-23 14:03 UTC, spolti commented
> > @levivic is there any plans to port the Quarkus official images to Z?
> 
> The only RH quarkus **image** i know is quarkus mandrel https://catalog.redhat.com/software/containers/quarkus/mandrel-21-rhel8/60fab204411f224f8bc3c246, which is not supported on z and power. However, RH Build of Quarkus itself is supported on z and p.

they should have a jvm runtime as well.
AFAIK they will be using the official openjdk image.

If there are no other option for us to have the runtime image we'll have to provide our own.

@mareknovotny @levivic @errantepiphany @vaibhavjainwiz @radtriste f.y.i

2021-11-25 14:15 UTC, mareknovotny commented
i have no idea, who could answer that @spolti ?

2021-11-25 16:08 UTC, levivic commented
> > > @levivic is there any plans to port the Quarkus official images to Z?
> > 
> > 
> > The only RH quarkus **image** i know is quarkus mandrel https://catalog.redhat.com/software/containers/quarkus/mandrel-21-rhel8/60fab204411f224f8bc3c246, which is not supported on z and power. However, RH Build of Quarkus itself is supported on z and p.
> 
> they should have a jvm runtime as well. AFAIK they will be using the official openjdk image.
> 
> If there are no other option for us to have the runtime image we'll have to provide our own.
> 
> @mareknovotny @levivic @errantepiphany @vaibhavjainwiz @radtriste f.y.i

@spolti not sure what you mean, quarkus is tested with openjdk image for QE, and the same is done on z/p but with openj9 based image https://catalog.redhat.com/software/containers/openj9/openj9-11-rhel8/5ddfdb765a13461646f816f0?architecture=s390x&tag=1.9-9&push_date=1636033798000. Is this what you are referring to? These are regular java jdk images, not quarkus images though.

2021-11-25 19:27 UTC, spolti commented
> e on z/p but with openj9 based image

That might be enough, but it is only for 7.13 or so.
we can go ahead with these changes.

2021-11-25 19:30 UTC, merged